const content = `<p>Bei ya mashine ya kusaga mawe ina maana ukiijua kazi inayotarajiwa. Kinu cha kusaga malighafi kwa recovery ya gravity kinaweza kuhitaji duty tofauti na kinu kinachotayarisha mawe kwa leaching. Uwezo unaotajwa kwenye tangazo hauwezi kulinganishwa vizuri bila kujua aina ya mawe, ukubwa wa vipande na ulaini unaolengwa.</p>
<p>Mwongozo huu unaonyesha namna ya kutofautisha crusher, hammer mill na ball mill, kuomba quotation yenye wigo wazi, na kuhesabu gharama za kuendesha. Hatuna bei ya sasa iliyohakikiwa ya modeli maalumu hapa; mifano ya fedha ni dhana za kupanga na si ofa ya mashine inayouzwa.</p>
<h2 id="aina">Crusher na kinu zina majukumu tofauti</h2>
<p><a href="/equipment-swahili/jaw-crusher">Jaw crusher</a> hupunguza mawe makubwa kabla ya hatua inayofuata. Hammer mill huvunja malighafi kwa nyundo zinazozunguka, wakati <a href="/equipment-swahili/ball-mill-gold-ore">ball mill</a> hutumia media za kusagia ndani ya ngoma. Majina haya pekee hayathibitishi uwezo, ulaini au gharama kwa tani kwa mawe yako.</p>
<p>Kusaga zaidi kunaweza kusaidia kuachia dhahabu iliyofungamana na mawe, lakini pia huongeza kazi na kunaweza kubadilisha tabia ya slurry. <a href="https://www.sgs.com/-/media/sgscorp/documents/corporate/brochures/sgs-canada-inc-minerals-comminution.cdn.en-CA.pdf">Mwongozo wa SGS wa comminution</a> unaeleza nafasi ya majaribio ya grindability kwenye uteuzi wa circuit. Tumia matokeo ya sampuli kuunganisha kinu na mfumo wa recovery, badala ya kudhani kinu kikubwa kinahakikisha dhahabu nyingi zaidi.</p>
<h2 id="duty">Fafanua uwezo kwa saa halisi za kazi</h2>
<p>Ukitarajia tani 30 kwa siku katika saa 10 za kusaga zinazozalisha, wastani unaohitajika ni tani 3 kwa saa. Huu ni mfano wa hesabu ya duty, si uthibitisho wa uwezo wa kinu fulani. Saa za matengenezo, kusafisha na kusubiri mawe zisihesabiwe kama saa za uzalishaji.</p>
<p>Muuzaji apewe ukubwa wa malighafi, ulaini unaolengwa, ugumu, unyevu na matokeo ya recovery. Aeleze kama uwezo wake ni kwa mawe yanayofanana na yako, na kama circuit inajumuisha classification na kurudisha mawe yasiyosagika vya kutosha. “Tani moja” bila kusema kwa saa au kwa batch si specification kamili.</p>
<h2 id="quotation">Omba bei inayoweza kulinganishwa</h2>
<ul><li>Kinu, mota, drive, liners na media za kuanzia, zikiwa na specification.</li><li>Vifaa vya kudhibiti na ulinzi wa umeme na mashine.</li><li>Pampu na classification ikiwa zinahitajika kwenye circuit.</li><li>Ufungashaji, usafirishaji, kodi na kufikisha eneo, kwa wigo ulioelezwa.</li><li>Msingi, kuunganisha umeme, ufungaji, commissioning na mafunzo.</li><li>Spare parts, warranty, nyaraka na huduma baada ya kununua.</li></ul>
<p>Quotation ionyeshe tarehe, muda wa uhalali na kinacholipwa kando. Linganisha ofa kwa duty na vifaa vinavyofanana. Kwa mfano wa gharama za plant nzima yenye crusher na ball mill, soma <a href="/insights-swahili/bei-ya-vifaa-vya-uchimbaji#mawe-magumu">bajeti ya mawe magumu</a>; bei ya plant nzima si bei ya kinu pekee.</p>
<h2 id="umeme">Panga umeme wa kuendesha na kuwasha</h2>
<p>Jumla ya kilowati za mota haitoshi kuchagua jenereta. Mfumo unahitaji kuzingatia current ya kuwasha, mpangilio wa kuwasha mota, voltage na vifaa vingine vinavyofanya kazi kwa wakati mmoja. <a href="https://www.cat.com/en_US/by-industry/electric-power/electric-power-resources/genset-sizing.html">Maelezo ya Caterpillar ya sizing</a> yanatofautisha mzigo wa kawaida na mzigo wa kuanzia. Mpe mtaalamu wa umeme load list na taarifa za mota ili athibitishe mfumo.</p>
<p>Kama mashine imetumika, hakiki nameplate, hali ya drive na sehemu zinazochakaa, pamoja na upatikanaji wa spares. Marekebisho na kupima mashine kabla ya kukubali yaingie kwenye bajeti ya kununua.</p>
<h2 id="gharama">Hesabu gharama kwa tani</h2>
<p>Kwa mfano wa kupanga pekee, tuchukulie tani 780 kwa mwezi na matumizi ya umeme ya 25 kWh kwa tani kwa circuit ya kusaga. Nishati ni 780 × 25 = 19,500 kWh. Kwa bei iliyodhaniwa ya TSh 400 kwa kWh, gharama ya umeme ni TSh 7,800,000 kwa mwezi, au TSh 10,000 kwa tani. Bei hiyo si tariff ya sasa na matumizi si kipimo cha plant iliyofungwa.</p>
<p>Ongeza media, liners, vilainishi, matengenezo na wafanyakazi ili kupata gharama ya circuit. Ukipima umeme wote wa plant, usiandike kiasi hicho kama matumizi ya kinu pekee. Hesabu tofauti itakusaidia kuelewa sehemu inayosababisha gharama.</p>
<h2 id="conclusion">Chagua kinu kwa duty na gharama kamili</h2>
<p>Thibitisha mawe, tani kwa saa na ulaini unaohitajika, kisha linganisha quotation zenye wigo unaofanana. Panga umeme na consumables pamoja na bei ya kununua. Hatua inayofuata ni kuandaa taarifa za sampuli, ratiba ya kazi na eneo la mradi ili supplier aeleze uteuzi na gharama kwa msingi unaopimika.</p>
<h2 id="basis">Vyanzo na dhana za hesabu</h2>
<p>Vyanzo vya SGS na Caterpillar vilikaguliwa tarehe 5 Oktoba 2026. Hesabu za duty na umeme ni mifano ya kufundisha; zinahitaji kubadilishwa kwa matokeo ya majaribio, quotation na bei za mradi wako.</p>`
export default content
