import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Shaba (copper) inazidi kuwa chaguo la kweli kwa wachimbaji wadogo Tanzania, si kwa kampuni kubwa pekee. Mwezi Juni 2025 mtambo wa kwanza wa kisasa wa kuchakata shaba nchini ulifunguliwa Chunya mkoani Mbeya, na hununua madini kutoka kwa wachimbaji wadogo pamoja na kuchakata madini yake. Kwa mwenye leseni aliye na dalili za shaba, swali ni kama auze madini kwa mchakataji, ayachakate eneo lake au asubiri hadi eneo lenye madini lieleweke vizuri zaidi. Jibu linategemea aina ya madini ya shaba, kiwango chake, umbali hadi kwa mnunuzi na gharama ya kuchakata.</p>
<p>Mwongozo huu unaeleza aina kuu za madini ya shaba na njia za kuyachakata, kile mtambo wa Chunya unaonyesha kuhusu kuuza madini ndani ya nchi, na jinsi ya kutathmini eneo lenye madini ya shaba kabla ya kutumia fedha kwenye vifaa. Mfano wa hesabu unaonyesha jinsi kiwango na masharti ya malipo vinavyogeuza lori la madini kuwa makadirio ya mapato.</p>
<h2 id="chunya-plant">Kile mtambo wa Chunya unaonyesha</h2>
<p>Mtambo wa Chunya unaendeshwa na Mineral Access Systems Tanzania (MAST). Kwa mujibu wa taarifa za uzinduzi wake, huchakata madini ya kiwango cha chini yenye takribani 0.5–2% ya shaba kutoka eneo la Mbugani na kuyapandisha kuwa bidhaa ya shaba yenye usafi wa hadi 75% kwa kutumia leaching na cementation. Unaweza kuchakata takribani tani 31,200 za madini kwa mwezi, ambapo takribani tani 4,000 hununuliwa kutoka kwa wachimbaji wadogo nchi nzima, na kampuni imetangaza mipango ya mitambo mingine Manyara, Ruvuma na Dodoma (<a href="https://www.theeastafrican.co.ke/tea/business-tech/tanzania-launches-modern-copper-processing-plant-5088446">The EastAfrican</a>; <a href="https://www.argusmedia.com/en/news-and-insights/latest-market-news/2701443-tanzania-launches-first-copper-processing-plant">Argus</a>, kwa Kiingereza).</p>
<p>Kwa wachimbaji wadogo, mambo muhimu ni kwamba sasa yupo mnunuzi wa ndani wa madini ya shaba, na kwamba anachakata kwa leaching, njia inayofaa baadhi ya aina za madini kuliko nyingine. Thibitisha masharti ya sasa ya ununuzi moja kwa moja kabla ya kuchimba kwa ajili ya kuuza.</p>
<h2 id="ore-types">Jua aina ya madini ya shaba uliyonayo</h2>
<p>Madini ya shaba kwa ujumla yako makundi mawili. <strong>Madini ya oxide</strong>, mara nyingi ya rangi ya kijani au bluu karibu na uso wa ardhi, huyeyuka kwenye tindikali na kwa kawaida huchakatwa kwa leaching, kisha shaba hupatikana kutoka kwenye myeyusho, kwa mfano kwa cementation kwenye vyuma chakavu au kwa solvent extraction na electrowinning kwenye mitambo mikubwa. <strong>Madini ya sulphide</strong>, kwa kawaida yaliyo chini zaidi na yanayong’aa kama metali, hayajibu vizuri leaching rahisi na kwa kawaida husagwa na kukusanywa kwa flotation, kisha huuzwa kama madini yaliyokolezwa (concentrate) kwa ajili ya kuyeyushwa.</p>
<p>Maeneo mengi yenye madini yana aina zote mbili, oxide karibu na uso zikifuatiwa na sulphide kwa kina. Hilo ni muhimu kwa sababu mnunuzi aliyejipanga kwa leaching anaweza kulipa kidogo, au kukataa, madini yasiyoyeyuka vizuri. Ukaguzi wa mineralogy na jaribio rahisi la leaching kwenye sampuli wakilishi vinakuambia madini yako yako kundi gani kabla ya kuamua kuchimba au kununua vifaa.</p>
<h2 id="worked-example">Mfano wa hesabu: thamani ya mzigo wa madini</h2>
<p>Tuseme mchimbaji anapeleka tani 30 za madini makavu yenye 1.5% ya shaba. Mzigo una 30 × 0.015 = tani 0.45, au kg 450, za shaba. Mnunuzi hatalipia yote: malipo yanategemea sehemu inayolipwa iliyokubaliwa, makato yoyote ya unyevu au uchafu, usafiri na bei ya shaba siku ya malipo. Ikiwa masharti ya mnunuzi yangelipia 50% ya shaba iliyomo (dhana), mchimbaji angelipwa kwa kg 225. Zidisha hiyo kwa bei kwa kilo kwenye masharti ya maandishi ya mnunuzi, kisha toa gharama za kuchimba, kupakia na kusafirisha kuona kama mzigo unafaa kupelekwa.</p>
<p>Asilimia hizi ni dhana za kuonyesha njia, si masharti ya mtambo wa Chunya. Muombe mnunuzi yeyote masharti ya maandishi yanayoeleza jinsi madini yanavyochukuliwa sampuli na kupimwa, jinsi unyevu unavyopimwa, sehemu gani ya shaba iliyomo inalipwa, bei ipi inatumika na malipo yanafuata kwa haraka kiasi gani baada ya kupeleka.</p>
<h2 id="sell-or-process">Kuuza madini au kuchakata eneo lako?</h2>
<p>Kuuza madini kwa kawaida ndio mwanzo sahihi kwa mgodi mdogo. Kunahitaji mtaji mdogo, kunaleta mapato mapema na kunazalisha kumbukumbu za assay na malipo zinazoonyesha thamani ya eneo lenye madini. Kuchakata eneo lako kuna maana pale tu tani, kiwango na umbali hadi kwa mnunuzi vinapohalalisha, na majaribio yanapothibitisha njia inayofanya kazi kwenye madini yako.</p>
<p>Mradi mdogo wa leaching na cementation unahitaji upatikanaji na usimamizi salama wa tindikali, pedi au matanki ya leaching yaliyowekewa kinga, usimamizi wa myeyusho na mpango wa myeyusho uliotumika na mabaki, vyote ndani ya kibali cha mazingira. Flotation ya madini ya sulphide inahitaji vifaa vya kuponda, kusaga na flotation vyenye umeme na maji ya kuaminika, na mnunuzi wa mkusanyiko. Njia zote mbili zinahusisha kemikali na mabaki yanayohitaji usanifu na idhini ya mtaalamu, kwa hiyo zichukulie kama miradi yenye majaribio na tathmini ya mazingira, si ununuzi wa vifaa tu.</p>
<h2 id="next-steps">Hatua kabla ya kuwekeza</h2>
<ol>
<li>Thibitisha kuwa leseni yako inajumuisha shaba na kwamba una kumbukumbu za mauzo zinazohitajika na Tume ya Madini.</li>
<li>Chukua sampuli wakilishi kutoka kwenye madini utakayochimba, si vipande teule vyenye shaba nyingi, na zipimwe shaba.</li>
<li>Uliza maabara kama madini ni oxide au sulphide zaidi, na fanya jaribio rahisi la leaching.</li>
<li>Pata masharti ya maandishi ya ununuzi kutoka kwa mnunuzi na kadiria gharama ya usafiri hadi langoni kwake.</li>
<li>Kisha tu linganisha kuendelea kuuza madini na chaguo lolote la kuchakata eneo lako.</li>
</ol>
${renderArticleFaqs("kuchakata-madini-ya-shaba", "sw")}
<h2 id="conclusion">Anza kwa kuthibitisha madini na mnunuzi</h2>
<p>Shaba inawapa wachimbaji wadogo Tanzania njia mpya ya mapato sasa kwa kuwa mchakataji wa ndani ananunua madini. Kama italipa inategemea aina ya madini, kiwango chake, masharti ya mnunuzi na usafiri. Thibitisha hayo kwa assay wakilishi, jaribio la leaching na masharti ya maandishi kabla ya kutumia fedha kwenye vifaa, na chukulia kuchakata eneo lako kama mradi wa baadaye uliojaribiwa. Hatua yako inayofuata ni mpango wa kuchukua sampuli kwenye dalili za shaba kwenye leseni yako.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Taarifa za mtambo wa Chunya zinatoka kwenye ripoti za <a href="https://www.theeastafrican.co.ke/tea/business-tech/tanzania-launches-modern-copper-processing-plant-5088446">The EastAfrican</a> na <a href="https://www.argusmedia.com/en/news-and-insights/latest-market-news/2701443-tanzania-launches-first-copper-processing-plant">Argus</a> (kwa Kiingereza), zilizopitiwa tarehe 7 Oktoba 2026; thibitisha masharti ya sasa na mwendeshaji. Masharti ya leseni na mauzo yathibitishwe na <a href="https://www.tumemadini.go.tz/">Tume ya Madini</a>. Thamani ya madini inatumia kiwango na sehemu ya malipo ya kudhaniwa kuonyesha njia na haiwakilishi masharti ya mnunuzi yeyote. Ukurasa wetu wa <a href="/equipment-swahili/flotation-cell">seli ya flotation</a> na <a href="/insights-swahili/flotation-ya-graphite-na-shaba">mwongozo wa flotation</a> vinaeleza uchakataji wa shaba ya sulphide.</p>`
export default content
