import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Flotation ndiyo njia ya kawaida ya kukusanya madini ya shaba ya sulphide na graphite yenye vipande bapa (flake), madini mawili yanayovutia uwekezaji Tanzania sasa. Graphite inazalishwa Lindi Jumbo na kwenye mitambo ya God Mwanga Gems mkoani Tanga, na madini ya shaba ya sulphide yako chini ya dalili nyingi za oxide ambazo wachimbaji wadogo wanazichimba leo. Mwenye leseni au mwendelezaji mdogo anayetaka mtambo wa flotation lazima abainishe madini, majaribio na mfumo kabla msambazaji yeyote aweze kutoa bei ya usanifu utakaofanya kazi.</p>
<p>Mwongozo huu unaeleza jinsi flotation inavyotenganisha madini, jinsi mfumo unavyotofautiana kwa shaba na graphite, mnunuzi anapaswa kubainisha nini na jinsi ya kukadiria kiasi cha madini yaliyokolezwa (concentrate), yanayoitwa mkusanyiko katika mwongozo huu, ambacho mtambo utazalisha. Ni mwongozo wa kupanga, si mapishi ya kemikali: mpango wa kemikali na mipangilio ya uendeshaji hutoka kwenye majaribio ya madini yako.</p>
<h2 id="how-flotation-works">Jinsi flotation inavyotenganisha madini</h2>
<p>Ndani ya <a href="/equipment-swahili/flotation-cell">seli ya flotation</a>, madini yaliyosagwa huchanganywa na maji na kemikali. Kemikali ya kukusanya chembe (collector) hufunika madini yenye thamani ili yakatae maji, na kemikali ya kuimarisha povu (frother) huimarisha viputo vidogo vya hewa ambavyo kichanganyio (impeller) au kipulizia hewa (blower) husambaza ndani ya tope. Chembe zilizofunikwa hushikamana na viputo na kupanda kuwa povu linalomwagika kama mkusanyiko, huku madini yasiyo na thamani yakibaki kwenye tope na kutoka kama mabaki. Kemikali za kuzuia madini fulani kuelea (depressant) na vidhibiti vya pH huzuia madini yasiyotakiwa yasielee.</p>
<p>Flotation inahitaji chembe laini kiasi cha kuachiliwa kutoka kwenye mwamba na kubebwa na kiputo. Ndiyo sababu mtambo huanza kwa kuponda na kusaga, mara nyingi kwa ball mill iliyofungwa na <a href="/equipment-swahili/spiral-classifier">spiral classifier</a> au hydrocyclone, na ndiyo sababu ukubwa wa kusaga ni moja ya mambo ya kwanza ambayo majaribio lazima yaamue.</p>
<h2 id="copper-circuit">Mfumo kwa madini ya shaba ya sulphide</h2>
<p>Madini ya shaba ya sulphide kwa kawaida husagwa hadi ukubwa ambao madini ya shaba huachiliwa, kisha hupitishwa kwenye flotation ya hatua ya awali (rougher) inayopata shaba nyingi kwenye mkusanyiko wa kiwango cha chini. Seli za kukusanya yaliyosalia (scavenger) hupata shaba zaidi kutoka kwenye mabaki ya rougher, na hatua moja au zaidi za kusafisha (cleaner) hupandisha kiwango cha mkusanyiko kwa kuuelea tena, wakati mwingine baada ya kusaga upya. Mkusanyiko uliokamilika hupunguzwa maji na kuchujwa, mara nyingi kwenye <a href="/equipment-swahili/filter-press">filter press</a>, na kuuzwa kwa kiyeyusho au kiwanda cha kusafisha kwa kemikali.</p>
<p>Madini ya shaba ya oxide hayaelei vizuri kwa collector za kawaida za sulphide na kwa kawaida huchakatwa kwa leaching. Maeneo mengi yenye madini hubadilika kutoka oxide karibu na uso hadi sulphide kwa kina, kwa hiyo jaribu maeneo yote mawili. <a href="/insights-swahili/kuchakata-madini-ya-shaba">Mwongozo wetu wa madini ya shaba</a> unaeleza jinsi ya kuyatofautisha na nini kinahusika katika kuuza madini kwa mchakataji.</p>
<h2 id="graphite-circuit">Mfumo kwa graphite ya flake</h2>
<p>Graphite huelea yenyewe, kwa hiyo changamoto si kuifanya ielee bali kufikia kiwango kikubwa cha kaboni bila kuvunja flake. Flake kubwa huuzwa kwa bei kubwa kuliko ndogo, na kusaga kupita kiasi huharibu thamani hiyo. Kwa hiyo mitambo ya graphite husaga kwa upole, huchukua mkusanyiko wa rougher, kisha huusaga upya kidogo na kuusafisha kwa hatua kadhaa ili kuondoa madini yasiyo na thamani bado yaliyoshikamana na flake. Programu za majaribio zilizochapishwa zinaeleza mkusanyiko wa rougher ukisagwa upya hadi takribani maikroni 150 kisha kusafishwa kwa hatua kadhaa kufikia viwango vya kaboni vya asilimia 90 na zaidi.</p>
<p>Idadi ya hatua za kusafisha, nishati ya kusaga upya na kiwango cha mwisho ni maamuzi ya kupima kati ya kiwango, urejeshaji na ukubwa wa flake. Mnunuzi anapaswa kuomba maabara iripoti mgawanyo wa ukubwa wa flake kwenye mkusanyiko pamoja na kiwango na urejeshaji wake.</p>
<h2 id="worked-example">Kadiria mkusanyiko ambao mtambo utazalisha</h2>
<p>Uzito wa mkusanyiko hutokana na kiwango cha malighafi, urejeshaji na kiwango cha mkusanyiko. Kama mfano wa dhana kwa shaba, mtambo unaochakata tani 100 kwa siku za madini yenye 1.2% ya shaba, ukipata 85% yake kwenye mkusanyiko wenye 25% ya shaba, huzalisha 100 × 0.012 × 0.85 ÷ 0.25 = takribani tani 4.1 za mkusanyiko kwa siku.</p>
<p>Kwa graphite, mtambo unaochakata tani 100 kwa siku zenye 8% ya kaboni ya graphite, ukipata 85% (dhana) kwenye mkusanyiko wa kaboni 94%, huzalisha 100 × 0.08 × 0.85 ÷ 0.94 = takribani tani 7.2 kwa siku. Takwimu hizi zinaonyesha hesabu tu; kiwango chako, urejeshaji na kiwango cha mkusanyiko kinachouzika hutoka kwenye majaribio na masharti ya wanunuzi.</p>
<h2 id="what-to-specify">Cha kubainisha kabla ya kuomba mtambo</h2>
<ol>
<li>Sampuli wakilishi kutoka kila eneo la madini, pamoja na mineralogy inayoonyesha madini yenye thamani yamekaaje.</li>
<li>Matokeo ya majaribio ya kusaga na flotation, ikiwemo locked-cycle tests inapowezekana, yanayotoa kiwango na urejeshaji kwa kila hatua.</li>
<li>Mpango wa kemikali na matumizi yaliyotumika kwenye majaribio.</li>
<li>Kwa graphite, mgawanyo wa ukubwa wa flake kwenye mkusanyiko; kwa shaba, elementi zinazosababisha makato ya bei vilivyomo kwenye mkusanyiko.</li>
<li>Tani kwa siku, saa za kazi, na umeme na maji yanayopatikana.</li>
<li>Jinsi mabaki yatakavyohifadhiwa na maji ya mchakato yatakavyorejeshwa; angalia <a href="/insights-swahili/kurejesha-maji-kwenye-mtambo">mwongozo wa kurejesha maji</a>.</li>
</ol>
${renderArticleFaqs("flotation-ya-graphite-na-shaba", "sw")}
<h2 id="conclusion">Bainisha madini kabla ya seli</h2>
<p>Mtambo wa flotation hufanya kazi pale usagaji, kemikali na mfumo wake vinaposanifiwa kulingana na madini yaliyojaribiwa. Kwa sulphide za shaba lengo ni mkusanyiko safi kwa urejeshaji mzuri; kwa graphite ni mkusanyiko wa kiwango kikubwa unaohifadhi flake kubwa. Vyote viwili vinategemea sampuli wakilishi na majaribio ya hatua kwa hatua. Anza na mineralogy na programu ya majaribio ya flotation kwenye sampuli kutoka kila eneo la madini, kisha waombe wasambazaji watoe bei kwa matokeo hayo.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Wazalishaji wa graphite Tanzania wametajwa kutoka <a href="https://projectblue.com/blue/news-analysis/1315/new-graphite-supply-increases-tanzania’s-market-share">Project Blue</a> (kwa Kiingereza). Maelezo ya kusafisha graphite kwa hatua yanafuata programu za majaribio zilizochapishwa zilizofupishwa na <a href="https://www.jmma.tfbor.bg.ac.rs/?p=347">Journal of Mining and Metallurgy</a> (kwa Kiingereza). Kanuni za seli za flotation zimeelezwa na <a href="https://www.911metallurgist.com/blog/denver-flotation-machine/">911 Metallurgist</a> (kwa Kiingereza). Vyanzo vilipitiwa tarehe 7 Oktoba 2026. Mifano ya mkusanyiko inatumia viwango na urejeshaji wa kudhaniwa kuonyesha hesabu na si matokeo ya eneo lolote lenye madini.</p>`
export default content
