import { CHUNYA_EXAMPLES, MONTHLY_OPERATING_EXAMPLES, totalCost, usd } from '@/data/plant-cost-examples'
const [wash, starter, full] = CHUNYA_EXAMPLES
const categories = ['Usafirishaji, bima, kutoa mzigo na kufikisha eneo', 'Wafungaji na kuinua vifaa', 'Makadirio ya ujenzi', 'Wahandisi na usimamizi wa mradi', 'Majaribio, ukaguzi na vibali', 'Commissioning na vipuri vya mwaka wa kwanza', 'Akiba ya dharura']
const rows = categories.map((label, i) => `<tr><th scope="row">${label}</th><td>${usd(wash.categories[i])}</td><td>${usd(starter.categories[i])}</td><td>${usd(full.categories[i])}</td></tr>`).join('')
const operating = MONTHLY_OPERATING_EXAMPLES[0]

const content = `
<p>Kuanzisha plant ya dhahabu kunahitaji mfumo unaofanya kazi pamoja: malighafi, recovery, maji, umeme, wafanyakazi na namna ya kuhifadhi mabaki baada ya kuchakata. Mashine haziwezi kuanza uzalishaji mpaka sehemu hizo ziwe tayari. Bajeti yako inapaswa kufuata kazi zinazohitajika kutoka kwenye sampuli iliyojaribiwa hadi plant iliyofungwa na kufanyiwa commissioning.</p>
<p>Mwongozo huu unatumia mapendekezo yetu ya Chunya ya Oktoba 2026 kueleza gharama zilizopo kati ya kununua vifaa na kuanza uzalishaji. Utaona jinsi ya kuchagua njia ya alluvial au mawe magumu, kupanga kufikisha na ujenzi, kuweka fedha za kuendesha na kukubaliana masharti ya kupokea plant. Kwa hesabu za kulinganisha gharama za kuanzisha na kuendesha, soma <a href="/bei-ya-vifaa-vya-uchimbaji">mwongozo wa bei za vifaa na plant</a>.</p>

<h2 id="aina-ya-plant">Fafanua plant unayotaka kuanzisha</h2>
<p>Kwa changarawe yenye dhahabu iliyo huru, chunguza kuosha, kuchuja na kutenganisha kwa tofauti ya uzito. Pendekezo la awamu ya kwanza Chunya lina washing screen na sluice sita kwa uwezo wa kubuniwa wa 150 m³ kwa saa. Mpangilio unaruhusu kuongeza vifaa vya kupata dhahabu laini baadaye, kulingana na majaribio na usanifu wa kina. Mfinyanzi mwingi au mahitaji tofauti ya recovery yanaweza kuhitaji mfumo wenye rotary scrubber.</p>
<p>Mawe magumu yanahitaji tathmini tofauti. Kuponda na ball mill huandaa malighafi kwa recovery, huku mahitaji ya kusaga yakithibitishwa kwa majaribio. Gravity inaweza kupata sehemu ya dhahabu; kuongeza CIL au CIP kunakuwa uamuzi mwingine wa uwekezaji ikiwa uchenjuaji unaweza kupata dhahabu ya ziada kwa gharama inayolipa. Malighafi yenye dhahabu iliyofungwa kwenye madini magumu kuchakatwa inaweza kuhitaji matibabu mengine. Chagua plant kwa matokeo ya sampuli, kiasi cha malighafi kinachopatikana na hali ya eneo.</p>
<figure><img src="/equipment/jaw-crusher.jpg" alt="Jaw crusher kwenye katalogi ya Bart Mining" width="1200" height="800" loading="lazy" /><figcaption>Mfano wa kifaa: jaw crusher hupunguza ukubwa wa mawe kabla ya kusaga. Mapendekezo ya alluvial ya Chunya yanayojadiliwa hapa hayana mfumo wa kuponda na kusaga.</figcaption></figure>

<h2 id="vifaa-na-utekelezaji">Tenganisha vifaa na kazi za kufikisha plant kwenye uzalishaji</h2>
<p>Mapendekezo ya Chunya yanatenganisha bei ya vifaa na huduma za utekelezaji. Kifurushi cha sasa cha washing na sluice kina vifaa vya ${usd(wash.equipment)} na takribani ${usd(wash.execution)} za huduma zilizokadiriwa. Jumla ni ${usd(wash.total)} kabla ya kodi za kuagiza zinazolipwa kando, tozo nyingine na mtaji wa mwenye mradi wa kuendesha. Plant mbili za scrubber kwenye pendekezo la awali zina wigo wa kazi na makadirio tofauti.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Jedwali la gharama; sogeza upande kuona safu zote"><p class="article-table-caption">Wigo wa kuanzisha plant kwenye mapendekezo ya Chunya, USD zilizokaribishwa. Huduma ni makadirio.</p><table aria-label="Wigo wa kuanzisha plant kwenye mapendekezo ya Chunya, USD zilizokaribishwa. Huduma ni makadirio."><thead><tr><th scope="col">Kipengele</th><th scope="col">Washing na sluice, 150 m³/saa</th><th scope="col">Scrubber, 75 m³/saa</th><th scope="col">Scrubber, 150 m³/saa</th></tr></thead><tbody>
<tr><th scope="row">Vifaa</th><td>${usd(wash.equipment)}</td><td>${usd(starter.equipment)}</td><td>${usd(full.equipment)}</td></tr>${rows}
<tr><th scope="row">Jumla ya vifaa na utekelezaji</th><td><strong>${usd(wash.total)}</strong></td><td><strong>${usd(starter.total)}</strong></td><td><strong>${usd(full.total)}</strong></td></tr>
</tbody></table></div>
<p>Takwimu zimekaribishwa kutoka kwenye mfumo wa proposal, hivyo ukijumlisha vipengele vinavyoonekana unaweza kupata tofauti ya dola moja. Pendekezo la washing ni la tarehe 5 Oktoba 2026; la scrubber ni la tarehe 3 Oktoba. Hizi ni bei zilizopendekezwa kwa mteja, si gharama za mwisho za plant zilizokamilika. Recovery, uwezo halisi na wigo wa mwisho bado vinategemea majaribio, usanifu na tathmini ya eneo.</p>
<p>Tofauti ya plant mbili zenye 150 m³/saa inafundisha jambo muhimu. Moja ni awamu ya kwanza ya screen na sluice; nyingine ina scrubber, centrifugal recovery na kazi pana zaidi za kuisaidia. Uwezo sawa wa kulisha hauzifanyi kuwa plant zinazofanana. Linganisha kushughulikia mfinyanzi, ukubwa wa dhahabu, matokeo ya majaribio, mahitaji ya maji na huduma zilizojumuishwa kabla ya kuchagua uwekezaji.</p>

<h2 id="maji-umeme-mabaki">Panga maji, umeme na mabaki kama sehemu ya plant</h2>
<p>Pendekezo la washing na sluice lina takribani 400 m³/saa za maji yanayozunguka kwa kuosha kwenye pumping head ya mita 35–40, na takribani 147 kW za jumla ya uwezo wa vifaa vya umeme, pamoja na jenereta ya 200 kW kwenye mpangilio uliopangiwa bei. Maji yanayozunguka si lazima yawe mahitaji yote ya maji mapya: sehemu inaweza kurudishwa baada ya kutuliza tope. Pampu halisi hutegemea umbali wa chanzo, mwinuko na upotevu wa msukumo kwenye mabomba, hivyo ukaguzi wa maji unaweza kubadili vifaa na gharama za kuendesha.</p>
<p>Kwa mawe magumu, kinu kinaweza kuamua sehemu kubwa ya matumizi ya umeme. Orodha ya mota, namna ya kuziwasha na tathmini ya chanzo cha umeme vikamilike kabla ya kuchagua jenereta au kuunganisha umeme wa gridi. Usanifu pia unahitaji wiring salama, mifereji na hifadhi ya mabaki inayofaa kwa malighafi na mchakato. Uchenjuaji unaongeza mahitaji ya kuzuia uvujaji na kufanya ufuatiliaji.</p>
<p>Omba michoro na kiasi cha kazi kinachounda makadirio ya ujenzi. Misingi, nafasi ya kushusha vifaa, mabwawa ya kutuliza tope, mifereji, hifadhi ya mafuta na chumba cha dhahabu viwe na majukumu yaliyo wazi. Kipengele ambacho bado hakijapewa bei kibaki kwenye bajeti kama gharama inayohitaji kutatuliwa.</p>

<h2 id="bajeti-ya-mwenye-mradi">Tengeneza bajeti ya mwenye mradi pamoja na pendekezo</h2>
<p>Jumla ya proposal haifadhili biashara nzima ya uchimbaji. Ongeza ardhi au haki ya kutumia eneo, haki za madini, uchimbaji na kusafirisha malighafi, kununua au kukodi mitambo ya uchimbaji, kodi za kuagiza, tozo, mkopo na gharama za usimamizi wa kawaida. Thibitisha vibali na tozo kwa mamlaka na washauri husika. Dhana ya ushuru iliyotumika Chunya haithibitishi msamaha kwa mwagizaji au mzigo mwingine.</p>
<p>Tenganisha akiba ya dharura ya ujenzi na fedha za kuendesha. Ya kwanza inashughulikia mambo yasiyojulikana kwenye utekelezaji. Ya pili inalipia mafuta, mishahara, consumables na servicing wakati uzalishaji na malipo ya dhahabu yanaanza. Ukitumia akiba kununua kifaa cha ziada, rekebisha mpango wa fedha pia.</p>

<h2 id="mtaji-wa-kuendesha">Weka fedha za miezi ya kwanza ya uzalishaji</h2>
<p><a href="/bei-ya-vifaa-vya-uchimbaji#gharama-za-mwezi">Mfano wetu wa kuendesha</a> unatumia washing plant ya 150 m³/saa, saa 20 zilizopangwa kwa siku, siku 26 kwa mwezi na 75% ya muda huo ukiwa uzalishaji halisi. Kwa dhana zilizoelezwa za mafuta, kulisha, wafanyakazi, sehemu zinazochakaa, maji na usimamizi, gharama ya kuchakata ni takribani ${usd(totalCost(operating.costs))} kwa mwezi. Miezi miwili ingehitaji takribani ${usd(totalCost(operating.costs) * 2)} juu ya proposal na gharama nyingine za mwenye mradi.</p>
<p>Hii ni mfano wa akiba ya fedha, si quotation ya kuendesha wala utabiri wa uzalishaji wa Chunya. Kwa mradi wako, tumia tathmini ya load na matumizi ya mafuta, pata bei za kulisha plant na wafanyakazi eneo lako, na pima athari ya kufanya kazi saa chache. Kuanzisha polepole au kuchelewa kupata malipo kunaweza kuhitaji akiba ya muda mrefu zaidi.</p>
<p>Mapato pia yahesabiwe kwa msingi uliothibitishwa. Grade ya alluvial mara nyingi ni gramu kwa mita ya ujazo, na ya mawe magumu ni gramu kwa tani. Tumia kipimo kimoja kinacholingana na malighafi, grade iliyopimwa na recovery inayofaa kwa mfumo wako. Hesabu fedha zinazobaki baada ya uchimbaji, kuchakata, makato ya mauzo na mkopo; thamani ghafi ya dhahabu haitoshi kuthibitisha faida.</p>

<h2 id="ratiba-na-kukabidhi">Kubalianeni muda na masharti ya kukabidhi plant</h2>
<p>Pendekezo la sasa la washing linakadiria wiki 16 kutoka mwanzo wa utekelezaji hadi uzalishaji. Plant za scrubber za awali zinakadiria wiki 24 na 26.5. Hizi ni ratiba zenye kazi zinazotegemeana, si ahadi kwa kila plant. Utengenezaji, ukaguzi, usafirishaji, forodha na ufungaji vyote vinahitaji muda, huku ujenzi na maji vikiendelea sambamba pale inapowezekana.</p>
<p>Kabla ya kuagiza, kubalianeni hali ya malighafi ya majaribio, namna ya kuthibitisha uwezo na recovery, hitilafu zinazokubalika na mafunzo ya waendeshaji. Pendekezo la washing linahitaji zamu tatu mfululizo karibu na uwezo wa kubuniwa bila hitilafu muhimu kabla ya kusaini commissioning. Recovery bado ihakikiwe kwa sampuli zinazowakilisha mchakato na hesabu ya dhahabu inayoingia na kutoka, badala ya kudhani mashine inayozunguka imepata dhahabu.</p>
<p>Kukabidhi kujumuisha maelekezo ya kuendesha, nyaraka za umeme na mchakato, mpango wa matengenezo, vipuri vinavyopendekezwa na orodha ya kazi iliyobaki. Plant iko tayari pale timu inaweza kuiendesha na kuitunza kwa hali zilizokubaliwa.</p>

<h2 id="maswali">Maswali kabla ya kuanzisha plant</h2>
<h3>Plant ya bei ya chini ndiyo bora kuanzia?</h3>
<p>Inaweza kuwa bora ikiwa majaribio yanaunga mkono mfumo na mradi unaweza kutoa malighafi na maji yanayohitajika. Pendekezo la washing na sluice la Chunya ni njia maalumu ya awamu ya kwanza, yenye nafasi ya kuongeza recovery. Mfumo wa bei ya chini usioweza kushughulikia mfinyanzi au ukubwa wa dhahabu unaweza kuongeza gharama kwa kupoteza uzalishaji.</p>
<h3>Nahitaji elution ninapoongeza CIP au CIL?</h3>
<p>Unahitaji njia iliyopangwa ya kupata dhahabu kutoka kwenye kaboni iliyobeba dhahabu, iwe eneo lako au kupitia mtoa huduma anayefaa. Linganisha usafiri, ukubwa wa batch, ulinzi, malipo na muda wa kupata fedha kabla ya kuamua kumiliki vifaa. Njia hiyo iwe kwenye bajeti ya uchenjuaji tangu mwanzo.</p>
<h3>Nitume nini ili kupata pendekezo la plant?</h3>
<p>Tuma eneo, aina ya deposit na malighafi, sampuli au matokeo ya majaribio, kiasi cha malighafi unachoweza kutoa kwa muda endelevu, saa za kazi, chanzo cha maji na umeme. Eleza vifaa na miundombinu iliyopo pamoja na huduma unazotaka zijumuishwe. Hii inasaidia kupata bei ya kazi unayohitaji.</p>

<h2 id="hitimisho">Bajeti ya kuanza ikufikishe kwenye plant unayoweza kuendesha</h2>
<p>Chagua njia ya recovery kwa malighafi na matokeo ya majaribio, kisha panga vifaa, kufikisha, miundombinu na commissioning kama mradi mmoja. Ongeza gharama za mwenye mradi na akiba ya kuendesha kabla ya kuamua uwezo wako wa kuwekeza. Chunya inaonyesha tofauti hiyo kwa vitendo: vifaa vya ${usd(wash.equipment)} vinakuwa takribani ${usd(wash.total)} ukijumuisha utekelezaji uliopendekezwa, na biashara bado inahitaji fedha za kuendesha.</p>
<p>Hatua inayofuata ni kuandaa taarifa za eneo na malighafi zinazoweza kusaidia usanifu na quotation yenye vipengele. Taarifa hizo zitatue maswali makubwa ya maji, recovery, umeme na upatikanaji wa malighafi, ili bajeti ikuongoze kwenye uamuzi wazi wa kufungua plant.</p>

<h2 id="vyanzo">Msingi wa mwongozo huu</h2>
<p>Gharama za kuanzisha zimetolewa kwenye bei za upande wa mteja kwenye mapendekezo ya Chunya ya tarehe 3 na 5 Oktoba 2026 na hesabu za Plant Planner. Huduma bado ni makadirio ya awali. Bei za wasambazaji na taarifa za ndani za biashara hazijawekwa hapa. Akiba ya kuendesha imehesabiwa kwa dhana zilizoelezwa kwenye mwongozo wa bei wa vifaa; si gharama ya kuendesha iliyopimwa kutoka kwenye proposal.</p>
<p>Kwa maandalizi ya eneo, soma <a href="https://www.cat.com/en_US/by-industry/electric-power/electric-power-resources/genset-sizing.html">mwongozo wa Caterpillar wa kuchagua uwezo wa jenereta (Kiingereza)</a> na <a href="https://eia.nemc.or.tz/dev/web/home.eu">mfumo wa NEMC wa usajili wa tathmini ya mazingira</a>. Vyanzo hivi vinaeleza sehemu za maandalizi; havithibitishi bajeti ya proposal wala kutoa kibali kwa eneo fulani.</p>
`
export default content
