const content = `<p>Ukitaka kuanza uchimbaji mdogo, hatua ya kwanza ni kuthibitisha haki ya kufanya kazi kwenye eneo na aina ya leseni inayofaa shughuli zako. Kununua mashine au kukubaliana na mwenye ardhi pekee hakuthibitishi kwamba unaweza kuchimba madini hapo. Maandalizi mazuri huunganisha hali ya eneo, ustahiki wa mwombaji na mpango wa kazi kabla ya kutumia fedha nyingi.</p>
<p>Mwongozo huu unakusaidia kuandaa maombi ya Primary Mining Licence, inayojulikana kama PML, na maswali ya kujadili na Afisa Madini Mkazi. Lengo ni uwe na taarifa na nyaraka zinazohitajika kwa eneo lako, badala ya kutegemea orodha ya jumla kana kwamba kila ombi lina hali sawa.</p>
<h2 id="pml">PML inahusu shughuli gani?</h2>
<p><a href="https://www.tumemadini.go.tz/pages/licenseservice/">Maelezo ya leseni ya Tume ya Madini</a> yanaeleza PML kama leseni ya uchimbaji mdogo yenye matumizi madogo ya mashine au teknolojia na mtaji wa awali usiozidi dola milioni 5 za Marekani au thamani inayolingana kwa shilingi. Maelezo hayo yanataja muda wa miaka saba na ustahiki wa uraia wa Tanzania. Thibitisha masharti yanayotumika kwa mwombaji wako na toleo la sasa la sheria kabla ya kuwasilisha ombi.</p>
<p>PML isichanganywe na leseni ya biashara, processing, smelting au refining. Ukipanga kupokea mawe kutoka kwa wachimbaji wengine au kuongeza shughuli za uchakataji, uliza Tume kama wigo wako unahitaji leseni au idhini nyingine. Ukubwa wa mashine pekee haujibu swali hilo.</p>
<h2 id="eneo">Thibitisha eneo kabla ya kulipa kwa mradi</h2>
<p>Andaa ramani yenye mipaka na viwianishi vya eneo, ukieleza mfumo wa kuratibu uliotumika. Kisha hakiki hali ya eneo kupitia mfumo rasmi wa cadastre na ofisi ya madini. Ramani inayoonekana kuwa wazi kwenye mazungumzo ya kawaida haitoshi kuthibitisha hali ya maombi au haki zilizopo.</p>
<p>Pia jadili namna ya kupata ruhusa ya kuingia na kutumia ardhi. Haki ya madini na makubaliano ya matumizi ya ardhi ni mambo yanayohitaji kushughulikiwa kwa pamoja, lakini moja isitumike kama ushahidi wa moja kwa moja wa jingine. Ikiwa eneo lina haki nyingine au mgogoro, pata ufafanuzi rasmi kabla ya kulipa amana ya vifaa.</p>
<h2 id="nyaraka">Andaa jalada la mwombaji</h2>
<p><a href="https://www.tumemadini.go.tz/pages/applicationprocedure/">Utaratibu wa maombi wa Tume</a> unaeleza ustahiki na nyaraka kwa aina tofauti za waombaji na leseni. Omba orodha ya sasa inayohusu PML yako, pamoja na njia ya kuwasilisha na namna ya kulipa ada. Usinakili masharti ya leseni kubwa au ya mwombaji mwingine bila kuthibitisha yanakuhusu.</p>
<ul><li>Taarifa za utambulisho, uraia na mawasiliano ya mwombaji.</li><li>Nyaraka za kampuni au ushirika ikiwa ombi si la mtu binafsi.</li><li>Ramani, viwianishi na madini yanayoombewa leseni.</li><li>Maelezo ya kazi iliyopangwa na uwezo wa kuitekeleza.</li><li>Nyaraka nyingine, fomu na malipo zinazotajwa kwenye maelekezo rasmi ya ombi.</li></ul>
<p>Hifadhi nakala za nyaraka ulizowasilisha, kumbukumbu ya ombi na stakabadhi za malipo. Ada za maombi, maandalizi na kodi ya pango la mwaka zinaweza kuwa hatua tofauti; tumia maelekezo na namba ya malipo uliyopewa badala ya bei isiyo na tarehe kutoka kwa mtu mwingine.</p>
<h2 id="hatua">Fuatilia maombi kwa hatua zinazoeleweka</h2>
<ol><li>Thibitisha ustahiki, eneo na aina ya leseni na ofisi husika.</li><li>Fungua au tumia akaunti yako kwenye mfumo rasmi unaoelekezwa na Tume.</li><li>Jaza ombi na wasilisha nyaraka kwa njia inayotakiwa, mtandaoni au nakala nyingine inapohitajika.</li><li>Lipa kwa maelekezo rasmi na hifadhi uthibitisho.</li><li>Jibu maombi ya ufafanuzi na fuatilia hatua ya uhakiki.</li><li>Ukikubaliwa, soma masharti ya leseni na tarehe zake, na panga malipo na wajibu unaofuata.</li></ol>
<p>Hakuna muda wa kupewa leseni unaohakikishwa kwenye mwongozo huu. Ombi lenye nyaraka halimaanishi eneo limeidhinishwa au kwamba unaweza kuanza uchimbaji wakati unasubiri.</p>
<h2 id="baada">Panga kazi baada ya leseni kutolewa</h2>
<p>Tenganisha kupata leseni na kupata mradi ulio tayari kufanya kazi. Hakiki mipango ya uchimbaji, mazingira, usalama, jamii na masharti mengine yanayotumika. Kwa masuala ya mazingira, <a href="https://eia.nemc.or.tz/dev/web/home.eu">mfumo wa NEMC</a> unaeleza majukumu ya mwendelezaji wa mradi na mtaalamu aliyesajiliwa; mtaalamu akusaidie kuthibitisha njia inayofaa shughuli zako.</p>
<p>Kwa mfano wa kupanga tu, mwombaji anayetarajia plant ya mawe magumu anapaswa kuthibitisha sampuli, maji, umeme na eneo la mabaki kabla ya kuweka oda ya crusher na ball mill. Leseni inaruhusu shughuli chini ya masharti yake, lakini haithibitishi kiasi cha madini, recovery au faida. Soma pia <a href="/gharama-ya-plant-ya-dhahabu">bajeti ya kuanzisha plant</a>.</p>
<h2 id="conclusion">Anza na eneo na masharti yaliyothibitishwa</h2>
<p>Maombi mazuri ya PML yanaanza kwa kuthibitisha mwombaji na eneo, kisha kufuata utaratibu na nyaraka rasmi. Baada ya leseni, unahitaji bado kupanga approvals, usalama na uwezo wa mradi kujiendesha. Hatua yako inayofuata ni kupeleka ramani na maelezo ya shughuli kwa Afisa Madini Mkazi ili uthibitishe orodha inayohusu ombi lako.</p>
<h2 id="basis">Vyanzo na wigo</h2>
<p>Kurasa rasmi za Tume ya Madini na NEMC zilikaguliwa kwa mwongozo huu tarehe 5 Oktoba 2026. Ada, ukubwa unaoruhusiwa wa eneo na masharti ya ombi lazima vithibitishwe kwa aina ya madini na leseni husika; havijawekwa kama viwango vya jumla hapa.</p>`
export default content
