import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Madini ya betri yameleta aina mpya ya miradi Afrika Mashariki. Nchini Tanzania, mradi wa nickel wa Kabanga unapanga kuchimba madini ya nickel ya sulphide mkoani Kagera na kuyasafisha Kahama, na kampuni za utafiti zinajaribu pegmatite zenye lithium katika ukanda huu. Kwa kampuni ndogo au mwenye leseni aliye na dalili za lithium au nickel, njia ya kuchakata huamua thamani ya eneo lenye madini muda mrefu kabla mtambo wowote haujajengwa, kwa sababu huamua bidhaa inayoweza kuuzwa na majaribio yanayohitajika kuithibitisha.</p>
<p>Mwongozo huu unatoa muhtasari wa jinsi madini ya lithium ya mawe magumu na nickel ya sulphide yanavyochakatwa, bidhaa gani yanazalisha na mradi wa hatua za mwanzo unapaswa kujaribu na kupangia bajeti nini. Mfano wa hesabu unaonyesha jinsi kiwango cha madini na urejeshaji vinavyoamua uzito wa madini yaliyokolezwa (concentrate) ya lithium, yanayoitwa mkusanyiko katika mwongozo huu. Ni muhtasari wa kupanga, si usanifu wa mchakato.</p>
<h2 id="lithium-spodumene">Lithium ya mawe magumu: kukusanya spodumene</h2>
<p>Lithium nyingi ya mawe magumu hutoka kwenye spodumene, madini yenye lithium yaliyo ndani ya pegmatite. Migodi kwa kawaida huuza mkusanyiko wa spodumene, wenye lengo la takribani 6% ya lithium oxide (Li₂O), kwa viwanda vinavyoubadilisha kuwa kemikali za lithium. Njia mbili za kukusanya hutumika, peke yake au pamoja. Dense media separation (DMS) hutenganisha mawe yaliyopondwa ndani ya kimiminika kizito na hufanya kazi pale spodumene inapoachiliwa kwenye ukubwa mkubwa; huondoa takataka nyingi kabla ya kusaga laini. Flotation hutumika pale spodumene inapoachiliwa tu kwenye ukubwa laini zaidi, kwa kawaida kwa collector za fatty acid baada ya kuosha na kuondoa tope laini, kwa sababu tope laini huharibu flotation.</p>
<p>Uchafu wa chuma ni muhimu kwa wanunuzi, kwa hiyo mifumo mara nyingi hujumuisha <a href="/equipment-swahili/magnetic-separator">utenganishaji wa sumaku</a> kuondoa madini yenye chuma na vipande vya chuma vilivyochakaa kwenye mkusanyiko. Mica na feldspar pia vinaweza kuondolewa kwa flotation tofauti. Programu ya majaribio huamua mchanganyiko unaohitajika kulingana na madini.</p>
<h2 id="nickel-sulphide">Nickel ya sulphide: mkusanyiko na usafishaji</h2>
<p>Madini ya nickel ya sulphide kwa kawaida hupondwa, husagwa na kukusanywa kwa <a href="/equipment-swahili/flotation-cell">flotation</a> kuwa mkusanyiko wa nickel, ambao pia hubeba shaba na cobalt. Mkusanyiko kisha huyeyushwa au huchakatwa kwa hydrometallurgy kuzalisha metali iliyosafishwa au bidhaa za kati. Kabanga inaonyesha njia hii: madini kutoka mgodi wilayani Ngara yatakusanywa na mkusanyiko kusafishwa kwenye kiwanda cha hydrometallurgy Kahama kuzalisha nickel, shaba na cobalt. Mradi umepangwa kwa tani milioni 3.4 za madini kwa mwaka na gharama ya mtaji ya takribani USD milioni 942.</p>
<p>Kwa kampuni ndogo, jambo kuu ni kwamba thamani ya nickel hupimwa kupitia mkusanyiko wake na masharti ya usafishaji. Mineralogy inayoonyesha nickel imekaaje, na kiasi gani kinaingia kwenye mkusanyiko wa flotation, ni muhimu kama kiwango kwenye sampuli za uchimbaji.</p>
<h2 id="worked-example">Jinsi kiwango na urejeshaji vinavyoamua uzito wa mkusanyiko</h2>
<p>Mkusanyiko ambao mradi wa lithium huzalisha hutokana na kiwango cha madini, urejeshaji na kiwango cha mkusanyiko. Kama mfano wa dhana, madini yenye 1.3% Li₂O, ambapo 70% ya lithium hupatikana kwenye mkusanyiko wa 6% Li₂O, hutoa uzito wa mkusanyiko wa 1.3 × 0.70 ÷ 6 = takribani 15% ya madini. Kila tani 1,000 za madini zingezalisha takribani tani 152 za mkusanyiko.</p>
<p>Uwiano huo huendesha uchumi wa mradi: huamua kiasi cha madini kinachopaswa kuchimbwa na kuchakatwa kwa kila tani inayouzwa na kiasi cha usafiri ambacho bidhaa inahitaji. Badilisha kiwango na urejeshaji wa dhana kwa assay na majaribio yako; urejeshaji hasa hutofautiana sana kulingana na jinsi spodumene ilivyokaa.</p>
<h2 id="exploration-checklist">Mradi wa hatua za mwanzo unapaswa kufanya nini</h2>
<ol>
<li>Chimba mashimo ya utafiti ya kutosha kubainisha maeneo yenye madini, ukihifadhi sampuli za mwamba wa kuchimba (core) au <a href="/equipment-swahili/rc-drilling-rig">sampuli za RC</a> kwa assay na metallurgy. <a href="/insights/assay-laboratory-tanzania">Mwongozo wetu wa maabara ya assay</a> (kwa Kiingereza) unaeleza kushughulikia sampuli na ukaguzi wa ubora.</li>
<li>Fanya mineralogy kubaini madini ya lithium au nickel, ukubwa wa chembe zake na yameshikamana na nini.</li>
<li>Agiza majaribio ya hatua kwa hatua: majaribio ya DMS (kimiminika kizito) na flotation kwa lithium; flotation na uchambuzi wa mkusanyiko kwa nickel. Angalia <a href="/insights/plant-test-work-guide">mwongozo wa majaribio</a> (kwa Kiingereza).</li>
<li>Waombe wanunuzi watarajiwa masharti ya mkusanyiko, ikiwemo elementi zinazosababisha makato ya bei kama chuma kwenye mkusanyiko wa spodumene.</li>
<li>Panga umeme, maji na mabaki mapema; njia zote mbili zinahitaji umeme wa kudumu na huzalisha mabaki mengi.</li>
</ol>
${renderArticleFaqs("kuchakata-lithium-na-nickel", "sw")}
<h2 id="conclusion">Thibitisha bidhaa kabla ya mtambo</h2>
<p>Maeneo yenye madini ya lithium au nickel hupimwa thamani kupitia mkusanyiko unaoweza kuuzalisha na masharti ambayo mnunuzi atatoa. Kwa spodumene hiyo inamaanisha kujaribu kama DMS, flotation au vyote vinaweza kufikia takribani 6% Li₂O kwa chuma kidogo; kwa nickel ya sulphide inamaanisha kuthibitisha mkusanyiko wa flotation na njia ya usafishaji. Jenga programu ya uchimbaji wa mashimo ya utafiti, mineralogy na majaribio kuzunguka bidhaa hizo, na panga ukubwa wa vifaa pale tu matokeo yanapopatikana.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Njia za kukusanya spodumene na lengo la 6% Li₂O zinafuata <a href="https://www.911metallurgist.com/blog/froth-flotation-spodumene-processing-lithium-extraction">muhtasari wa 911 Metallurgist kuhusu flotation ya spodumene</a> (kwa Kiingereza) na taarifa za miradi zilizochapishwa. Takwimu za Kabanga zinatoka <a href="https://www.tanzaniainvest.com/mining/kabanga-nickel-project-implementation">TanzaniaInvest (Juni 2026)</a> (kwa Kiingereza). Vyanzo vilipitiwa tarehe 7 Oktoba 2026. Mfano wa mkusanyiko unatumia kiwango na urejeshaji wa kudhaniwa kuonyesha hesabu na si matokeo ya eneo lolote lenye madini.</p>`
export default content
