import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Madini mazito kama ilmenite, rutile, zircon, monazite na magnetite hupatikana kwenye mchanga wa fukwe na mito na kwenye madini yaliyokolezwa (concentrate), yanayoitwa mkusanyiko katika mwongozo huu, ambayo wachimbaji wa dhahabu huzalisha kila siku. Kuyatenganisha kunatumia sifa mbili za kimaumbile: msongamano na sumaku. Vifaa vya gravity hupanga chembe kwa msongamano wake, na vitenganishi vya sumaku huzipanga kwa nguvu ambayo sumaku inazivuta. Shughuli nyingi za madini mazito zinahitaji vyote viwili, kwa mpangilio sahihi, na uchaguzi wa vifaa unategemea madini yaliyopo.</p>
<p>Mwongozo huu unaeleza tofauti ya utenganishaji wa gravity na wa sumaku, jinsi vinavyoshirikiana kwenye mfumo wa mchanga wa madini, na jinsi mgodi wa dhahabu unavyoweza kutumia sumaku kusafisha mchanga mweusi wa mkusanyiko. Mfano wa hesabu unaonyesha jinsi kuondoa magnetite kunavyopunguza mkusanyiko ambao mchimbaji wa dhahabu anapaswa kuyeyusha.</p>
<h2 id="gravity">Gravity hupanga kwa msongamano</h2>
<p>Vifaa vya gravity hutenganisha chembe zenye msongamano tofauti. Spiral concentrator, <a href="/equipment-swahili/shaking-table-gold">shaking table</a>, jig na <a href="/equipment-swahili/centrifugal-gold-concentrator">centrifugal concentrator</a> vyote huacha chembe nzito zitulie huku quartz nyepesi na udongo wa mfinyanzi vikisombwa. Kwenye mchanga wa madini, spiral za gravity za majimaji kwa kawaida huja kwanza, zikigeuza mchanga mwingi kuwa mkusanyiko mdogo zaidi wa madini mazito wenye madini yote mazito pamoja.</p>
<p>Gravity haiwezi kutenganisha madini mazito yenyewe kwa yenyewe pale msongamano wake unapokaribiana. Ilmenite, rutile na zircon yote ni mazito, kwa hiyo yakishakusanywa pamoja, sifa nyingine inahitajika kuyagawanya.</p>
<h2 id="magnetic">Sumaku hupanga kwa jinsi madini yanavyojibu sumaku</h2>
<p><a href="/equipment-swahili/magnetic-separator">Kitenganishi cha sumaku</a> hutumia tofauti za jinsi madini yanavyovutwa na sumaku. Madini yanayovutwa sana na sumaku kama magnetite huondolewa kwa drum za nguvu ndogo. Madini yanayovutwa kidogo na sumaku kama ilmenite, garnet na monazite yanahitaji vitenganishi vya nguvu kubwa, vinavyofikia takribani gauss 7,000–20,000. Madini yasiyovutwa na sumaku kama rutile na zircon hupita. Kwenye mitambo ya mchanga wa madini, utenganishaji wa sumaku mara nyingi huunganishwa na utenganishaji wa electrostatic, unaogawanya madini kwa jinsi yanavyopitisha umeme, ili kuzalisha bidhaa tofauti za ilmenite, rutile na zircon.</p>
<h2 id="mineral-sands">Jinsi vinavyoshirikiana kwenye mchanga wa madini</h2>
<p>Njia ya kawaida ya mchanga wa madini ina sehemu mbili. Mtambo wa majimaji kwenye eneo lenye madini hutumia spiral za gravity kutengeneza mkusanyiko wa madini mazito. Mtambo wa kutenganisha madini kisha hukausha mkusanyiko huo na kuugawanya kwa vitenganishi vya sumaku na electrostatic, wakati mwingine pamoja na kusafisha zaidi kwa gravity. Mpangilio ni muhimu: gravity huondoa mchanga mwepesi mwingi kwa gharama ndogo, na hatua za sumaku na electrostatic kisha hutenganisha madini ambayo gravity haiwezi.</p>
<p>Tanzania ina miradi ya aina hii. Mwezi Machi 2024 leseni ya kuchimba mchanga wa madini ilitolewa kwa mradi wilayani Handeni, mkoa wa Tanga, ulioripotiwa kuwa na tani milioni 268 za mchanga wa madini mazito, zikiwemo tani milioni 74 za akiba iliyothibitishwa (<a href="https://www.tanzaniainvest.com/mining/licenses-mineral-sands-mining-handeni-metal-refining-kahama">TanzaniaInvest</a>, kwa Kiingereza).</p>
<h2 id="gold-black-sand">Kusafisha mkusanyiko wa dhahabu kwa sumaku</h2>
<p>Wachimbaji wa dhahabu hukutana na madini hayo hayo kwenye bidhaa za sluice na concentrator kama mchanga mweusi. Magnetite kwenye mkusanyiko huo huongeza uzito, huchelewesha kusafisha kwenye meza na huongeza flux inayohitajika kuyeyusha. Kwa kuwa dhahabu haivutwi na sumaku, sumaku huondoa magnetite na kuiacha dhahabu. Kwa kiwango kidogo sumaku ya mkono au drum ndogo inatosha; shughuli kubwa hutumia drum ya sumaku ya nguvu ndogo kwenye mkusanyiko kabla ya shaking table.</p>
<p>Kama mfano wa dhana, tuseme mkusanyiko wa gravity wa siku moja una uzito wa kg 50 na 60% yake ni magnetite. Kuondoa magnetite kunaacha 50 × (1 − 0.60) = kg 20 za kusafisha kwenye meza na kuyeyusha. Kagua sehemu ya sumaku mara kwa mara kwa karai au assay, kwa sababu dhahabu inaweza kunaswa kwenye mabonge yenye unyevu ambayo sumaku huinua.</p>
<h2 id="next-steps">Majaribio ya kuagiza</h2>
<ol>
<li>Mineralogy ya sampuli wakilishi au mkusanyiko, inayoonyesha madini mazito yaliyopo na uwiano wake.</li>
<li>Jaribio la kimiminika kizito au gravity kupima kiasi cha mkusanyiko wa madini mazito kinachopatikana.</li>
<li>Jaribio la jinsi madini yanavyojibu sumaku kwa nguvu tofauti, na majaribio ya electrostatic pale rutile na zircon ni muhimu.</li>
<li>Kwa mkusanyiko wa dhahabu, mgawanyo rahisi wa sumaku pamoja na assay za sehemu zote mbili kuthibitisha hakuna dhahabu inayopotea.</li>
</ol>
${renderArticleFaqs("utenganishaji-wa-sumaku-au-gravity", "sw")}
<h2 id="conclusion">Tumia msongamano kwanza, kisha sumaku</h2>
<p>Utenganishaji wa gravity na wa sumaku hujibu maswali tofauti. Gravity hukusanya madini mazito na kuondoa takataka nyepesi; sumaku, mara nyingi pamoja na electrostatic, hugawanya madini mazito yenyewe kwa yenyewe. Kwa mchanga wa madini hiyo inamaanisha mfumo wa hatua uliosanifiwa kutokana na mineralogy na majaribio; kwa mgodi wa dhahabu inaweza kuwa rahisi kama sumaku kwenye mkusanyiko. Anza na mineralogy na jaribio la sumaku kwenye malighafi yako.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Viwango vya nguvu za vitenganishi vya sumaku vinafuata <a href="https://www.911metallurgist.com/blog/fundamentals-high-intensity-magnetic-separation-industrial-minerals/">911 Metallurgist kuhusu utenganishaji wa nguvu kubwa</a> na <a href="https://www.911metallurgist.com/blog/wet-magnetic-separation/">utenganishaji wa sumaku wa majimaji</a> (kwa Kiingereza). Takwimu za mradi wa Handeni zinatoka <a href="https://www.tanzaniainvest.com/mining/licenses-mineral-sands-mining-handeni-metal-refining-kahama">TanzaniaInvest (Machi 2024)</a> (kwa Kiingereza). Vyanzo vilipitiwa tarehe 7 Oktoba 2026. Mfano wa mchanga mweusi unatumia sehemu ya magnetite ya kudhaniwa kuonyesha hesabu.</p>`
export default content
