import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Shimo linapozidi kwenda chini au uzalishaji unapoongezeka, mfumo wa kupandisha madini mara nyingi huwa kikomo cha kiasi cha madini kinachofika juu. Kuchagua winchi kwa nguvu ya kuvuta iliyoandikwa pekee mara nyingi huleta mashine ndogo mno kwa mzigo halisi, ya polepole mno kwa tani za kila siku au isiyo salama juu ya headframe ambayo haikusanifiwa kwa ajili yake. Kupanga mfumo vizuri kunamaanisha kujua mzigo mzito zaidi kwenye kamba ya waya wa chuma, idadi ya safari zinazohitajika kila siku na muundo unaobeba waya juu ya shimo.</p>
<p>Mwongozo huu unakupitisha kwenye hesabu hizo kwa shimo dogo la dhahabu, ukiwa na mfano wa shimo la mita 100. Unaeleza jinsi mzigo, waya, kasi, gurudumu la kupitishia waya (sheave) na mnara wa kupandishia (headframe) vinavyoshirikiana, na taarifa gani msambazaji na mhandisi wa miundo wanahitaji kabla ya kutoa bei au kusanifu. Hauchukui nafasi ya uthibitisho unaohitajika kwa mfumo wa kudumu wa kupandisha.</p>
<h2 id="suspended-load">Anza na mzigo mzito zaidi kwenye waya</h2>
<p>Nguvu ya kuvuta ya winchi hupimwa kwenye tabaka la kwanza la waya kwenye ngoma. Mzigo ambao winchi inapaswa kuubeba ni kila kitu kinachoning’inia chini ya ngoma wakati mzito zaidi wa safari: ndoo, kibble au skip, madini yanayobebwa, viunganishi vyovyote na waya wenyewe kutoka ngomani hadi chini ya shimo. Uzito wa waya husahaulika kwenye shimo fupi lakini ni mkubwa kwenye shimo refu, kwa hiyo chukua uzito kwa kila mita kutoka kwa msambazaji wa waya na uzidishe kwa urefu wote wa kupandisha.</p>
<p>Kisha waya lazima uwe na nguvu ya kutosha pamoja na nafasi ya ziada. Kupandisha mizigo kwa kawaida husanifiwa kwa kipimo cha usalama cha angalau 5:1 dhidi ya nguvu ya chini ya kukatika kwa waya, na kupandisha watu kunahitaji kipimo kikubwa zaidi, kwa kawaida 8:1 au zaidi kwa mujibu wa kanuni husika. <a href="/equipment-swahili/wire-rope-slings-lifting-tackle">Ukurasa wetu wa waya</a> unaeleza muundo wa waya na vigezo vya ISO 4309 vinavyoamua lini waya ubadilishwe.</p>
<h2 id="trips-per-day">Hesabu safari zinazohitajika kwa tani zako</h2>
<p>Uwezo wa kupandisha unategemea kiasi kila safari inabeba na muda wa kila safari. Mzunguko mzima unajumuisha kupandisha, kumwaga juu, kushusha chombo kitupu na kupakia chini. Kasi ya waya huamua muda wa safari, kwa hiyo shimo refu zaidi au winchi ya polepole hupunguza safari zinazopatikana kwenye zamu.</p>
<p>Kama mfano wa dhana, fikiria shimo la mita 100 lenye winchi inayopandisha kwa mita 10 kwa dakika. Kupandisha huchukua dakika 10 na kushusha dakika 10 nyingine, na kupakia na kumwaga huongeza dakika 4 (dhana), kwa hiyo mzunguko mmoja huchukua dakika 24. Kwa saa 20 za kupandisha hiyo ni safari 50. Ikiwa kila safari inabeba kg 600 za madini, shimo linaweza kutoa takribani tani 30 kwa siku. Ikiwa mtambo unahitaji tani 40, chaguo ni chombo kikubwa zaidi, winchi ya kasi zaidi, saa ndefu zaidi za kupandisha au sehemu ya pili ya shimo; kila chaguo hubadilisha mzigo au vifaa, kwa hiyo hesabu upya mzigo unaoning’inia baada ya mabadiliko yoyote.</p>
<h2 id="choosing-winch">Linganisha winchi na mzigo na kina</h2>
<p>Ukishajua mzigo mzito zaidi unaoning’inia na kasi inayohitajika, chagua winchi ambayo kipimo chake kinaacha nafasi ya ziada ngoma ikikaribia kujaa, kwa sababu nguvu ya kuvuta hupungua waya unapojipanga kwa matabaka. Ngoma pia lazima ibebe urefu wote wa waya pamoja na mizunguko ya waya inayopaswa kubaki kwenye ngoma. Kama mwongozo wa jumla kutoka kwenye katalogi yetu, <a href="/equipment-swahili/1-ton-winch">winchi ya tani 1</a> inafaa mashimo hadi takribani mita 60, <a href="/equipment-swahili/2-ton-winch">winchi ya tani 2</a> takribani mita 60–120 na <a href="/equipment-swahili/5-ton-mine-winch">winchi ya tani 5</a> kupandisha kwa uzalishaji wa kudumu kwenye mashimo ya takribani mita 120–300. Winchi ya uzalishaji inapaswa kuwa na breki mbili zinazojitegemea, kinga ya kupanda kupita kikomo (overwind) na kiashiria cha kina.</p>
<h2 id="headframe">Sanifu headframe na sheave kulingana na waya</h2>
<p><a href="/equipment-swahili/mine-hoist-headframe">Headframe</a> hubeba gurudumu la sheave juu ya shimo na kupeleka mizigo ya waya kwenye msingi wake. Headframe ndogo za chuma kwa kawaida zina kimo cha mita 8–18. Kimo lazima kiache nafasi ya chombo kumwaga juu na nafasi ya overwind juu yake, ili chombo kinachopita mahali pa kusimama kishikwe kabla hakijafika kwenye sheave.</p>
<p>Sheave lazima iwe kubwa vya kutosha kwa waya. Kipenyo cha sheave cha angalau mara 60 ya unene wa waya hupunguza uchovu wa kupinda ambao vinginevyo ungefupisha maisha ya waya. Kwa waya wa mm 12 hiyo inamaanisha sheave ya angalau mm 720. Pembe ya waya kutoka ngomani hadi sheave, mpangilio wake na mizigo kwenye muundo vyote vinahitaji kukaguliwa na mhandisi wa miundo, anayesanifu headframe na msingi wake kwa mizigo halisi ya waya, ikiwemo mzigo wa breki za dharura.</p>
<h2 id="certification">Panga ukaguzi na uthibitisho</h2>
<p>Mfumo wa kudumu wa kupandisha unasimamiwa na kanuni za usalama kazini na ukaguzi wa mara kwa mara na mtu mwenye ujuzi, huku kumbukumbu zikihifadhiwa. Masharti hutofautiana kati ya kupandisha mizigo pekee na kupandisha watu. Thibitisha masharti ya sasa ya leseni yako na <a href="https://www.tumemadini.go.tz/">Tume ya Madini</a> na <a href="https://www.osha.go.tz/">OSHA Tanzania</a> kabla ya kuanza kazi, na weka ukaguzi wa kila siku wa waya na breki kwenye utaratibu tangu zamu ya kwanza.</p>
<h2 id="next-steps">Taarifa za kuandaa kwa nukuu ya bei</h2>
<ol>
<li>Kina cha shimo sasa na kina kinachopangwa miaka michache ijayo.</li>
<li>Aina ya chombo na uzito wake kikiwa kitupu, na mzigo wa madini kwa kila safari.</li>
<li>Tani zinazohitajika kwa siku na saa za kupandisha kwa siku.</li>
<li>Kama mfumo utawahi kubeba watu.</li>
<li>Umeme unaopatikana kwenye shimo, na michoro yoyote ya headframe iliyopo.</li>
</ol>
${renderArticleFaqs("ukubwa-wa-winchi-na-headframe", "sw")}
<h2 id="conclusion">Panga mfumo kwa mzigo, safari na muundo</h2>
<p>Mfumo wa kupandisha umepangwa vizuri pale winchi inapobeba mzigo mzito zaidi unaoning’inia ikiwa na nafasi ya ziada ngoma ikiwa imejaa, inakamilisha safari za kutosha kwa tani za kila siku za mtambo na inafanya kazi juu ya sheave na headframe zilizosanifiwa kwa mizigo ya waya na breki zake. Fanya hesabu ya mzigo na safari kwanza, kisha muombe msambazaji na mhandisi wa miundo wathibitishe winchi, waya, sheave na headframe pamoja. Anza kwa kupima chombo chako, mzigo wake na kina cha shimo.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Uwezo wa winchi, vipimo vya usalama wa waya, kimo cha headframe na uwiano wa sheave kwa waya vinalingana na kurasa zetu za <a href="/equipment-swahili/1-ton-winch">winchi ya tani 1</a>, <a href="/equipment-swahili/2-ton-winch">2</a> na <a href="/equipment-swahili/5-ton-mine-winch">5</a>, <a href="/equipment-swahili/mine-hoist-headframe">headframe</a> na <a href="/equipment-swahili/wire-rope-slings-lifting-tackle">waya</a>, zilizopitiwa tarehe 7 Oktoba 2026. Kubadilisha waya kunafuata ISO 4309. Mfano wa mita 100 unatumia kasi, muda na mizigo ya kudhaniwa kuonyesha hesabu na si usanifu wa shimo lolote.</p>`
export default content
