import { CHUNYA_EXAMPLES, HARD_ROCK_EXAMPLES, MONTHLY_OPERATING_EXAMPLES, totalCost, usd } from '@/data/plant-cost-examples'

const [wash, starter, full] = CHUNYA_EXAMPLES
const [gravity, cil] = HARD_ROCK_EXAMPLES
const projectTotal = (p: typeof gravity | typeof cil) => p.equipment + p.delivery + p.civilsUtilities + p.engineeringStartup + p.contingency + p.workingCapital
const operatingRows = MONTHLY_OPERATING_EXAMPLES.map((p, i) => `<tr><th scope="row">${['Kuosha changarawe na sluice', 'Mawe magumu, gravity', 'Mawe magumu, gravity na CIL'][i]}</th><td>${p.throughput.toLocaleString('en-US')} ${p.unit}/mwezi</td><td>${usd(totalCost(p.costs))}</td><td>${usd(totalCost(p.costs) * 2)}</td><td>USD ${(totalCost(p.costs) / p.throughput).toFixed(2)}/${p.unit}</td></tr>`).join('')

const content = `
<p>Ukipanga kuanzisha plant ya dhahabu Tanzania, unahitaji kujua kiasi cha fedha kitakachokufikisha kwenye uzalishaji. Bei ya mashine ni sehemu ya gharama hiyo. Pia utahitaji kufikisha vifaa eneo la mradi, kuandaa misingi, kupata maji na umeme, kufunga mashine, kufanya majaribio ya kuwasha na kuweka fedha za kuendesha wakati uzalishaji unaanza.</p>
<p>Makala hii inalinganisha plant ya kuosha changarawe yenye dhahabu, plant ya mawe magumu yenye mashine za kuponda na ball mill, na plant inayoongeza uchenjuaji wa CIL au CIP. Tunaanza na bei za upande wa mteja kwenye mapendekezo yetu ya Chunya, kisha tunaonyesha mifano tofauti ya kupanga bajeti ya mawe magumu na gharama za mwezi. Lengo ni kukusaidia kutambua plant inayofaa, gharama zinazopaswa kuingia kwenye bajeti na taarifa utakazohitaji ili kupata bei ya mradi wako.</p>

<h2 id="chagua-mfumo">Anza na aina ya malighafi na namna ya kupata dhahabu</h2>
<p>Dhahabu ya alluvial hupatikana kwenye mchanga au changarawe iliyo huru. Ikiwa dhahabu tayari imejitenga na mwamba, kuosha na kuchuja changarawe huiandaa kwa vifaa vinavyotenganisha madini kwa tofauti ya uzito, kama sluice, jig au centrifugal concentrator. Udongo wa mfinyanzi unaweza kubadili uchaguzi huu: washing screen pekee inaweza kushindwa kuuvunja, hivyo rotary scrubber na mfumo mpana zaidi wa kutenganisha dhahabu unaweza kuhitajika. Plant ya aina hii haihitaji ball mill kwa sababu tu inazalisha dhahabu. <a href="https://www.jxscmachine.com/gold-mining-equipment-for-sale/">Mifano ya mifumo ya JXSC</a> inaonyesha tofauti ya kuosha changarawe na kuchakata mawe magumu.</p>
<p>Kwa mawe magumu, dhahabu inaweza kuhitaji kuachiliwa kwa kuponda na kusaga. Mfumo wa kawaida una jaw crusher, ball mill na kifaa cha kutenganisha chembe kwa ukubwa kabla ya gravity recovery. Majaribio huonyesha ulaini unaohitajika na kiasi cha dhahabu kinachopatikana kwa njia hiyo. Ikiwa sehemu muhimu ya dhahabu inabaki na majaribio ya uchenjuaji yanaonyesha njia inayofaa, CIL au CIP inaweza kuongezwa. Dhahabu iliyofungwa ndani ya madini magumu kuchakatwa inaweza kuhitaji matibabu mengine; kununua matanki pekee hakutatui tatizo hilo.</p>
<figure><ol class="process-flow" aria-label="Mfumo wa alluvial"><li>Changarawe</li><li>Kuosha / kuvunja mfinyanzi</li><li>Kuchuja kwa ukubwa</li><li>Kutenganisha kwa uzito</li><li>Kusafisha concentrate</li></ol><figcaption>Mfano wa mtiririko wa alluvial. Maji hurudishwa kupitia mfumo wa kutuliza tope na kuyatumia tena; mpangilio halisi hutegemea mfinyanzi na ukubwa wa dhahabu.</figcaption></figure>
<figure><ol class="process-flow" aria-label="Mfumo wa mawe magumu"><li>Mawe yenye madini</li><li>Kuponda</li><li>Ball mill na kutenganisha chembe</li><li>Gravity recovery</li><li>Uchenjuaji ukithibitishwa na majaribio</li></ol><figcaption>Mfano wa mtiririko wa mawe magumu. Kuponda na kusaga huongeza mashine, matumizi ya umeme na gharama za sehemu zinazochakaa.</figcaption></figure>

<h2 id="bei-za-chunya">Mapendekezo ya Chunya yanaonyesha gharama gani za alluvial?</h2>
<p>Pendekezo letu la tarehe 5 Oktoba 2026 la awamu ya kwanza lina plant ya kuosha na sluice yenye uwezo wa kubuniwa wa 150 m³ kwa saa. Vifaa ni washing screen ya tabaka mbili, sluice sita, mikeka ya kunasa dhahabu, pampu, mabomba, control cabinet na jenereta iliyojumuishwa kwenye mpangilio uliopangiwa bei. Kifurushi cha vifaa ni ${usd(wash.equipment)}. Ukiongeza makadirio ya huduma za utekelezaji, jumla inakuwa takribani <strong>${usd(wash.total)}</strong>, kabla ya VAT ya uagizaji inayolipwa kando, tozo nyingine na mtaji wa kuendesha wa mwenye mradi.</p>
<p>Pendekezo la awali la tarehe 3 Oktoba linalinganisha plant zenye rotary scrubber, centrifugal concentrator na vifaa vya kusafisha concentrate. Hizi ni plant zenye mifumo tofauti ya recovery na makadirio makubwa zaidi ya kazi za eneo na utekelezaji. Bei zake zinaonyesha athari ya wigo wa kazi; si bei tofauti za mashine ileile.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Jedwali la gharama; sogeza upande kuona safu zote"><p class="article-table-caption">Bei za upande wa mteja kwenye mapendekezo ya Chunya, USD zilizokaribishwa. Huduma za utekelezaji bado ni makadirio.</p><table aria-label="Bei za upande wa mteja kwenye mapendekezo ya Chunya, USD zilizokaribishwa. Huduma za utekelezaji bado ni makadirio."><thead><tr><th scope="col">Mpangilio wa plant</th><th scope="col">Uwezo wa kubuniwa</th><th scope="col">Vifaa</th><th scope="col">Huduma za utekelezaji</th><th scope="col">Jumla</th></tr></thead><tbody>
<tr><th scope="row">Washing screen na sluice sita</th><td>150 m³/saa</td><td>${usd(wash.equipment)}</td><td>${usd(wash.execution)}</td><td>${usd(wash.total)}</td></tr>
<tr><th scope="row">Scrubber na gravity recovery, ya kuanzia</th><td>75 m³/saa</td><td>${usd(starter.equipment)}</td><td>${usd(starter.execution)}</td><td>${usd(starter.total)}</td></tr>
<tr><th scope="row">Scrubber na gravity recovery, kubwa</th><td>150 m³/saa</td><td>${usd(full.equipment)}</td><td>${usd(full.execution)}</td><td>${usd(full.total)}</td></tr>
</tbody></table></div>
<p>Kwenye mapendekezo haya, VAT ya uagizaji na tozo za kisheria ni wajibu wa mteja. Dhana iliyotumika kuhusu ushuru wa kuagiza lazima ihakikiwe kwa vifaa na mwagizaji husika. Mteja pia anahitaji kuhakikisha eneo linafikika, kuna chanzo cha maji, vibali vinapatikana na sampuli inayowakilisha malighafi inatolewa. Uchimbaji na kusafirisha changarawe, kununua ardhi au kupata haki za madini, na gharama za uzalishaji wa kawaida zinahitaji bajeti zao. Hizi ni bei za kazi zilizopendekezwa, si gharama zilizopimwa kwenye plant iliyokamilika wala orodha ya bei kwa kila mradi.</p>
<p>Pia linganisha vipimo kwa uangalifu. Alluvial hapa imepimwa kwa mita za ujazo kwa saa, lakini plant za mawe magumu hapa chini zimepimwa kwa tani kwa siku. Kubadili kipimo kunahitaji uzito wa malighafi kwa ujazo, saa za kazi na muda halisi wa uzalishaji. Uwezo sawa wa kulisha plant hauhakikishi mfumo sawa wa recovery.</p>
<figure><img src="/equipment/rotary-scrubber.jpeg" alt="Rotary scrubber kwenye katalogi ya vifaa ya Bart Mining" width="1200" height="800" loading="lazy" /><figcaption>Mfano wa kifaa kutoka kwenye katalogi yetu: rotary scrubber huosha changarawe yenye mfinyanzi kabla ya kutenganisha madini. Hii si picha ya plant iliyofungwa Chunya.</figcaption></figure>

<h2 id="mawe-magumu">Bajeti ya plant yenye crusher na ball mill</h2>
<p>Plant ya gravity kwa mawe magumu inaongeza vifaa vya kuponda, ball mill, kutenganisha chembe kwa ukubwa, recovery, pampu na controls. Kinu kinapaswa kufikisha mawe yako kwenye ulaini unaohitajika kwa kiasi unachopanga kuchakata. Bei ya chini ina manufaa ikiwa mashine inaweza kufanya kazi hiyo kwa matumizi yanayokubalika ya umeme na sehemu zinazochakaa.</p>
<p>Hatuna quotation ya sasa ya plant ya mawe magumu inayotumika kama chanzo cha makala hii. Hivyo mifano miwili inayofuata ni <strong>dhana za kuonyesha namna ya kupanga bajeti</strong>, si bei rasmi za Bart Mining wala viwango vya soko vilivyohakikiwa. Unapaswa kubadilisha kiasi cha kila kipengele kwa bei za mradi wako.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Jedwali la gharama; sogeza upande kuona safu zote"><p class="article-table-caption">Mifano ya bajeti za kuanzisha plant ya mawe magumu, USD. Kila kiasi kwenye jedwali hili ni dhana ya mfano.</p><table aria-label="Mifano ya bajeti za kuanzisha plant ya mawe magumu, USD. Kila kiasi kwenye jedwali hili ni dhana ya mfano."><thead><tr><th scope="col">Kipengele</th><th scope="col">Gravity, tani 30/siku</th><th scope="col">Gravity na CIL, tani 50/siku</th></tr></thead><tbody>
<tr><th scope="row">Vifaa</th><td>${usd(gravity.equipment)}</td><td>${usd(cil.equipment)}</td></tr>
<tr><th scope="row">Usafirishaji, kutoa mzigo na kufikisha eneo</th><td>${usd(gravity.delivery)}</td><td>${usd(cil.delivery)}</td></tr>
<tr><th scope="row">Ujenzi, umeme, maji na hifadhi ya mabaki</th><td>${usd(gravity.civilsUtilities)}</td><td>${usd(cil.civilsUtilities)}</td></tr>
<tr><th scope="row">Majaribio, usanifu, ufungaji na kuanza uzalishaji</th><td>${usd(gravity.engineeringStartup)}</td><td>${usd(cil.engineeringStartup)}</td></tr>
<tr><th scope="row">Akiba ya dharura: 10% ya vipengele vilivyotangulia</th><td>${usd(gravity.contingency)}</td><td>${usd(cil.contingency)}</td></tr>
<tr><th scope="row">Miezi miwili ya gharama za kuchakata za mfano</th><td>${usd(gravity.workingCapital)}</td><td>${usd(cil.workingCapital)}</td></tr>
<tr><th scope="row">Jumla ya mfano ya fedha za kuanza</th><td><strong>${usd(projectTotal(gravity))}</strong></td><td><strong>${usd(projectTotal(cil))}</strong></td></tr>
</tbody></table></div>
<p>Jumla hizi hazijumuishi kodi za kuagiza, ardhi na haki za madini, kufungua mgodi, kununua mitambo ya kuchimba na kusafirisha, gharama za mkopo wala bajeti kamili ya usimamizi wa mwenye mradi. Gharama za maji na hifadhi ya mabaki zinahitaji usanifu wa eneo; eneo lenye changamoto linaweza kuzidi makadirio haya. CIP inaweza kuwa na mpangilio tofauti wa matanki na kaboni, hivyo mfano wa CIL hauwezi kutoa bei ya kila mfumo wa uchenjuaji.</p>
<figure><img src="/equipment/ball-mill-gold-ore.jpg" alt="Ball mill kwenye katalogi ya vifaa vya dhahabu ya Bart Mining" width="1200" height="800" loading="lazy" /><figcaption>Mfano wa kifaa: ball mill husaga mawe yaliyopondwa. Ukubwa wake unahitaji kuhakikiwa kwa ugumu wa mawe, ulaini unaolengwa na saa za kufanya kazi.</figcaption></figure>

<h2 id="gharama-za-mwezi">Fedha zinazohitajika kuendesha plant kila mwezi</h2>
<p>Panga gharama za kuendesha kando na ujenzi. Kwa alluvial, zingatia kulisha plant, dizeli au umeme, pampu, wafanyakazi, kusafisha concentrate na vipuri. Kwa mawe magumu, ongeza mipira ya kusagia na liners. CIL au CIP pia inahitaji kemikali, kaboni, udhibiti wa mchakato na ufuatiliaji wa mazingira. Vipengele hivi vinakuwa makadirio ya mradi baada ya kupata matokeo ya majaribio na bei za eneo lako.</p>
<p>Jedwali hili ni hesabu ya mfano. Kila gharama ya mwezi ni dhana, ikiwemo bei ya dizeli na umeme. Linahusu kazi za kuchakata zilizoelezwa hapa, na halitabiri gharama halisi za kuendesha Chunya.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Jedwali la gharama; sogeza upande kuona safu zote"><p class="article-table-caption">Mifano ya gharama za kuchakata kwa mwezi na akiba ya fedha, USD.</p><table aria-label="Mifano ya gharama za kuchakata kwa mwezi na akiba ya fedha, USD."><thead><tr><th scope="col">Plant</th><th scope="col">Malighafi kwa mwezi</th><th scope="col">Gharama kwa mwezi</th><th scope="col">Akiba ya miezi miwili</th><th scope="col">Gharama kwa kipimo</th></tr></thead><tbody>${operatingRows}</tbody></table></div>
<p><strong>Dhana za alluvial:</strong> plant ya 150 m³/saa imepangiwa saa 20 kwa siku, siku 26 kwa mwezi, na 75% ya muda huo ni uzalishaji halisi, hivyo inalishwa 58,500 m³. Tunatumia wastani wa umeme wa 120 kW kwa saa 520, dizeli lita 0.27 kwa kWh na USD 1.20 kwa lita. Mafuta ya plant ni takribani USD 20,218; kulisha na kupakia ni USD 15,000, wafanyakazi USD 5,000, sehemu zinazochakaa na servicing USD 3,000, na maji, sampuli na usimamizi USD 3,500. Kiasi cha kulisha hakijumuishi kununua mitambo ya uchimbaji. Wastani wa 120 kW ni dhana ya matumizi, tofauti na uwezo wa jenereta wa 200 kW.</p>
<p><strong>Dhana za gravity ya mawe magumu:</strong> tani 30 kwa siku kwa siku 26 za uzalishaji ni tani 780. Kwa kWh 35 kwa tani na USD 0.30 kwa kWh, umeme ni USD 8,190. Wafanyakazi ni USD 4,500, media na vifaa vinavyochakaa USD 3,900, maji na sampuli USD 1,560, na matengenezo USD 2,340. Jumla ni USD 20,490, karibu USD 26.27 kwa tani.</p>
<p><strong>Dhana za CIL:</strong> tani 50 kwa siku kwa siku 26 ni tani 1,300. Umeme wa kWh 40 kwa tani kwa USD 0.30 kwa kWh ni USD 15,600; kemikali na kaboni ni USD 10,400, media na liners USD 6,500, wafanyakazi USD 8,000, maji na maabara USD 2,600, na matengenezo USD 3,900. Jumla ni USD 47,000, karibu USD 36.15 kwa tani. Huu ni mfano wa uzalishaji uliotulia; kuanza polepole kunahitaji akiba zaidi.</p>
<p>Ongeza uchimbaji, kusafirisha mawe, mrabaha, kusafisha dhahabu, gharama za mkopo na kodi pale zinapohusika. USD kwa m³ ya alluvial hailinganishwi moja kwa moja na USD kwa tani ya mawe magumu. Kwa mfano wa mapato, zidisha malighafi halisi kwa kiwango cha dhahabu kilichopimwa na recovery iliyothibitishwa kwa majaribio, kisha tumia bei ya mauzo na makato. Rudia hesabu kwa grade ndogo, recovery ndogo na saa chache za uzalishaji kabla ya kuwekeza.</p>

<h2 id="gharama-za-kufikisha">Hakiki bei ya kufikisha vifaa inajumuisha nini</h2>
<p>Omba masharti ya usafirishaji na wigo wa kazi kwa maandishi. EXW, FOB na CIF zinagawa majukumu tofauti. Kwa CIF, muuzaji analipia usafirishaji na bima hadi bandari iliyotajwa, lakini hatari ya usafiri huhamia kwa mnunuzi vifaa vinapowekwa kwenye meli kwenye bandari ya kuanzia. CIF pekee haijumuishi kutoa mzigo forodha, usafiri wa ndani au ufungaji wa plant. <a href="https://academy.iccwbo.org/incoterms/article/place-of-delivery-risk-transfer-global-trade-contracts/">ICC Academy inaeleza tofauti kati ya gharama za kufikisha na kuhamisha hatari</a>.</p>
<p>Wakala wa forodha ahakiki vifaa kwa kutumia specifications, invoice, nchi ya asili na HS code. Tumia <a href="https://www.eac.int/tariffsearch">utafutaji wa ushuru wa EAC</a> na thibitisha hali husika na TRA. Kuwa na leseni ya madini hakuthibitishi kwamba kila mashine au kipuri hakitozwi ushuru. Makadirio ya kodi yawekwe kando, yakionyesha msingi wa hesabu na anayelipa.</p>
<p>Mfano wa washing na sluice wa Chunya una takribani ${usd(wash.execution)} nje ya bei ya vifaa. Humo kuna logistics, ufungaji, ujenzi, wahandisi, majaribio, commissioning na akiba ya dharura. Hii inaonyesha kwa nini kuongeza asilimia moja ya jumla juu ya bei ya mashine kunaweza kuacha sehemu kubwa ya fedha zinazohitajika kufungua plant.</p>

<h2 id="kabla-ya-kuagiza">Badilisha makadirio kuwa bajeti ya mradi wako</h2>
<p>Anza na sampuli inayowakilisha malighafi na ukaguzi wa eneo. Tambua grade, ukubwa wa dhahabu na recovery, mfinyanzi kwenye changarawe, au ugumu na mahitaji ya kusaga kwenye mawe. Hakiki maji, umbali na mwinuko wa kusukuma maji, barabara, umeme na mpango unaowezekana wa kuhifadhi mabaki. <a href="/insights/plant-test-work-guide" lang="en">Mwongozo wetu wa majaribio</a> unaeleza namna matokeo yanavyoamua plant, kwa Kiingereza.</p>
<p>Kisha omba pendekezo linalotenganisha vifaa, kufikisha, kodi, ujenzi, commissioning na majukumu ya mwenye mradi. Uliza jinsi uwezo na recovery vitakavyothibitishwa kwa malighafi yako, vipuri vilivyojumuishwa na mabadiliko yatakayohitajika malighafi ikitofautiana na sampuli. Linganisha wauzaji kwa kazi na wigo unaofanana.</p>
<p>Panga muda pamoja na fedha. Pendekezo la sasa la washing la Chunya linakadiria wiki 16 hadi uzalishaji; plant za scrubber kwenye pendekezo la awali zinakadiria wiki 24 na 26.5. Hizi ni ratiba za mapendekezo zenye kazi zinazotegemeana, si ahadi ya muda wa kila mradi. Maandalizi ya eneo yanaweza kuendelea wakati vifaa vinatengenezwa na kusafirishwa, lakini maji, barabara na vibali lazima viwe tayari kwa commissioning.</p>

<h2 id="maswali">Maswali wakati wa kupanga bajeti</h2>
<h3>Naweza kuanza na washing na sluice, kisha kuongeza recovery?</h3>
<p>Hiyo ndiyo njia iliyopendekezwa kwa awamu ya kwanza Chunya. Inaweza kufaa ikiwa malighafi ina dhahabu huru inayoweza kupatikana na mfumo unalingana na malighafi hiyo. Majaribio yaonyeshe kinachopotea kwenye sluice, na layout iruhusu kuongeza centrifugal concentrator au vifaa vya kusafisha concentrate. Upanuzi unahitaji bajeti yake; mfumo rahisi hautafaa kila eneo.</p>
<h3>Jumla ya plant inajumuisha excavator na kufungua mgodi?</h3>
<p>Bei za Chunya hapa zinahusu vifaa vya kuchakata na kazi za utekelezaji zilizoelezwa. Hazipangi gharama za biashara nzima ya uchimbaji. Panga uchimbaji, usafirishaji wa malighafi, haki za ardhi na madini, na mtaji wa kuendesha kando.</p>
<h3>Nibadilishe USD kuwa shilingi kwa kiwango gani?</h3>
<p>Kwa mpango wako wa fedha, tumia kiwango cha ubadilishaji na gharama za benki zinazohusika kwenye tarehe za malipo. Hapa tumeacha fedha kwenye sarafu ya pendekezo ili kiwango cha mfano kisichukuliwe kuwa kiwango cha sasa.</p>

<h2 id="hitimisho">Panga fedha za safari kutoka malighafi hadi uzalishaji</h2>
<p>Kwa changarawe ya alluvial, chunguza kuosha na gravity recovery kwanza. Kwa mawe magumu, thibitisha mahitaji ya kuponda na kusaga kabla ya kupanga bei, kisha ongeza uchenjuaji pale majaribio na uchumi vinaporuhusu. Maamuzi hayo yanaeleza gharama vizuri zaidi kuliko jina la mashine pekee.</p>
<p>Mapendekezo ya Chunya yanatoa rejea ya vitendo: takribani ${usd(wash.total)} kwa washing na sluice pamoja na makadirio ya utekelezaji, na bajeti tofauti kwa mifumo yenye scrubber. Uamuzi wako wa kuwekeza bado unahitaji kodi, gharama za mwenye mradi na akiba ya kuendesha. Andaa eneo la mradi, matokeo ya sampuli, uwezo unaolengwa na taarifa za maji na umeme ili vipengele vinavyobaki viweze kupewa bei.</p>

<h2 id="vyanzo">Vyanzo na msingi wa takwimu</h2>
<p>Gharama za kuanzisha alluvial ni jumla zilizokaribishwa za upande wa mteja kutoka mapendekezo ya Bart Mining ya Chunya ya tarehe 3 na 5 Oktoba 2026, zilizohesabiwa kwa mfumo wa proposal wa Plant Planner. Ni bei na makadirio ya kazi zilizopendekezwa, si gharama zilizotumika. Bei za wasambazaji na taarifa za ndani za biashara hazijawekwa kwenye makala hii. Bajeti za mawe magumu na mifano yote ya kuendesha ni dhana zilizoelezwa kwa ajili ya kufundisha hesabu; hazijatolewa kwenye mapendekezo hayo. Viungo vya mtengenezaji, ICC na EAC vinasaidia maelezo ya mchakato na biashara, lakini havithibitishi gharama za mfano.</p>
`
export default content
