const content = `<p>Unapouza dhahabu, thamani iliyoandikwa kabla ya makato inaweza kuwa tofauti na fedha utakazopokea. Hesabu hiyo inategemea uzito, usafi wa dhahabu, bei inayotumika na makato yanayohusu njia ya mauzo. Ili kupanga fedha za mgodi, unahitaji kuelewa kila hatua ya settlement, yaani hesabu ya mwisho ya malipo.</p>
<p>Mwongozo huu unaeleza namna ya kuthibitisha mrabaha na makato, kusoma mfano wa hesabu na kuhifadhi stakabadhi. Hauorodheshi kila kodi ya biashara, wala hautumii viwango vya kihistoria kana kwamba ni uthibitisho wa makato ya kila mauzo ya mwaka 2026.</p>
<h2 id="thamani">Thibitisha thamani inayotumika kwenye hesabu</h2>
<p>Uzito wa jumla si lazima uwe uzito wa dhahabu safi. Omba matokeo ya kipimo cha usafi, utaratibu wa kupima uzito na ufafanuzi kama bei ni kwa gramu ya jumla au gramu ya dhahabu safi. Pia thibitisha namna thamani rasmi ya madini inavyohusiana na bei ya mnunuzi.</p>
<p><a href="https://www.tumemadini.go.tz/pages/mineral-royalties-and-inspection-fees-rates/">Ratiba iliyochapishwa na Tume ya Madini</a> inaeleza msingi wa mrabaha na ada kuwa gross value, yaani thamani ya soko inayopatikana kupitia uthamini. Usidhani thamani hiyo ni sawa moja kwa moja na bei uliyoiona kwenye simu au jumla aliyotaja mnunuzi.</p>
<h2 id="viwango">Soma kiwango pamoja na njia ya mauzo</h2>
<p>Ukurasa huo wa Tume unaonyesha mrabaha wa kawaida wa dhahabu wa 6% na ada ya ukaguzi na uthibitisho ya 1%, huku ukitaja mazingira yenye tofauti. Kwa dhahabu inayouzwa kwenye refinery centres, ukurasa unaonyesha mrabaha wa 4% na kutotumika kwa ada hiyo ya ukaguzi. Kwa sababu sheria na programu maalumu zinaweza kubadilisha matokeo, thibitisha kiwango na msingi wake kwa muamala na mnunuzi husika kabla ya kuuza.</p>
<p>Usitumie kiwango cha 2% kwa sababu mnunuzi amejiita kiwanda cha kusafisha. Ukipendekezewa kiwango tofauti na ratiba rasmi, omba kifungu cha sasa au maelekezo rasmi yanayoruhusu tofauti hiyo. Orodha ya makato yenye marejeo ni bora kuliko maelezo ya mdomo yanayosema kodi zote zimejumuishwa.</p>
<h2 id="bot">Mpango wa Benki Kuu una masharti yake</h2>
<p><a href="https://www.bot.go.tz/Adverts/PressRelease/en/2024100206312713.pdf">Tangazo la BoT la 1 Oktoba 2024</a> lilieleza mrabaha wa 4%, ada ya ukaguzi ya 0%, VAT ya kiwango cha sifuri na malipo ndani ya saa 24 baada ya kuthibitishwa kwa ripoti ya fire assay ya refinery iliyoidhinishwa. Haya ni masharti ya tangazo lenye tarehe; hakiki yanayotumika sasa na njia iliyoidhinishwa kabla ya kuyatumia kwenye makadirio yako.</p>
<p>Muda wa malipo unaohusishwa na uthibitisho wa assay hauanzi moja kwa moja unapokabidhi dhahabu. Uliza lini ripoti itapatikana, nani ataidhinisha na nani atatoa taarifa ya malipo. Gharama za usafiri, ulinzi na masharti mengine ya kukabidhi ziwekwe wazi pia.</p>
<h2 id="mfano">Mfano wa hesabu ya makato</h2>
<p>Tuchukulie, kwa mfano wa kufundisha tu, una gramu 100 zenye usafi wa 90% na bei ya TSh 300,000 kwa gramu ya dhahabu safi. Kiasi cha dhahabu safi ni 100 × 0.90 = gramu 90, na thamani ya kuanzia ni 90 × TSh 300,000 = TSh 27,000,000. Bei na usafi huu ni dhana, si bei ya leo wala valuation rasmi ya lot yako.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Mfano wa makato kwa thamani iliyodhaniwa"><table><thead><tr><th>Kipengele cha mfano</th><th>Hesabu</th><th>Kiasi</th></tr></thead><tbody><tr><td>Thamani kabla ya makato</td><td>90 g × TSh 300,000</td><td>TSh 27,000,000</td></tr><tr><td>Makato ya 6%, ikiwa yanatumika</td><td>27,000,000 × 0.06</td><td>TSh 1,620,000</td></tr><tr><td>Makato mengine ya 1%, ikiwa yanatumika</td><td>27,000,000 × 0.01</td><td>TSh 270,000</td></tr><tr><td>Salio baada ya makato hayo mawili tu</td><td>27,000,000 − 1,620,000 − 270,000</td><td>TSh 25,110,000</td></tr></tbody></table></div>
<p>Jedwali linaonyesha namna ya kufanya hesabu, si orodha kamili ya makato ya mauzo yako. Kila tozo ya ziada, gharama ya mnunuzi au kodi inayohusika iwe na jina, msingi, kiwango na stakabadhi. Usihesabu salio hili kama faida: gharama za uchimbaji na uchakataji bado zinahitaji kuondolewa.</p>
<h2 id="asilimia-20">Sharti la 20% si aina ya makato</h2>
<p><a href="https://www.bot.go.tz/Publications/Other/The%2050th%20Anniversary%20of%20Bank%20of%20Tanzania/sw/2026061710500724.pdf">Chapisho la BoT la mwaka 2026</a> linaeleza kutenga 20% ya dhahabu ya mauzo ya nje kwa ununuzi wa Benki Kuu, kwa wamiliki wa haki za madini na dealers wenye leseni chini ya kifungu cha 59. Usilitafsiri kama kodi ya 20%, au kudhani kuuza kwa mnunuzi yeyote wa ndani kunakamilisha wajibu huo.</p>
<p>Ikiwa wewe au mnunuzi wako anasafirisha dhahabu nje, pata maelekezo ya Tume na BoT kuhusu nyaraka na utaratibu unaohusika. Kwa taarifa za njia za kuuza, soma <a href="/insights/selling-gold-tanzania">mwongozo wa mauzo kwa Kiingereza</a>.</p>
<h2 id="conclusion">Panga fedha kwa malipo yanayoeleweka</h2>
<p>Kabla ya kuuza, thibitisha uzito, usafi, valuation, makato na muda wa malipo kwa maandishi. Hifadhi assay, hesabu ya settlement, stakabadhi na kumbukumbu ya benki pamoja. Kiasi unachoweza kuthibitisha baada ya makato ndicho kinachofaa kwenye mpango wa fedha; ushahidi wa gharama za biashara utakusaidia kufikia hesabu ya faida baadaye.</p>
<h2 id="basis">Vyanzo na msingi wa mfano</h2>
<p>Vyanzo rasmi vya Tume na BoT vilikaguliwa tarehe 5 Oktoba 2026. Mfano unatumia dhana za bei na usafi; masharti ya tangazo la 2024 yamewekewa tarehe. Thibitisha pia kodi na tozo nyingine zinazohusu biashara yako kwa mamlaka husika.</p>`
export default content
