import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Maji ni moja ya sababu kuu zinazosimamisha migodi midogo ya dhahabu ya chini ya ardhi, hasa wakati wa mvua. Shimo linalojaa maji usiku mmoja hupoteza zamu, huharibu vifaa na linaweza kufunika madini yaliyochukua miezi kuandaliwa. Kulikausha kunategemea kujua kiasi cha maji kinachoingia, kuyapandisha urefu wote hadi juu na kuhakikisha pampu zinaendelea kufanya kazi umeme au mashine moja ikishindwa. Kuanzia kina fulani, njia ya kuaminika ni kusukuma kwa hatua badala ya kupandisha mara moja kwa urefu wote.</p>
<p>Mwongozo huu unaeleza jinsi ya kukadiria maji yanayoingia, kuhesabu kimo cha jumla cha kusukuma maji (total head) ambacho pampu inapaswa kushinda na kuamua lini kupanga pampu kwa hatua zenye mashimo ya kukusanyia maji (sump) ya kati. Mfano wa shimo la mita 150 unaonyesha hesabu. Baada ya kusoma utaweza kumpa msambazaji wa pampu taarifa na kupanga umeme na akiba zinazohitajika.</p>
<h2 id="inflow">Pima kiasi cha maji kinachoingia</h2>
<p>Mwanzo ni kiwango cha maji yanayoingia. Njia rahisi zaidi ni kusimamisha pampu kwa muda uliopimwa na kuandika jinsi maji yanavyopanda kwenye sump yenye ukubwa unaojulikana. Ikiwa sump ya mita 2 kwa 2 inapanda mita 0.5 kwa saa moja, maji yanayoingia ni takribani mita za ujazo 2 kwa saa. Rudia kipimo wakati wa kiangazi na wa mvua, kwa sababu maji yanaweza kuongezeka sana baada ya mvua kubwa, na panga kwa kiwango cha juu cha msimu wa mvua pamoja na nafasi ya ziada.</p>
<p>Weka daftari rahisi la saa za kusukuma na kina cha maji kwenye sump. Linaonyesha kama maji yanaongezeka shimo linapozidi kwenda chini na humpa msambazaji takwimu halisi badala ya kubahatisha.</p>
<h2 id="total-head">Hesabu total head, si kina pekee</h2>
<p>Pampu lazima ipandishe maji urefu wa wima kutoka sump hadi mahali yanapotolewa na pia ishinde msuguano ndani ya bomba au hose. Msuguano mara nyingi hukadiriwa chini kuliko ulivyo: hose ndefu nyembamba inaweza kuongeza upinzani zaidi ya kina cha shimo chenyewe. Msambazaji huuhesabu kutokana na kiasi cha maji, ukubwa wa bomba, urefu na viungio, kwa hiyo mpe njia nzima ya bomba. Chagua pampu kwa total head, yaani urefu wa wima pamoja na msuguano, kwa kiasi cha maji kinachohitajika.</p>
<p><a href="/equipment-swahili/submersible-dewatering-pump">Pampu ya kuzamishwa ya kutoa maji</a> hukaa ndani ya maji inayoyasukuma, jambo linaloepusha matatizo ya kujaza pampu na bomba maji kabla ya kuanza (priming) na ya kunyonya yanayosimamisha pampu za juu kwenye shimo linalojaa maji. Pampu za migodini za aina hii hufunika takribani mita za ujazo 5–500 kwa saa dhidi ya head ya mita 10–120 kwa kila hatua, kulingana na modeli.</p>
<h2 id="staging">Amua lini kupanga pampu kwa hatua</h2>
<p>Zaidi ya takribani mita 80, kusukuma kwa mfululizo pamoja na sump za kati kwa kawaida huaminika zaidi kuliko kupandisha mara moja. Pampu ya chini hupandisha maji hadi sump iliyo katikati ya shimo, na pampu ya pili huyapandisha kutoka hapo hadi juu. Kila pampu hufanya kazi dhidi ya head ndogo, pampu ndogo na rahisi kubeba zinaweza kutumika, na hitilafu hufurika hatua moja badala ya shimo zima.</p>
<p>Kupanga kwa hatua kunahitaji nafasi ya kila sump ya kati, umeme na nyaya kwa kila pampu, na njia ya waendeshaji kuona kuwa hatua zote mbili zinafanya kazi. Sump zinapaswa kuhifadhi maji ya kutosha kuwapa wafanyakazi muda wa kuchukua hatua pampu ikisimama.</p>
<h2 id="worked-example">Mfano wa hesabu kwa shimo la mita 150</h2>
<p>Tuseme shimo lina kina cha mita 150 na maji yanayoingia msimu wa mvua yamepimwa kuwa takribani mita za ujazo 10 kwa saa. Kuzidisha mara mbili kwa nafasi ya usanifu kunatoa kiasi cha usanifu cha mita za ujazo 20 kwa saa. Tuseme msambazaji anakadiria msuguano wa bomba wa mita 15 kwa kupandisha mara moja, hivyo total head ni mita 165. Hiyo inazidi mita 120 ambazo hatua moja ya pampu ya kuzamishwa ya mgodini kwa kawaida inamudu, kwa hiyo usanifu unatumia hatua mbili zenye sump ya kati karibu mita 75.</p>
<p>Kila hatua kisha hupandisha takribani mita 75, pamoja na msuguano wa kudhaniwa wa mita 8, hivyo total head ya takribani mita 83. Nguvu inayohitajika kusukuma maji kwa hatua moja ni kiasi cha maji ukizidisha kwa head na kwa mvuto: mita za ujazo 20 kwa saa ni takribani mita za ujazo 0.0056 kwa sekunde, na kg/m³ 1,000 × m/s² 9.81 × m³/s 0.0056 × m 83 ni takribani kW 4.5. Kwa ufanisi wa jumla wa pampu wa 50% (dhana), kila mota ingehitaji takribani kW 9. Takwimu hizi zinaonyesha njia; mchoro wa utendaji wa pampu (pump curve) wa msambazaji na hesabu yake ya msuguano ndizo zinazoamua uchaguzi halisi.</p>
<h2 id="power-standby">Panga umeme, akiba na matengenezo</h2>
<p>Kutoa maji ni kazi muhimu isiyopaswa kusimama. Pampu zikisimama wakati wa mvua, shimo linaweza kujaa ndani ya saa chache, kwa hiyo panga akiba. Hiyo inaweza kuwa pampu ya ziada kwa kila hatua, jenereta yenye ukubwa wa kuwasha pampu tena umeme wa gridi ukikatika, au vyote viwili. <a href="/insights/off-grid-mine-power">Mwongozo wetu wa umeme nje ya gridi</a> (kwa Kiingereza) unaeleza jinsi ya kujumuisha mizigo muhimu na kuwasha mota kwenye tathmini ya jenereta.</p>
<p>Mchanga na tope hufupisha maisha ya pampu haraka. Sehemu za ndani za high-chrome na chujio linalosafishwa kila zamu husaidia, na mafuta ya chumba cha seal yanapaswa kukaguliwa kila mwezi; mafuta yenye rangi ya maziwa yanamaanisha maji yamepita seal ya nje na pampu inahitaji huduma kabla mota haijaharibika. Fanya huduma kamili na jaribio la umeme kabla ya kila msimu wa mvua. Kwa maji yenye tope jingi, <a href="/equipment-swahili/slurry-pump">slurry pump</a> inaweza kuwa chaguo bora kwa sehemu ya kazi.</p>
<h2 id="next-steps">Taarifa za kuandaa kwa nukuu ya pampu</h2>
<ol>
<li>Maji yanayoingia yaliyopimwa msimu wa kiangazi na wa mvua, na jinsi yalivyopimwa.</li>
<li>Kina cha shimo sasa na kinachopangwa, pamoja na mahali panapowezekana kwa sump ya kati.</li>
<li>Njia ya bomba au hose, kipenyo na urefu kutoka kila sump hadi mahali pa kutolea maji.</li>
<li>Kiasi cha mchanga au tope kilichomo kwenye maji.</li>
<li>Umeme uliopo kwa kila hatua na mpango wa akiba ulio nao sasa.</li>
</ol>
${renderArticleFaqs("kutoa-maji-shimoni", "sw")}
<h2 id="conclusion">Panga kutoa maji kwa kiwango cha juu cha msimu wa mvua</h2>
<p>Mfumo wa kuaminika wa kutoa maji huanza na maji yanayoingia yaliyopimwa, huchaguliwa kwa total head badala ya kina, na hutumia pampu za hatua pale kupandisha mara moja kunapokuwa juu mno. Unajumuisha pampu na umeme wa akiba kwa msimu unaohitajika zaidi. Anza kwa kupima maji yanayoingia kwenye sump yako na kuandika njia ya bomba, kisha muombe msambazaji achague pampu kwa kila hatua kwa takwimu hizo.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Viwango vya kiasi cha maji na head, mwongozo wa kupanga hatua zaidi ya mita 80 na hoja za matengenezo vinalingana na <a href="/equipment-swahili/submersible-dewatering-pump">ukurasa wetu wa pampu ya kuzamishwa</a>, uliopitiwa tarehe 7 Oktoba 2026. Kanuni ya nguvu ya maji ni ya kawaida ya hydraulics; <a href="https://www.engineeringtoolbox.com/pumps-power-d_505.html">rejea ya Engineering ToolBox kuhusu nguvu ya pampu</a> (kwa Kiingereza) inaonyesha hesabu hiyo hiyo. Mfano wa mita 150 unatumia maji yanayoingia, msuguano na ufanisi wa kudhaniwa kuonyesha njia na si usanifu wa shimo lolote.</p>`
export default content
