import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Mtambo wa dhahabu hutumia maji mengi kuliko wamiliki wengi wanavyotarajia, na kwenye wilaya nyingi Tanzania maji ndiyo kikomo cha muda mtambo unaoweza kufanya kazi wakati wa kiangazi. Kurejesha maji ya mchakato huruhusu mtambo kuendelea kufanya kazi kwa maji mapya kidogo kutoka kwenye chanzo, hupunguza kinachotoka eneo la mgodi na hulinda watumiaji wengine wa maji jirani. Kufanya hivyo vizuri kunamaanisha kujua kiasi cha maji kila sehemu ya mtambo inatumia, kutuliza yabisi au kuondoa maji kwenye tope ili maji yarudi, na kutenganisha maji ya mchakato na maji safi na ya mvua.</p>
<p>Mwongozo huu unaeleza jinsi ya kuandaa hesabu rahisi ya maji, kuchagua kati ya mabwawa ya kutuliza na tanki la kukoleza tope (thickener), na kupanga kwa msimu wa mvua. Mfano wa hesabu kwa mtambo wa kuosha alluvial unaonyesha jinsi kurejesha maji kunavyobadilisha mahitaji ya maji safi. Haujumuishi kutibu maji yenye sianidi kwa kemikali, ambayo inahitaji usanifu wa mtaalamu.</p>
<h2 id="water-balance">Anza na hesabu ya maji</h2>
<p>Hesabu ya maji huorodhesha maji yanapoingia kwenye mtambo, yanapotumika na yanapotoka. Matumizi makuu ni kuosha na kuchuja, kusaga, urejeshaji wa gravity na, kwa mitambo ya mawe magumu, leaching. Maji hutoka pamoja na mabaki, kwenye mkusanyiko na marundo yenye unyevu, kwa kuvukiza kutoka kwenye mabwawa na kupitia utoaji wowote. Tofauti kati ya maji mtambo unayotumia na yale unayoweza kurejesha ni maji ya kujaza ambayo chanzo lazima kitoe.</p>
<p>Vifaa vya kuosha huamua ukubwa wa mahitaji kwenye maeneo ya alluvial. <a href="/equipment-swahili/trommel-screen">Trommel</a> kwa kawaida hutumia mita za ujazo 1–3 za maji kwa kila mita ya ujazo ya malighafi, na <a href="/equipment-swahili/rotary-scrubber">rotary scrubber</a> kwenye udongo mzito wa mfinyanzi mita za ujazo 2–5. Pima mtiririko halisi kwa flow meter au ndoo na saa inapowezekana; makadirio kutoka viwango vya vifaa ni mwanzo, si hesabu kamili.</p>
<h2 id="settling">Tuliza yabisi ili maji yarudi</h2>
<p>Maji yanaweza kutumika tena pale tu yabisi nyingi zimetulia. Kwenye mitambo midogo hili kwa kawaida hufanyika kwenye mfululizo wa mabwawa ya kutuliza: bwawa la kwanza hukamata mchanga mzito, na mabwawa yanayofuata huzipa chembe laini muda wa kutulia kabla maji yaliyotulia hayajasukumwa kurudi. Malighafi yenye udongo mwingi wa mfinyanzi hutulia polepole, kwa hiyo mabwawa ya malighafi yenye udongo wa mfinyanzi yanahitaji eneo au muda zaidi, na flocculant inaweza kufaa kujaribiwa na msambazaji.</p>
<p>Thickener hufanya kazi hiyo hiyo ndani ya tanki. Tope huingia katikati, yabisi hutulia chini na kusukumwa nje kama tope zito, na maji yaliyoondolewa yabisi humwagika juu ya ukingo kwa kutumika tena. Inahitaji ardhi kidogo kuliko mabwawa na hurudisha maji haraka, lakini inagharimu zaidi na inahitaji umeme na uangalizi wa mwendeshaji. Mitambo ya mawe magumu yenye usagaji na leaching mara nyingi hutumia thickener; mitambo ya kuosha alluvial kwa kawaida huanza na mabwawa. Pale maji ni haba sana, <a href="/equipment-swahili/filter-press">filter press</a> inaweza kurejesha maji zaidi kutoka kwenye mabaki.</p>
<h2 id="worked-example">Mfano wa hesabu kwa mtambo wa kuosha</h2>
<p>Tuseme mtambo wa kuosha alluvial unachakata mita za ujazo 50 za malighafi kwa saa na unatumia mita za ujazo 2 za maji kwa kila mita ya ujazo ya malighafi, hivyo unazungusha mita za ujazo 100 za maji kwa saa. Bila kurejesha, siku ya saa 10 ingehitaji mita za ujazo 1,000 za maji mapya kutoka kwenye chanzo. Ikiwa mabwawa ya kutuliza yanarudisha 80% ya maji hayo (dhana), mtambo unahitaji takribani mita za ujazo 20 tu za kujaza kwa saa, au mita za ujazo 200 kwa siku, kuchukua nafasi ya maji yanayopotea kwenye mabaki, kuvukiza na kupenya ardhini.</p>
<p>Mabwawa lazima yawe makubwa vya kutosha ili maji yatulie kabla ya kurudi. Ikiwa maji yanahitaji saa 4 kutulia (dhana) kwa mita za ujazo 100 kwa saa, mabwawa yanahitaji angalau mita za ujazo 400 za ujazo wa kazi, pamoja na nafasi ya yabisi zinazojikusanya na nafasi ya ziada kwa mvua. Badilisha dhana hizi kwa mtiririko uliopima na jaribio la kutuliza kwenye malighafi yako.</p>
<h2 id="rain-and-separation">Panga kwa mvua na tenganisha maji</h2>
<p>Mabwawa yanayofanya kazi wakati wa kiangazi yanaweza kufurika wakati wa mvua. Elekeza maji safi ya mvua pembeni ya mtambo na mabwawa kwa mifereji, acha nafasi ya ziada kwenye kila bwawa na panga maji ya ziada yangeenda wapi kwenye dhoruba kubwa. <a href="/insights/recovering-gold-rainy-season">Mwongozo wetu wa msimu wa mvua</a> (kwa Kiingereza) unaeleza mifereji na kufunika marundo.</p>
<p>Tenganisha maji ya mchakato na maji ya kunywa na mito. Kwenye mitambo inayotumia sianidi, maji ya mchakato lazima yabaki ndani ya mfumo uliosanifiwa na kituo chake cha mabaki kilichotibiwa, na utoaji wowote unahitaji tiba na idhini zilizowekwa kwenye kibali cha mazingira. Mtaalamu asanifu sehemu hiyo ya mfumo.</p>
<h2 id="next-steps">Taarifa za kuandaa</h2>
<ol>
<li>Matumizi ya maji yaliyopimwa au kukadiriwa kwa kila hatua ya mtambo na saa za kazi kwa siku.</li>
<li>Chanzo chako cha maji mapya, kiasi kinachoweza kutoa wakati wa kiangazi na watumiaji wengine wanaokitegemea.</li>
<li>Ardhi inayopatikana kwa mabwawa, aina ya udongo na njia za maji ya mvua eneo hilo.</li>
<li>Sampuli ya mabaki kwa jaribio la kutuliza, hasa ikiwa malighafi ina udongo mwingi wa mfinyanzi.</li>
</ol>
${renderArticleFaqs("kurejesha-maji-kwenye-mtambo", "sw")}
<h2 id="conclusion">Panga mtambo kulingana na maji unayoweza kurejesha</h2>
<p>Mahitaji ya maji mapya ya mtambo yanategemea kiasi cha maji ya mchakato unaorejesha. Andaa hesabu ya maji, tuliza yabisi au ondoa maji kwenye tope ili maji yarudi, panga ukubwa wa mabwawa kwa kutuliza na kwa mvua, na tenganisha maji ya mchakato na maji safi. Anza kwa kupima maji kila hatua inatumia na kupima jinsi mabaki yako yanavyotulia haraka, kisha panga mabwawa au thickener kutokana na takwimu hizo.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Viwango vya matumizi ya maji kwa trommel na scrubber vinalingana na kurasa zetu za vifaa, zilizopitiwa tarehe 7 Oktoba 2026. <a href="https://www.epa.gov/international-cooperation/artisanal-and-small-scale-gold-mining-without-mercury">Muhtasari wa US EPA kuhusu uchimbaji mdogo wa dhahabu</a> (kwa Kiingereza) unatoa muktadha mpana wa uchakataji na mabaki. Mfano wa mtambo wa kuosha unatumia kiwango cha kurejesha na muda wa kutuliza wa kudhaniwa kuonyesha hesabu na si usanifu wa eneo lolote.</p>`
export default content
