import { renderArticleFaqs } from '@/lib/article-faqs'

// NOTE FOR REVIEW: native Kiswahili review pending.
const content = `
<p>Migodi mingi midogo ya mawe magumu Tanzania husaga madini kwa wet pan mill, na wengi baadaye hujiuliza kama ball mill ingepata dhahabu zaidi. Jibu linategemea mambo matatu: ukubwa wa chembe unaoachilia dhahabu, unahitaji kuchakata tani ngapi kwa siku, na eneo lako lina umeme na karakana za aina gani. Wet pan mill ni nafuu, rahisi na hurekebishwa kwa urahisi. Ball mill husaga kwa ulaini zaidi na kwa uthabiti kwenye tani nyingi, lakini inagharimu zaidi kununua, kuendesha na kuipa umeme.</p>
<p>Mwongozo huu unaeleza vinu hivi, hali vinapofaa na jinsi ya kuvilinganisha kwa madini yako. Mfano wa hesabu unaonyesha uamuzi kwa mgodi wa tani 20 kwa siku. Utaweza kutambua matokeo ya majaribio na taarifa za eneo zinazosaidia kuamua.</p>
<h2 id="how-they-work">Jinsi vinu viwili vinavyosaga</h2>
<p><a href="/equipment-swahili/wet-pan-mill">Wet pan mill (kinu cha magurudumu)</a>, ambayo wengine huiita Chilean mill, husaga mawe yaliyopondwa chini ya magurudumu mazito ya chuma yanayozunguka ndani ya sinia la duara pamoja na maji. Mashine za magurudumu mawili za mm 1,100 na mm 1,200 ndizo zinazotumika zaidi kwenye maeneo madogo Tanzania. Kwa kawaida huchakata tani 0.5–3 kwa saa na hutoa chembe za takribani mm 0.1–0.6, zikitoka kama tope linaloweza kwenda moja kwa moja kwenye <a href="/equipment-swahili/shaking-table-gold">shaking table</a> au concentrator.</p>
<p><a href="/equipment-swahili/ball-mill-gold-ore">Ball mill (kinu cha mipira)</a> ni silinda ya chuma inayozunguka ikiwa na mipira ya chuma ndani. Silinda inapozunguka, mipira inayojipindua ndani huvunja mawe kwa kugonga na kusaga. Kwenye mitambo ya dhahabu, ball mill kwa kawaida hupangwa kutoa 80% ya bidhaa ikiwa laini kuliko takribani maikroni 75–150, ambayo ni laini zaidi ya kile pan mill hufikia kwa kawaida. Hufanya kazi mfululizo, mara nyingi pamoja na classifier au hydrocyclone inayorudisha chembe kubwa zisagwe tena.</p>
<h2 id="what-decides">Kinachoamua chaguo</h2>
<p><strong>Ukubwa wa kuachilia dhahabu unaamua kwanza.</strong> Dhahabu inaweza kupatikana pale tu usagaji umeiachilia kutoka kwenye mwamba unaoizunguka. Ikiwa dhahabu yako nyingi huachiliwa kwenye ukubwa mkubwa, pan mill inaweza kufanya kazi hiyo. Ikiwa majaribio yanaonyesha dhahabu imefungwa kwenye chembe ndogo na huachiliwa chini ya takribani mm 0.1, pan mill iliyo mwisho wa uwezo wake itaacha dhahabu kwenye mabaki ambayo ball mill ingeiachilia. Jaribio la usagaji na urejeshaji kwenye sampuli wakilishi hujibu swali hili; <a href="/insights/plant-test-work-guide">mwongozo wetu wa majaribio</a> (kwa Kiingereza) unaeleza jinsi ya kuliagiza.</p>
<p><strong>Kiasi cha madini kwa siku kinafuata.</strong> Kila pan mill huchakata kiasi kidogo cha madini, kwa hiyo mgodi unaokua huongeza vinu, waendeshaji na sehemu za matengenezo. Zaidi ya takribani tani 10–15 kwa siku, ball mill moja yenye mfumo wake mara nyingi huwa rahisi kuendesha kuliko mstari wa pan mill, kwa sababu umeme na nguvu kazi huanza kupendelea mstari mmoja wa usagaji.</p>
<p><strong>Umeme, msaada wa ufundi na bajeti hukamilisha picha.</strong> Pan mill huendeshwa na injini ndogo ya dizeli au mota ndogo ya umeme na inaweza kurekebishwa kwenye karakana za Mwanza au Geita. Ball mill inahitaji mota kubwa zaidi, soft starter au variable-speed drive ikiendeshwa na jenereta, mpango wa kuinua liners, na bajeti ya mipira ya kusagia, ambayo kwa kawaida hutumia kilo 0.3–1.2 za chuma kwa kila tani ya madini.</p>
<h2 id="worked-example">Mfano wa hesabu kwa tani 20 kwa siku</h2>
<p>Tuseme mgodi unahitaji kuchakata tani 20 za mawe yaliyopondwa kwa siku na vinu vinafanya kazi saa 20 kwa siku. Kazi ya usagaji kwa hiyo ni tani 1 kwa saa.</p>
<ul>
<li>Ikiwa majaribio yanaonyesha dhahabu huachiliwa kwenye takribani mm 0.3 na pan mill moja huchakata tani 0.5 kwa saa kwa madini haya (dhana), pan mill mbili zingetosha, na ya tatu ingefaa kufikiriwa kama akiba wakati moja inabadilishiwa vipuri.</li>
<li>Ikiwa majaribio hayo yanaonyesha urejeshaji unafikia kiwango kinachokubalika pale tu madini yanaposagwa hadi takribani mm 0.1, pan mill zingekuwa zinafanya kazi kwenye kikomo cha uwezo wao. Ball mill ndogo iliyopangwa kwa jaribio la usagikaji ingekuwa chaguo la kuaminika zaidi.</li>
</ul>
<p>Ili kulinganisha, weka chaguo zote mbili kwenye msingi mmoja: gharama ya vifaa na ufungaji, umeme kila kimoja kinatumia kwa mwezi, nguvu kazi, vipuri na mipira, na dhahabu ya ziada inayopatikana kwa usagaji laini kwa mujibu wa majaribio. Ball mill inayopata dhahabu zaidi inaweza kufidia gharama yake kubwa; iliyofungwa kwa madini ambayo pan mill tayari inayaachilia huongeza gharama bila kuongeza dhahabu. Takwimu za mfano huu ni dhana za kuonyesha hesabu, si uwezo uliopimwa wa mashine yoyote.</p>
<h2 id="staged-approach">Kuanza na pan mill na baadaye kwenda ball mill</h2>
<p>Migodi mingi huanza na pan mill wakati inathibitisha madini na kujenga mapato, kisha huongeza ball mill pale tani na matokeo ya majaribio yanapohalalisha. Hii inaweza kufanya kazi vizuri, ikiwa mpangilio wa eneo unaacha nafasi ya kinu kikubwa, classifier yake na umeme wake. Weka kumbukumbu za ulaini wa usagaji na dhahabu inayopatikana kutoka kwenye pan mill tangu mwanzo, kwa sababu zitasaidia kupanga ball mill baadaye.</p>
<p>Kinu chochote utakachotumia, kiunganishe na urejeshaji wa gravity badala ya zebaki. Kuweka zebaki kwenye pan mill hupoteza zebaki na dhahabu kwenye mabaki na huhatarisha waendeshaji. Centrifugal concentrator ikifuatiwa na shaking table hupata dhahabu huru bila zebaki; angalia <a href="/insights/mercury-free-gold-recovery">mwongozo wa urejeshaji bila zebaki</a> (kwa Kiingereza).</p>
<h2 id="next-steps">Taarifa za kuandaa</h2>
<ol>
<li>Kusanya sampuli wakilishi ya madini utakayochakata miezi ijayo, si kipande teule chenye dhahabu nyingi.</li>
<li>Omba maabara ifanye jaribio la usagaji na urejeshaji kwenye ulaini tofauti, na jaribio la usagikaji ikiwa ball mill inawezekana.</li>
<li>Andika tani unazolenga kwa siku, saa za kazi na ukubwa wa mawe yanayotoka kwenye crusher yako.</li>
<li>Andika chanzo chako cha umeme na uwezo wake, na kama kuna karakana karibu inayoweza kuhudumia kila kinu.</li>
</ol>
${renderArticleFaqs("kinu-cha-dhahabu-pan-mill-au-ball-mill", "sw")}
<h2 id="conclusion">Chagua kinu kinachohitajika na madini na tani zako</h2>
<p>Wet pan mill inafaa tani chache, dhahabu inayoachiliwa kwa ukubwa mkubwa na maeneo yanayohitaji vifaa rahisi vinavyoweza kurekebishwa ndani ya nchi. Ball mill inafaa dhahabu inayohitaji usagaji laini zaidi, tani nyingi na migodi inayoweza kuhudumia umeme, mipira na matengenezo yake. Matokeo ya majaribio yanaamua swali la ulaini, na tani zako kwa siku zinaamua swali la uwezo. Anza na sampuli wakilishi na jaribio la usagaji na urejeshaji kabla ya kuamua kinu chochote.</p>
<h2 id="basis">Vyanzo na dhana</h2>
<p>Uwezo, viwango vya ulaini na matumizi ya mipira vinalingana na kurasa zetu za vifaa za <a href="/equipment-swahili/wet-pan-mill">wet pan mill</a> na <a href="/equipment-swahili/ball-mill-gold-ore">ball mill</a>, zilizopitiwa tarehe 7 Oktoba 2026. <a href="https://www.sgs.com/-/media/sgscorp/documents/corporate/brochures/sgs-canada-inc-minerals-comminution.cdn.en-CA.pdf">Rejea ya SGS kuhusu usagaji</a> (kwa Kiingereza) inaeleza majaribio ya usagikaji yanayotumika kupanga ball mill. Mfano wa tani 20 unatumia uwezo wa kudhaniwa kuonyesha hesabu na si ahadi ya utendaji wa mashine yoyote.</p>`
export default content
