const content = `<p>A gold leach plant needs reagents and carbon that match its process, arrive through an appropriate supply chain and can be handled reliably on site. A low price per bag is a poor comparison if the specification is unclear or the delivery leaves the plant without a critical input.</p>
<p>This guide explains how to prepare a procurement brief for activated carbon, cyanide and supporting consumables in Tanzania. The goal is a specification and stock plan tied to test results and production, rather than a generic consumption rate or an unverified list of suppliers.</p>
<h2 id="carbon">Specify carbon for the actual circuit</h2>
<p>Activated carbon collects dissolved gold in suitable adsorption circuits. Particle size, activity and resistance to abrasion affect how it performs and how it is retained by screens. <a href="https://activatedcarbon.com/applications/metal-recovery">Carbon Activated Corporation’s metal-recovery guidance</a> provides a manufacturer reference for these characteristics.</p>
<p>Ask for the product specification, test methods, batch certificate and trial acceptance criteria. Match the size distribution to the engineering of carbon retention and transfer. A general-purpose carbon described as “high quality” is not a complete gold-circuit specification.</p>
<h2 id="cyanide">Procure cyanide within the designed management system</h2>
<p>Confirm the form and specification required by the process engineer, the authorised procurement and transport route, documentation and site receiving arrangements. Storage, handling, training, exposure controls and emergency planning need to be established before the first delivery.</p>
<p>The <a href="https://cyanidecode.org/about-the-cyanide-code/the-cyanide-code/">Cyanide Code</a> is a reference for responsible cyanide management across supply and use. It does not establish Tanzanian permit eligibility or replace specialist site procedures. This guide deliberately gives no dosing recipe or universal chemical-control setting.</p>
<h2 id="consumption">Build consumption from test and plant evidence</h2>
<p>Use representative test work for the first operating model, then reconcile consumption with actual dry feed and stock movements. Distinguish an initial circuit inventory from ongoing makeup. Carbon charged into a new circuit is not the same expense pattern as carbon replacing routine losses.</p>
<p>For an illustrative stock calculation, assume 1,000 dry t/month and a tested planning allowance of 0.5 kg of a consumable per tonne. Monthly demand is 500 kg. If confirmed lead time is six weeks and an assumed two-week buffer is retained, an eight-week cover at roughly 125 kg/week is about 1,000 kg. These are teaching assumptions, not cyanide dosage, carbon consumption or a safe storage quantity.</p>
<h2 id="stock-plan">Balance continuity with storage constraints</h2>
<p>Validate the production schedule and supplier lead time, including border clearance where relevant. Choose reorder levels within the approved storage capacity and product conditions. Buying a year’s supply to avoid a delay can create handling, security and stock-quality problems.</p>
<p>Keep a stock register linking received batches, certificates, issues, balances and discrepancies. Investigate abnormal use through the process and inventory records instead of increasing orders automatically. The same review should examine screens, carbon fines, losses and the route to <a href="/insights/gold-elution-plant-price">carbon stripping and reuse</a>.</p>
<h2 id="quotation">Compare the complete delivered offer</h2>
<p>Request product identity, quantity, certificates, packaging, currency, delivery basis, validity, lead time and responsibility for freight, taxes and inland transport. Have the appropriate specialist confirm approvals and shipping documents. Do not infer duty exemption from holding a mining licence.</p>
<p>Keep reagents, carbon and spares in the <a href="/insights/gold-plant-setup-cost">startup operating-cash budget</a>. Delivery and receiving readiness must align with commissioning; materials that arrive early at an unprepared site do not improve readiness.</p>
<h2 id="conclusion">Buy a defined specification with a workable stock plan</h2>
<p>Specify consumables from the selected process, verify documentation and the permitted supply route, and calculate stock cover from production and lead time. Your next step is a procurement schedule reviewed by the process and site-management team, with acceptance criteria and storage responsibilities agreed before ordering.</p>
<h2 id="basis">Sources and example basis</h2>
<p>Manufacturer and Cyanide Code resources were reviewed on 5 October 2026. The stock arithmetic is illustrative; chemical conditions, quantities and approvals require the project’s own assessment.</p>`
export default content
