const content = `<p>An assay report is useful when the sample represents the material of interest and the analytical method answers the right question. A precise number from a poorly collected sample can still lead to the wrong exploration or plant decision. The work begins before the sample reaches the laboratory.</p>
<p>This guide helps you prepare an assay brief in Tanzania, choose appropriate methods and review the quality evidence. You should finish with a submission plan and an understanding of what the result establishes, rather than treat every gold number as a mine grade or recovery estimate.</p>
<h2 id="sampling">Define what the sample represents</h2>
<p>Record location, material, interval, collection method and mass. Distinguish a selected rock specimen from a systematic channel or drill sample. For stockpiles and tailings, design the coverage around variation in source, depth and treatment history. Keep identifiers unique and preserve the link between field records and laboratory certificates.</p>
<p>A laboratory cannot reconstruct a missing location or remove collection bias by using a more precise instrument. Ask a geologist to design the sampling programme around the intended decision before choosing the analytical package.</p>
<h2 id="preparation">Agree preparation and retention</h2>
<p>Specify drying where appropriate, crushing, splitting, pulverising and the retained material required. Discuss coarse gold and other heterogeneity with the laboratory because a small aliquot may not reflect a coarse-gold sample reliably. Preparation settings should be selected for the material and method rather than copied as universal percentages.</p>
<p><a href="https://www.alsglobal.com/de-ch/geochemistry/sample-preparation/sample-submission">ALS’s submission guidance</a> requires clear sample and method instructions. Request the preparation procedure, contamination controls and storage or return arrangements for residues and pulps.</p>
<h2 id="methods">Choose the method and reporting range</h2>
<p><a href="https://www.sgs.com/en-us/services/fire-assay-analysis">SGS’s fire-assay guidance</a> describes gold analysis and sample-size choices. Ask the laboratory which method, finish, detection limit and over-range procedure suit your expected grade. Discuss screened metallics or another appropriate approach when coarse gold is suspected; the laboratory should explain its selection.</p>
<p>Multi-element results can help investigate mineralisation and contaminants, but the digestion and method determine what is measured. A handheld screening measurement should not silently replace the agreed gold assay or metallurgical test.</p>
<h2 id="quality">Set quality checks before dispatch</h2>
<p>Use appropriate reference materials, blanks and duplicates through a designed QA/QC programme. Each check addresses a different uncertainty: standards assess analytical performance, blanks help identify contamination and duplicates investigate precision at the chosen sampling or preparation stage.</p>
<p><a href="https://www.alsglobal.com/-/media/ALSGlobal/Resources-Grid/ALS-Sample-Preparation-Quality-Control-Tech-Note.pdf">ALS’s preparation-quality note</a> explains the role of preparation duplicates. Set frequencies and failure rules with the responsible geologist and laboratory, considering the material and intended reporting use. A single universal percentage cannot establish data fitness.</p>
<h2 id="interpretation-example">Interpret grade under a stated basis</h2>
<p>Suppose, illustratively, a representative dry feed lot of 100 t averages 2 g/t gold. Its contained gold is 200 g. That does not mean 200 g will be sold: recovery, downstream losses, fineness and selling terms still matter. Conversely, one selected specimen at 20 g/t does not establish that the 100 t lot averages 20 g/t.</p>
<p>Check units, sample identifiers, method codes, quality results and anomalies before using assays in a model. Investigate failed controls and retain the original and revised certificates so the decision can be traced.</p>
<h2 id="conclusion">Commission analysis for a defined decision</h2>
<p>Design representative sampling, specify preparation and methods, and review the quality evidence before applying the numbers. Your next step is a submission sheet linked to a field sampling plan and the question you need answered. For plant selection, follow assays with the relevant <a href="/insights/plant-test-work-guide">metallurgical tests</a>.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Laboratory references were reviewed on 5 October 2026. The feed example is assumed. This guide does not certify individual laboratory locations, current accreditation scopes or turnaround times.</p>`
export default content
