const content = `<p>CIP, CIL and heap leaching are different ways to organise gold dissolution and recovery from solution. Choosing between them requires evidence about the ore and a project budget that includes water, waste, power and the time until gold can be sold. A tank count or a headline recovery percentage cannot make that decision on its own.</p>
<p>This comparison explains the process differences and the tests that make each option credible. The aim is to narrow your choices and prepare a test-work brief, rather than assume one route is the default for every Tanzanian deposit.</p>
<h2 id="difference">Where leaching and adsorption happen</h2>
<p>In carbon in pulp, or CIP, leaching is followed by a separate adsorption stage, where activated carbon collects dissolved gold. In carbon in leach, or CIL, carbon is present in the leaching circuit so dissolution and adsorption occur together. Both arrangements need a route to strip loaded carbon and recover a saleable product.</p>
<p>Heap leaching passes solution through a prepared bed of ore on an engineered pad. Solution is collected for downstream recovery. It changes the feed preparation, liquid flow and recovery schedule, so it needs more than a comparison of tanks against a pad. <a href="https://www.sgs.com/-/media/sgscorp/documents/corporate/brochures/sgs-nr-gold-processing-en.cdn.en-KZ.pdf">SGS’s gold-processing overview</a> provides a reference for these process routes.</p>
<h2 id="compare">Compare the design questions</h2>
<div class="tbl" tabindex="0" role="region" aria-label="Process-route comparison"><table><thead><tr><th>Route</th><th>Main design question</th><th>Evidence needed</th></tr></thead><tbody><tr><td>CIP</td><td>How should separate leaching and adsorption duties be arranged?</td><td>Leach kinetics, adsorption response and slurry properties.</td></tr><tr><td>CIL</td><td>How do simultaneous leaching and adsorption behave on this feed?</td><td>Combined tests, carbon management and screening requirements.</td></tr><tr><td>Heap leach</td><td>Can solution move through the prepared ore and recover worthwhile gold?</td><td>Column response, permeability, crush size and a site water balance.</td></tr></tbody></table></div>
<p>The table points to the uncertainty each route must resolve. It does not establish universal capital rankings or recovery ranges. A difficult pad site can change heap economics, while a difficult ore can make either tank arrangement unsuitable without additional treatment.</p>
<h2 id="ore">Test the ore’s behaviour</h2>
<p>Ask the laboratory how results vary with grind or crush size, treatment time, reagent use and feed domain. Carbonaceous material can remove dissolved gold from solution, a behaviour called preg-robbing. Its presence calls for comparative testing; it does not prove that simply adding carbon will solve every loss.</p>
<p>Keep oxide, transition and fresh ore separate where their behaviour differs. An average composite can conceal the period when harder or less responsive feed reaches the plant. Link the test selection to the mine schedule and compare gravity recovery as part of the options where relevant.</p>
<h2 id="example">Compare gold output without confusing it with profit</h2>
<p>Consider an assumed 1,000 t feed lot grading 1.5 g/t. It contains 1,500 g of gold. A hypothetical route recovering 70% produces 1,050 g; another recovering 90% produces 1,350 g. The difference is 300 g, but these percentages are teaching assumptions, not predictions for heap and tank plants.</p>
<p>Value the difference using a stated selling-price basis, then subtract the additional processing costs, selling deductions and capital burden. Also model when that gold becomes payable. A route with slower release can need more working cash even if its final recovery is attractive.</p>
<h2 id="whole-plant">Budget the whole route</h2>
<p>Include preparation, leaching, recovery from solution, elution where used, water recycling, residue treatment, containment, laboratory support and trained operators. The <a href="https://cyanidecode.org/about-the-cyanide-code/the-cyanide-code/">International Cyanide Management Code</a> is a management reference for cyanide supply and use; it does not replace local approvals or a site operating procedure.</p>
<p>Request a process description, equipment list, utilities, capital scope and operating model for each shortlisted route. Our <a href="/insights/plant-test-work-guide">test-work guide</a> helps prepare the evidence, and the <a href="/insights/gold-plant-setup-cost">startup guide</a> shows where owner costs and working capital belong.</p>
<h2 id="conclusion">Select the route the evidence supports</h2>
<p>Choose between CIP, CIL and heap leaching by comparing ore response, complete costs and cash timing under the same feed assumptions. Your next step is a representative test programme and a site assessment that resolve the main uncertainty for each option. Only then should a supplier turn the selected route into an equipment specification.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>The technical references were reviewed on 5 October 2026. The feed-and-recovery calculation is illustrative. Tank residence times, pad design and operating settings require project-specific test work and engineering.</p>`
export default content
