const content = `<p>A coal project in Mozambique needs a credible product and a workable delivery route as well as geological tonnage. Seam continuity, mining conditions, preparation yield and buyer specification determine what can be sold. Transport and handling then determine whether the sale can cover the full cost.</p>
<p>This guide explains how to connect coal exploration with quality testing and logistics, using Tete as a regional reference. The outcome should be a phased programme and a product basis, rather than an investment case built from a national resource headline.</p>
<h2 id="regional-context">Start with local seam evidence</h2>
<p>The <a href="https://pubs.usgs.gov/myb/vol3/2019/myb3-2019-africa-middle-east.pdf">USGS 2019 regional yearbook</a> records coal operations at Moatize in Tete Province. It is historical industry context, not evidence of present ownership, available transport capacity or resources within your licence.</p>
<p>Compile stratigraphy, historical holes, seams, faults, weathering and overburden for the specific area. Map what is exposed and record uncertainty where cover prevents direct observation. A thick intersection in one hole does not establish a continuous mineable seam.</p>
<h2 id="drill-plan">Collect geometry and representative coal</h2>
<p>Plan drilling and relevant borehole measurements around seam correlation, thickness, structure and sampling quality. Preserve the records and samples needed for quality and geotechnical assessment. The programme should distinguish coal, partings and adjacent material rather than silently combining them.</p>
<p>Agree sample handling and laboratory methods in advance. Moisture and degradation can change results, so the report needs the analytical basis, collection and preparation records. Review holes and correlations before expanding the campaign.</p>
<h2 id="quality">Define the intended product</h2>
<p>Thermal and metallurgical buyers ask different questions. Establish the required quality measures, reporting basis and qualification process with the laboratory and potential buyer. Parameters may include moisture, ash, sulphur, calorific value and the relevant coking properties for the proposed product.</p>
<p>Do not compare a dry-basis laboratory value with an as-received sale specification without conversion and an agreed moisture basis. “High-quality coal” is not a product specification that can support a revenue model.</p>
<h2 id="yield-example">Calculate saleable tonnes from raw feed</h2>
<p>Assume a raw-coal feed of 100,000 t/year and an illustrative preparation yield of 60% to a saleable product. Product quantity is 60,000 t/year, with the remaining material requiring a managed route. At an assumed USD 100/t product price, gross product value is USD 6 million before charges and costs.</p>
<p>These inputs are teaching assumptions. If the actual quality requires more rejection or blending, yield and price can both change. Model mining, preparation, waste, transport, handling, selling deductions and capital rather than treating raw tonnes as saleable tonnes.</p>
<h2 id="logistics">Verify the route to market</h2>
<p>Request written transport and handling terms for the actual road, rail and port route, including capacity, minimum commitments and delays. Check stockpile, loading and product-quality controls along the route. Do not infer bookable freight capacity from the existence of a regional corridor.</p>
<p><a href="https://www.usgs.gov/centers/national-minerals-information-center/mozambique">USGS’s Mozambique industry page</a> provides additional dated context. Current licences, land access, environmental work, safety requirements and export arrangements require local confirmation alongside the technical study.</p>
<h2 id="conclusion">Explore for a deliverable coal product</h2>
<p>Establish seam geometry, obtain representative quality and yield tests, and verify the complete route to the buyer. Advance the project using saleable product and delivered cost rather than raw tonnage alone. Prepare a drill-and-quality brief and an initial logistics enquiry before committing to a development case.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>USGS references were reviewed on 5 October 2026 and retain their reporting periods. Yield and price figures are illustrative. No current rail capacity, operator ownership or coal reserve is asserted.</p>`
export default content
