import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Copper is becoming a practical option for Tanzanian small-scale miners, not only for large companies. In June 2025 the country’s first modern copper processing plant opened at Chunya in Mbeya Region, and it buys ore from small-scale miners as well as treating its own. For a licence holder with copper showings, the question is whether to sell ore to a processor, process it on site or wait until the deposit is better understood. The answer depends on the type of copper ore, its grade, the distance to a buyer and what processing would cost.</p>
<p>This guide explains the main copper ore types and processing routes, what the Chunya plant shows about selling ore locally and how to evaluate a copper deposit before spending on equipment. A worked example shows how grade and payable terms turn a truckload of ore into an income estimate.</p>
<h2 id="chunya-plant">What the Chunya plant shows</h2>
<p>The plant at Chunya is operated by Mineral Access Systems Tanzania (MAST). According to reports at its launch, it treats low-grade ore containing about 0.5–2% copper from the Mbugani area and upgrades it to a copper product of up to 75% purity using leaching and cementation. It can process about 31,200 tonnes of ore a month, of which about 4,000 tonnes are bought from small-scale miners across the country, and the company has announced plans for further plants in Manyara, Ruvuma and Dodoma (<a href="https://www.theeastafrican.co.ke/tea/business-tech/tanzania-launches-modern-copper-processing-plant-5088446">The EastAfrican</a>; <a href="https://www.argusmedia.com/en/news-and-insights/latest-market-news/2701443-tanzania-launches-first-copper-processing-plant">Argus</a>).</p>
<p>For small miners, the important points are that a domestic buyer for copper ore now exists, and that it treats ore by leaching, which suits some ore types better than others. Confirm the buyer’s current purchasing terms directly before you mine for sale.</p>
<h2 id="ore-types">Know which copper ore you have</h2>
<p>Copper ores fall broadly into two groups. <strong>Oxide ores</strong>, often green or blue near the surface, dissolve in acid and are usually treated by leaching, followed by recovery of copper from the solution, for example by cementation onto scrap iron or by solvent extraction and electrowinning in larger plants. <strong>Sulphide ores</strong>, usually deeper and metallic-looking, respond poorly to simple leaching and are normally ground and concentrated by flotation, then sold as a concentrate for smelting.</p>
<p>Many deposits contain both, with oxides near the surface giving way to sulphides at depth. That matters because a buyer set up for leaching may pay less for, or refuse, ore that does not leach well. A mineralogy check and a simple leach test on representative samples tell you which group your ore belongs to before you commit to mining or equipment.</p>
<h2 id="worked-example">A worked example: valuing a load of ore</h2>
<p>Assume a miner delivers 30 tonnes of dry ore assaying 1.5% copper. The load contains 30 × 0.015 = 0.45 tonnes, or 450 kg, of copper. The buyer will not pay for all of it: payment depends on the agreed payable share, any deductions for moisture or impurities, transport and the copper price on the settlement date. If the buyer’s terms paid for an assumed 50% of contained copper, the miner would be paid for 225 kg. Multiply that by the price per kilogram in the buyer’s written terms, then subtract mining, loading and transport costs to see whether the load is worth sending.</p>
<p>These percentages are assumptions to show the method, not the Chunya plant’s terms. Ask any buyer for written terms that state how ore is sampled and assayed, how moisture is measured, what share of contained copper is paid, which price is used and how quickly payment follows delivery.</p>
<h2 id="sell-or-process">Sell ore or process on site?</h2>
<p>Selling ore is usually the right starting point for a small operation. It needs little capital, gives early income and produces assay and payment records that show what the deposit is worth. Processing on site makes sense only when the tonnage, grade and distance to a buyer justify it, and when tests confirm a route that works on your ore.</p>
<p>A small leach-and-cementation operation needs acid supply and safe handling, lined leach pads or tanks, solution management and a plan for spent solution and residues, all within an environmental approval. Flotation of sulphide ore needs crushing, grinding and flotation equipment with reliable power and water, and a buyer for the concentrate. Both routes involve chemicals and residues that need specialist design and approval, so treat them as projects with test work and an environmental assessment, not as an equipment purchase.</p>
<h2 id="next-steps">Steps before you invest</h2>
<ol>
<li>Confirm that your licence covers copper and what sales records the Mining Commission requires.</li>
<li>Take representative samples from the material you would mine, not selected rich pieces, and have them assayed for copper.</li>
<li>Ask the laboratory whether the ore is mainly oxide or sulphide, and run a simple leach test.</li>
<li>Obtain written purchasing terms from a buyer and estimate transport cost to their gate.</li>
<li>Only then compare continued ore sales with any on-site processing option.</li>
</ol>
${renderArticleFaqs("copper-ore-processing-tanzania", "en")}
<h2 id="conclusion">Start by proving the ore and the buyer</h2>
<p>Copper offers Tanzanian small-scale miners a new route to income now that a domestic processor buys ore. Whether it pays depends on the ore type, its grade, the buyer’s terms and transport. Prove those with representative assays, a leach test and written terms before spending on equipment, and treat on-site processing as a later, tested project. Your next step is a sampling plan for the copper showings on your licence.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Details of the Chunya plant come from reports by <a href="https://www.theeastafrican.co.ke/tea/business-tech/tanzania-launches-modern-copper-processing-plant-5088446">The EastAfrican</a> and <a href="https://www.argusmedia.com/en/news-and-insights/latest-market-news/2701443-tanzania-launches-first-copper-processing-plant">Argus</a>, reviewed on 7 October 2026; confirm current terms with the operator. Licence and sales requirements should be confirmed with the <a href="https://www.tumemadini.go.tz/">Mining Commission</a>. The ore valuation uses assumed grade and payable share to show the method and does not represent any buyer’s terms. Our <a href="/equipment/flotation-cell">flotation cell</a> page and <a href="/insights/flotation-graphite-copper">flotation guide</a> cover sulphide copper processing.</p>`
export default content
