import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Hiring equipment can help a mine complete a defined job without paying the full purchase price upfront. Whether it saves money depends on the working period, utilisation, transport and the responsibilities in the contract. A daily rate alone does not tell you what a productive hour will cost.</p>
<p>This guide explains how to compare rental, leasing and purchase for a Tanzanian project. You should finish with a common cost basis and a contract checklist, rather than a blanket rule that every job shorter than a particular number of months should be hired.</p>
<h2 id="job">Define the job and availability you need</h2>
<p>Describe the duty, location, start date, expected hours and site readiness. For a generator, provide the load and starting requirements; for a pump, the fluid, flow and head; for a compressor, tool demand and pressure. Equipment that cannot perform the duty is costly even at a low hire rate.</p>
<p>Separate scheduled hours from productive hours and identify standby periods caused by weather, feed or other contractors. Ask how the hire is billed during each period. <a href="https://www.cat.com/en_US/campaigns/awareness/cat-rent-lease-buy.html">Caterpillar’s rent, lease and buy comparison</a> is a useful reference for the different commitments, but local availability and terms require actual offers.</p>
<h2 id="responsibilities">Confirm what wet and dry hire mean in this offer</h2>
<p>Dry hire commonly provides the machine without an operator, while wet or operated hire includes an operator. Fuel, maintenance, consumables and insurance should still be specified individually. The label does not prove that all those services are included or that every breakdown risk belongs to the owner.</p>
<p>Agree who performs daily checks, who authorises repairs, how faults are reported and what response the supplier can provide at your location. <a href="https://rent.cat.com/en_MM/articles/how-to-manage-rental-equipment">Cat’s rental-management guidance</a> emphasises planning maintenance and support. Apply that principle through written responsibilities rather than an assumption about the hire category.</p>
<h2 id="worked-comparison">Compare complete costs over the same period</h2>
<p>For an illustrative six-month job, assume hire at USD 2,000/month and USD 3,000 total mobilisation and return costs. Hire totals USD 15,000 before fuel and items excluded by the assumed contract. For an assumed purchase at USD 30,000, add USD 3,000 delivery, USD 2,000 maintenance and USD 2,000 financing, then subtract an assumed USD 23,000 net resale receipt. Ownership totals USD 14,000 on that basis.</p>
<p>The USD 1,000 difference is not a recommendation to buy. If resale is only USD 18,000, ownership becomes USD 19,000. Neither example includes tax or a quantified downtime cost, and resale may occur after the cash is needed. Replace every amount with written offers and realistic disposal assumptions.</p>
<h2 id="contract">Resolve the terms before mobilisation</h2>
<ul><li>Minimum period, included hours, overtime and standby charging.</li><li>Fuel, operators, servicing, wear parts and repair responsibilities.</li><li>Mobilisation, return transport and notice to end the hire.</li><li>Availability commitments, breakdown response and the agreed remedy.</li><li>Insurance, excess, permitted use and liability for damage.</li><li>Arrival condition report, meter readings and return inspection.</li></ul>
<p>Check whether the supplier can actually support the proposed site. An availability promise needs a measurement period and a remedy, while a response-time promise should distinguish attending the site from restoring operation.</p>
<h2 id="pml-holders">Match hire to a small-scale licence</h2>
<p>Many primary mining licence holders work in stages: a test pit or bulk sample, a trial season and then steady production if the ground pays. Hire suits the early stages well, because it lets you test a generator, pump or wash plant on your own ground before committing capital. It also suits seasonal work, such as alluvial washing that slows during the rains, where a purchased machine would stand idle for part of the year.</p>
<p>Bart Mining offers equipment rental and leasing; tell us the duty, the period and your site, and we will set out both options on the same basis. Whichever supplier you use, check that they will deliver to your site and support it there, because a breakdown far from a workshop can cost more in lost days than the hire itself. Agree in writing what happens if the hire runs past the trial period, and whether any hire payments count towards a later purchase. Once production is steady and the machine runs most days, compare the hire cost with purchase using the method above, and test the repayments in the <a href="/insights/small-miner-financing">financing guide</a>. If you are considering a second-hand machine instead, read our guide to <a href="/insights/used-mining-equipment-tanzania">buying used equipment</a> first.</p>
<h2 id="lease">Evaluate leasing separately</h2>
<p>A lease can spread payments and may include an ownership option, but the full contract determines deposit, total payments, maintenance, termination and default consequences. Do not treat an advertised monthly amount as the total cost of owning the machine.</p>
<p>Use the <a href="/insights/small-miner-financing">financing guide</a> to test repayments against a weaker production month. For short power needs, our <a href="/generator-rental">generator-rental page</a> explains the information required for an equipment enquiry.</p>
${renderArticleFaqs("equipment-rental-tanzania", "en")}
<h2 id="conclusion">Choose from a complete job cost</h2>
<p>Specify the duty and hours, compare full-period costs and confirm who handles downtime and maintenance. Rental can preserve cash and flexibility; ownership can suit sustained use when support and resale assumptions are credible. Obtain comparable offers and test uncertain utilisation before choosing the arrangement.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Manufacturer references were reviewed on 5 October 2026. All example costs and resale values are assumed and do not represent current Tanzanian rental rates.</p>`
export default content
