import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Flotation is the standard way to concentrate copper sulphide ore and flake graphite, two of the minerals now attracting investment in Tanzania. Graphite is produced at Lindi Jumbo and at God Mwanga Gems’ plants in Tanga Region, and copper sulphides lie beneath many of the oxide showings that small miners work today. A licence holder or junior developer who wants a flotation plant must specify the ore, the tests and the circuit before any equipment supplier can quote a design that will work.</p>
<p>This guide explains how flotation separates minerals, how the circuit differs for copper and graphite, what a buyer needs to specify and how to estimate the concentrate a plant will produce. It is a planning guide, not a reagent recipe: the reagent scheme and operating settings come from test work on your ore.</p>
<h2 id="how-flotation-works">How flotation separates minerals</h2>
<p>In a <a href="/equipment/flotation-cell">flotation cell</a>, ground ore is mixed with water and reagents. A collector coats the valuable mineral so that it repels water, and a frother stabilises small air bubbles that an impeller or blower disperses through the slurry. The coated particles attach to the bubbles and rise into a froth that overflows as concentrate, while the waste minerals stay in the slurry and leave as tailings. Depressants and pH modifiers stop unwanted minerals from floating.</p>
<p>Flotation needs particles that are fine enough to be released from the rock and to be lifted by a bubble. That is why the plant starts with crushing and grinding, often in a ball mill closed by a <a href="/equipment/spiral-classifier">spiral classifier</a> or hydrocyclone, and why the grind size is one of the first things the test work must settle.</p>
<h2 id="copper-circuit">The circuit for copper sulphide ore</h2>
<p>Copper sulphide ore is usually ground to the size at which the copper minerals are released, then floated in a rougher stage that recovers most of the copper into a low-grade concentrate. Scavenger cells recover more copper from the rougher tailings, and one or more cleaner stages raise the concentrate grade by refloating it, sometimes after a regrind. The finished concentrate is thickened and filtered, often in a <a href="/equipment/filter-press">filter press</a>, and sold to a smelter or a hydrometallurgical refinery.</p>
<p>Oxide copper ore floats poorly with ordinary sulphide collectors and is usually leached instead. Many deposits change from oxide near the surface to sulphide at depth, so test both zones. Our <a href="/insights/copper-ore-processing-tanzania">copper ore guide</a> explains how to tell them apart and what selling ore to a processor involves.</p>
<h2 id="graphite-circuit">The circuit for flake graphite</h2>
<p>Graphite floats naturally, so the challenge is not making it float but reaching a high carbon grade without breaking the flakes. Large flakes sell for more than fine ones, and over-grinding destroys that value. Graphite plants therefore grind gently, take a rougher concentrate, then regrind it lightly and clean it through several stages to remove the gangue minerals still attached to the flakes. Published test programmes describe rougher concentrate reground to around 150 microns followed by multi-stage cleaning to reach grades in the mid-90s percent carbon.</p>
<p>The number of cleaning stages, the regrind energy and the final grade are trade-offs between grade, recovery and flake size. A buyer should ask the laboratory to report the flake-size distribution of the concentrate as well as its grade and recovery.</p>
<h2 id="worked-example">Estimate the concentrate a plant will produce</h2>
<p>The mass of concentrate follows from the feed grade, the recovery and the concentrate grade. As a worked assumption for copper, a plant treating 100 tonnes a day of ore at 1.2% copper, recovering 85% of it into a concentrate grading 25% copper, produces 100 × 0.012 × 0.85 ÷ 0.25 = about 4.1 tonnes of concentrate a day.</p>
<p>For graphite, a plant treating 100 tonnes a day at 8% graphitic carbon, recovering an assumed 85% into a 94% carbon concentrate, produces 100 × 0.08 × 0.85 ÷ 0.94 = about 7.2 tonnes a day. These figures show the arithmetic only; your grade, recovery and saleable concentrate grade come from test work and from buyers’ specifications.</p>
<h2 id="what-to-specify">What to specify before asking for a plant</h2>
<ol>
<li>Representative samples from each ore zone, with mineralogy showing how the valuable mineral occurs.</li>
<li>Grind and flotation test results, including locked-cycle tests where possible, giving grade and recovery for each stage.</li>
<li>The reagent scheme and consumption the tests used.</li>
<li>For graphite, the flake-size distribution of the concentrate; for copper, the concentrate’s penalty elements.</li>
<li>Tonnes per day, operating hours, and the power and water available.</li>
<li>How tailings will be stored and how process water will be recycled; see our <a href="/insights/water-recycling-gold-plant">water recycling guide</a>.</li>
</ol>
${renderArticleFaqs("flotation-graphite-copper", "en")}
<h2 id="conclusion">Specify the ore before the cells</h2>
<p>A flotation plant works when its grind, reagents and circuit are designed around tested ore. For copper sulphides the goal is a clean concentrate at good recovery; for graphite it is a high-grade concentrate that keeps the flakes large. Both depend on representative samples and staged test work. Start with mineralogy and a flotation test programme on samples from each ore zone, then ask suppliers to quote against those results.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Graphite producers in Tanzania are taken from <a href="https://projectblue.com/blue/news-analysis/1315/new-graphite-supply-increases-tanzania’s-market-share">Project Blue</a>. The description of staged graphite cleaning follows published test programmes summarised by <a href="https://www.jmma.tfbor.bg.ac.rs/?p=347">the Journal of Mining and Metallurgy</a>. Flotation cell principles are described on <a href="https://www.911metallurgist.com/blog/denver-flotation-machine/">911 Metallurgist</a>. Sources were reviewed on 7 October 2026. The concentrate examples use assumed grades and recoveries to show the calculation and are not results for any deposit.</p>`
export default content
