const content = `<p>Geological mapping records exposed rocks, structures and alteration and uses those observations to interpret a project area. It helps an explorer decide where further sampling, geophysics or drilling can test a meaningful hypothesis. The map should show both what is observed and what remains uncertain beneath cover.</p>
<p>This guide explains how to scope mapping for a Tanzanian project and what to request at handover. The useful outcome is a target model with supporting records, rather than a coloured map that cannot be connected to field evidence.</p>
<h2 id="desktop">Start with existing information</h2>
<p>Compile licence boundaries, historical reports, survey data, imagery and available geological maps. <a href="https://www.gst.go.tz/pages/geological-mapping">The Geological Survey of Tanzania’s mapping programme</a> provides a starting reference for regional map coverage and work. Check the edition, scale and source of the material used for your area.</p>
<p>Regional maps establish context but may not resolve a narrow vein or contact. Record gaps, conflicting coordinates and uncertain interpretations before planning field coverage. An inherited target location should be checked, not accepted because it appears on several copied maps.</p>
<h2 id="field-scope">Choose detail around the decision</h2>
<p>Licence reconnaissance and detailed prospect mapping need different coverage. Specify which rock units, contacts, structures and alteration must be investigated, where exposure exists and what access is permitted. Set the mapping scale and traverse plan with the geologist rather than treating scale as a universal spacing rule.</p>
<p>For a simple scale illustration, 1 cm on a 1:100,000 map represents 1 km on the ground; at 1:5,000 it represents 50 m. Enlarging the first map on a screen does not create the field detail of the second.</p>
<h2 id="observations">Preserve the evidence behind the interpretation</h2>
<p>Use located observations, photographs, sample identifiers and consistent rock and structure descriptions. Record weathering and exposure quality. Separate an observed contact from an inferred contact and explain the reason for extending it beneath cover.</p>
<p>Imagery and topography can guide traverses, but linear features are not automatically faults and colour differences are not automatically alteration. Ground-check the features that control the target model. Add geochemistry or permitted subsurface work where surface evidence is inadequate.</p>
<h2 id="integration">Use other datasets to test the map</h2>
<p>Geophysical data may help interpret covered structures or rock contrasts. <a href="https://www.usgs.gov/special-topics/earth-mri/geophysical-mapping">USGS’s geophysical-mapping guidance</a> explains how magnetic and other datasets support geological understanding. They remain indirect evidence and should be reconciled with field observations.</p>
<p>In a hypothetical gold prospect, a sampled vein and an interpreted structure beneath cover could justify a targeted traverse or drill test. The mapping report should explain that reasoning and alternatives, rather than label the covered continuation as established ore.</p>
<h2 id="deliverables">Request a map and a usable project dataset</h2>
<ul><li>Map files with scale, coordinates, legend, source dates and observed versus inferred features.</li><li>Located observations, photographs and sample records linked by identifiers.</li><li>Cross-sections or interpretations needed to explain target geometry.</li><li>A ranked target list with evidence, uncertainties and proposed tests.</li><li>A report documenting methods, coverage and access limitations.</li></ul>
<p>Keep editable spatial files and the original observations as well as a PDF. That lets the drilling and modelling team update interpretations without rebuilding the dataset from an image.</p>
<h2 id="conclusion">Use mapping to choose the next test</h2>
<p>Scope the survey around a project decision, preserve the observations and make uncertainty visible on the interpretation. A useful map leads to a justified next programme and identifies what would change the model. Begin with a desktop compilation and a field brief that names the geological questions.</p>
<h2 id="basis">Sources and example basis</h2>
<p>Survey references were reviewed on 5 October 2026. The prospect scenario is hypothetical; scale conversions are arithmetic and do not prescribe traverse spacing.</p>`
export default content
