const content = `<p>Geophysics measures physical properties that can help interpret rocks and structures beneath cover. It is valuable when a geological question has a measurable contrast, but an anomaly is not automatically an orebody. The method and survey design should be chosen from the target and conditions at site.</p>
<p>This guide helps an East African project owner scope airborne or ground work, understand the limitations and request useful deliverables. The outcome should be an interpreted target with a testable explanation, rather than a survey chosen because the instrument sounds advanced.</p>
<h2 id="method-selection">Identify the contrast you need to measure</h2>
<p>Magnetic surveys can help map magnetic rock differences and structures. Electromagnetic methods investigate conductivity; conductive responses can arise from target minerals or other materials. <a href="https://www.usgs.gov/special-topics/earth-mri/geophysical-mapping">USGS’s geophysical-mapping overview</a> explains these uses and provides context for interpreting them.</p>
<p>Induced polarisation, or IP, and resistivity investigate electrical behaviour that may help test a particular mineralisation model. <a href="https://www.usgs.gov/publications/electrical-geophysical-investigations-massive-sulfide-deposits-and-their-host-rocks">USGS’s sulphide-deposit research</a> illustrates both useful responses and variability. Gold itself should not be assumed to explain every chargeable or conductive anomaly.</p>
<h2 id="airborne-ground">Choose coverage and detail together</h2>
<p>Airborne work can provide wider coverage, while ground surveys may investigate a selected target at greater detail. Terrain, access, cultural interference, cover and the anticipated target depth affect the programme. Specify the objective before selecting line spacing, flight height, electrode layout or system.</p>
<p>For an illustrative rectangular block 2 km wide, parallel lines spaced 200 m apart give 11 lines if both edges are included. At 3 km each, that is 33 line-km before tie lines, extensions and logistics. This calculation helps check a tender quantity; it does not establish that 200 m spacing can resolve your target.</p>
<h2 id="quality">Define acquisition quality and ownership</h2>
<p>Agree positioning, calibration, noise checks, repeat measurements and acceptance criteria with the geophysicist. Record the instrument configuration and processing history. Ask how cultural effects such as power lines, fences or machinery will be identified and managed.</p>
<p>Require the raw and corrected data, coordinates, processing parameters, grids and interpretation. A set of attractive images without those records may be difficult to reprocess or compare with later work. Confirm data ownership and handover formats in the contract.</p>
<h2 id="interpretation">Interpret with geology and alternative explanations</h2>
<p>Compare anomalies with mapping, geochemistry, known workings and other datasets. State the physical source being proposed and plausible alternatives. The interpretation should explain which result would support the target model and which field observation or drill hole can distinguish it from another source.</p>
<p>For a hypothetical conductor under cover, graphite, sulphides or groundwater-related effects may need consideration depending on the setting. Its location can justify investigation, but cannot establish metal grade, thickness or mine economics without direct evidence.</p>
<h2 id="scope-cost">Price the complete programme</h2>
<p>Request mobilisation, acquisition units, access or aviation requirements, processing, interpretation, reporting and any repeat-work terms. Define who handles permissions and site preparation. Quoting a rate per line-kilometre without the survey configuration and deliverables leaves important scope unresolved.</p>
<p>Use the results to update the <a href="/insights/geological-mapping">geological model</a> and rank targets before <a href="/insights/drilling-services-tanzania">drilling</a>. Budget interpretation as part of the survey rather than assuming the instrument output is the final decision.</p>
<h2 id="conclusion">Survey for a testable geological explanation</h2>
<p>Choose geophysics from the expected physical contrast, agree acquisition quality and retain the underlying data. Interpret anomalies alongside geology and define the next direct test. Prepare a brief with the target model, cover, access and decision required before requesting a survey price.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>USGS references were reviewed on 5 October 2026. The line-kilometre and conductor examples are illustrative. No depth guarantee or mineral-discovery claim is made.</p>`
export default content
