import { CHUNYA_EXAMPLES, MONTHLY_OPERATING_EXAMPLES, totalCost, usd } from '@/data/plant-cost-examples'
const [wash, starter, full] = CHUNYA_EXAMPLES
const categories = ['Shipping, insurance, clearing and inland delivery', 'Installation crew and lifting', 'Civil works allowance', 'Engineering and project management', 'Testing, inspection and permits', 'Commissioning and first-year wear parts', 'Contingency']
const rows = categories.map((label, i) => `<tr><th scope="row">${label}</th><td>${usd(wash.categories[i])}</td><td>${usd(starter.categories[i])}</td><td>${usd(full.categories[i])}</td></tr>`).join('')
const operating = MONTHLY_OPERATING_EXAMPLES[0]

const content = `
<p>Opening a gold processing plant means organising a working system: feed, recovery, water, power, people and a way to handle the material left after processing. A collection of machines cannot start production until those parts are ready. Your startup budget should therefore follow the work needed to take the project from tested feed to a commissioned operation.</p>
<p>This guide uses our October 2026 Chunya proposals to show what sits between an equipment purchase and plant startup. It explains how to choose an alluvial or hard-rock route, build the delivery and construction budget, reserve operating cash and agree acceptance criteria. For the side-by-side capital and operating calculations, read our <a href="/insights/mining-equipment-cost-tanzania">plant and equipment cost guide</a>.</p>

<h2 id="define-the-plant">Define the plant you are trying to open</h2>
<p>For loose gravel containing liberated gold, start by investigating washing, screening and gravity recovery. The Chunya Phase 1 proposal uses a washing screen and six sluices at a nominal 150 m³/h. Its layout allows later fine-gold recovery equipment, subject to testing and detailed design. Where clay needs more intensive treatment or the recovery duty differs, a scrubber-based circuit may be suitable.</p>
<p>Hard-rock ore requires a different assessment. Crushing and a ball mill prepare the material for recovery, with the grinding duty established through test work. Gravity alone may suit part of the gold; CIL or CIP becomes a separate investment decision if leaching can recover additional gold economically. Refractory material may require further treatment. The plant choice should follow representative testing, the available feed supply and the site conditions.</p>
<figure><img src="/equipment/jaw-crusher.jpg" alt="Jaw crusher from the Bart Mining equipment catalogue" width="1200" height="800" loading="lazy" /><figcaption>Equipment reference: a jaw crusher reduces hard-rock feed before milling. The Chunya alluvial proposals discussed here do not include a crushing and grinding circuit.</figcaption></figure>

<h2 id="equipment-and-execution">Separate equipment from the work required to start it</h2>
<p>The Chunya proposals put equipment and execution services on separate lines. The current washing-and-sluice package has ${usd(wash.equipment)} of equipment and approximately ${usd(wash.execution)} of estimated execution services, giving ${usd(wash.total)} before separately payable import taxes, other statutory charges and owner operating capital. The two earlier scrubber options have different scopes and allowances.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Cost table; scroll horizontally to see all columns"><p class="article-table-caption">Client-facing Chunya startup scope, rounded USD. Services are proposal estimates.</p><table aria-label="Client-facing Chunya startup scope, rounded USD. Services are proposal estimates."><thead><tr><th scope="col">Cost category</th><th scope="col">Washing + sluices, 150 m³/h</th><th scope="col">Scrubber, 75 m³/h</th><th scope="col">Scrubber, 150 m³/h</th></tr></thead><tbody>
<tr><th scope="row">Equipment</th><td>${usd(wash.equipment)}</td><td>${usd(starter.equipment)}</td><td>${usd(full.equipment)}</td></tr>${rows}
<tr><th scope="row">Equipment + execution total</th><td><strong>${usd(wash.total)}</strong></td><td><strong>${usd(starter.total)}</strong></td><td><strong>${usd(full.total)}</strong></td></tr>
</tbody></table></div>
<p>Totals are rounded from the underlying proposal model, so adding displayed category amounts can differ by a dollar. The washing proposal is dated 5 October 2026; the scrubber proposal is dated 3 October. These are proposed client prices, rather than the final cost of completed installations. Recovery, throughput and the final scope remain subject to feed testing, design and site assessment.</p>
<p>The difference between the two 150 m³/h options is particularly useful. One is a screen-and-sluice first stage; the other uses a scrubber, centrifugal recovery and a more developed supporting scope. The same feed capacity does not make them equivalent plants. Compare clay handling, gold size, recovery tests, water requirements and the services included before judging which investment suits your deposit.</p>

<h2 id="site-infrastructure">Price water, power and tailings as part of the plant</h2>
<p>The washing-and-sluice proposal specifies about 400 m³/h of circulating wash water at a 35–40 m pumping head and about 147 kW of installed electrical load, with a 200 kW diesel generator in the priced configuration. Circulating water is not necessarily fresh-water demand: settling and recycling can return part of it. The actual pump selection depends on the source distance, elevation and pipe losses, so the water survey can change both equipment and operating costs.</p>
<p>For hard-rock processing, the mill can drive the electrical load. A motor list, starting method and supply assessment should be completed before selecting a generator or planning the grid connection. The design must also cover safe electrical distribution, drainage and a tailings facility appropriate to the material and process. A leach plant introduces additional containment and monitoring requirements.</p>
<p>Ask for drawings and quantities behind the civil-work allowance. Foundations, access for offloading, settling ponds, drainage, fuel storage and the gold room should have clear responsibilities. Where the estimate cannot yet price an item, keep it visible as an unresolved cost.</p>

<h2 id="owner-budget">Build an owner’s budget alongside the proposal</h2>
<p>The proposal total does not fund the entire mining business. Add land or site access, mineral rights, feed excavation and haulage, mining-fleet purchases or hire, import taxes, statutory charges, financing and routine overhead. Confirm applicable approvals and charges with the relevant authorities and advisers. The Chunya model’s import-duty assumption is not evidence that a different importer or consignment qualifies for relief.</p>
<p>Keep construction contingency and operating cash separate. Construction contingency covers uncertainty within the delivery project. Operating cash pays fuel, wages, consumables and servicing while the plant begins producing and gold sales are collected. Neither should be spent on an equipment upgrade without revising the funding plan.</p>

<h2 id="operating-cash">Reserve cash for the first months of production</h2>
<p>Our <a href="/insights/mining-equipment-cost-tanzania#operating-costs">worked operating-cost comparison</a> assumes a 150 m³/h washing plant, 20 scheduled hours a day, 26 days a month and 75% productive availability. With stated assumptions for fuel, feeding, labour, wear, water and overhead, its processing cost is approximately ${usd(totalCost(operating.costs))} per month. Two months would require approximately ${usd(totalCost(operating.costs) * 2)} beyond the capital proposal and other owner costs.</p>
<p>This is an illustrative cash reserve, not an operating quote or a Chunya production forecast. For your project, replace the assumed fuel use with an equipment load and consumption assessment, obtain local feeding and labour costs, and test the effect of fewer operating hours. Startups with slower ramp-up or delayed sales may need a longer reserve.</p>
<p>Revenue also needs a tested basis. Alluvial grade is often expressed in grams per cubic metre, while hard-rock grade is usually expressed in grams per tonne. Use a consistent feed unit, measured grade and recovery appropriate to the planned circuit. Calculate cash after mining, processing, selling deductions and financing; gross gold value alone cannot establish viability.</p>

<h2 id="schedule-and-acceptance">Agree the schedule and the conditions for handover</h2>
<p>The current washing proposal models 16 weeks from the start of its delivery sequence to production. The earlier scrubber options model 24 and 26.5 weeks. These are planning schedules with dependencies, not promises for every plant. Manufacturing, inspection, shipping, clearance and installation all need time, while civil works and the water system should progress in parallel where possible.</p>
<p>Before placing the order, agree the feed conditions for testing, the throughput demonstration, the recovery assessment, acceptable defects and operator training. The washing proposal calls for three consecutive shifts at or near the design rate without critical defects before commissioning sign-off. Recovery should still be assessed through representative sampling and reconciliation, rather than inferred from a machine running.</p>
<p>Make handover include operating instructions, electrical and process documentation, a maintenance plan, recommended spares and a list of unresolved work. A plant is ready to operate when the team can run and maintain it under the agreed conditions.</p>

<h2 id="questions">Questions before opening a plant</h2>
<h3>Is the least expensive plant the best first stage?</h3>
<p>It can be if testing supports the circuit and the project can supply the necessary feed and water. The Chunya washing-and-sluice proposal is a specific first-stage approach with later recovery additions in mind. A cheaper arrangement that cannot handle the clay or capture the relevant gold size may cost more through lost production.</p>
<h3>Do I need an elution plant when I add CIP or CIL?</h3>
<p>You need a defined route for recovering gold from loaded carbon, whether on site or through a suitable service arrangement. Compare transport, batch size, security, charges and cash timing before deciding to own the equipment. Include that route in the leach-plant budget from the start.</p>
<h3>What should I send to request a plant proposal?</h3>
<p>Send the site location, deposit and feed description, sample or test results, sustainable feed rate, planned hours, water-source details and power availability. State the equipment or infrastructure already on site and which services you want included. This helps the supplier quote the scope you actually need.</p>

<h2 id="conclusion">A startup budget should finish with a plant you can operate</h2>
<p>Choose the recovery route from the feed and test results, then fund the equipment, delivery, site infrastructure and commissioning as one project. Add the owner’s costs and a separate operating reserve before deciding whether the investment is affordable. The Chunya proposals make the distinction concrete: ${usd(wash.equipment)} of equipment becomes about ${usd(wash.total)} with the proposed execution scope, and the business still needs operating cash.</p>
<p>The next step is a site and feed brief that can support detailed design and an itemised quotation. That brief should resolve the major unknowns in water, recovery, power and feed supply, so the budget leads to a clear decision about opening the plant.</p>

<h2 id="basis">Basis of this guide</h2>
<p>Capital figures come from the client-facing Chunya proposals dated 3 and 5 October 2026 and their Plant Planner calculations. Services remain preliminary allowances. The private supplier and internal commercial figures are excluded. The operating reserve is calculated from the explicitly assumed scenario in the linked equipment-cost guide; it is not drawn from the proposal as a measured operating expense.</p>
<p>For the supporting site work, consult <a href="https://www.cat.com/en_US/by-industry/electric-power/electric-power-resources/genset-sizing.html">Caterpillar’s generator-sizing guidance</a> and <a href="https://eia.nemc.or.tz/dev/web/home.eu">NEMC’s environmental assessment registration portal</a>. These explain parts of the preparation process; they do not validate the proposal budget or establish approval for a particular site.</p>
`
export default content
