import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Gravity separation and cyanide leaching recover gold by different mechanisms. Gravity concentrates particles according to their physical behaviour, while leaching dissolves accessible gold into solution for later recovery. The useful question is how much each route can recover from your feed and whether the additional recovery justifies its complete cost.</p>
<p>A project may suit gravity alone, a combined circuit or another treatment route. This guide shows how to compare those choices without assuming that all gold is liberated, that leaching solves every ore problem or that two recovery percentages can simply be added together.</p>
<h2 id="gravity">What gravity needs from the feed</h2>
<p>Gravity equipment works on differences in particle density, size and behaviour in the separating medium. Gold that remains locked within another mineral may respond differently from liberated gold. Feed preparation and concentrate cleanup therefore matter as much as buying a concentrator.</p>
<p><a href="https://www.sgs.com/en/-/media/sgscorp/documents/corporate/brochures/sgs-min-wa012-gravity-separation-en-11.cdn.en.pdf">SGS’s gravity-separation guidance</a> emphasises particle size and density differences. Ask a laboratory to assess the intended feed, test method and size fractions, and explain how a laboratory result relates to the proposed plant circuit. Do not use a universal fine-gold cutoff as a performance guarantee.</p>
<h2 id="leaching">What leaching adds and what it cannot assume</h2>
<p>Cyanide leaching can recover suitable gold not collected by gravity, but it still depends on accessibility, chemistry and time. Gold enclosed in resistant minerals or ore with difficult solution chemistry may need a different treatment or pretreatment. Establish the response through mineralogy and comparative leach testing.</p>
<p>A leach circuit also needs recovery from solution, residue management and appropriate operator capability. Evaluate the whole route, including carbon handling and <a href="/insights/gold-elution-plant-price">elution</a> where used, rather than treating leach tanks as the complete plant.</p>
<h2 id="combined-example">Calculate combined recovery correctly</h2>
<p>Assume a test feed contains 100 g of gold. If gravity collects 40 g, 60 g remains in its tailings. If a subsequent test recovers 80% of that remaining gold, leaching adds 48 g. Combined recovery is therefore 40 + 48 = 88 g, or 88% of the original gold, rather than 40% + 80% = 120%.</p>
<p>These figures are illustrative. A real comparison needs measured stream masses and assays, including solution, concentrate and residue inventories. Ask the laboratory to reconcile the balance and report whether downstream handling introduces further losses.</p>
<h2 id="economics">Value the incremental route</h2>
<p>For a combined option, assess the extra payable gold against additional capital, reagents, power, labour, analysis, waste handling and working cash. Gravity itself also consumes resources and produces residues requiring management. A mechanical route does not remove environmental or mine-licensing responsibilities.</p>
<p>Use the same ore schedule and price basis for alternatives. Test a lower-recovery case and a supply interruption, and avoid funding an expansion solely from the best laboratory composite. Our <a href="/insights/mining-equipment-cost-tanzania">plant-cost guide</a> separates equipment from startup and operating allowances.</p>
<h2 id="upgrade-path">Moving an operating gravity plant to leaching</h2>
<p>Many small operations already run gravity recovery and want to know whether adding a leach circuit is worth it. The evidence usually starts in the gravity tailings. Sample the tailings over several weeks, assay them and ask a laboratory to run leach tests on that material, ground to the size the new circuit would use. If the tailings still carry gold that dissolves well, the combined-recovery calculation above shows how much extra gold the upgrade could add.</p>
<p>The upgrade adds more than tanks. It usually needs a finer grind than many gravity plants use, often a ball mill with classification, then a train of <a href="/equipment/leaching-tank">leaching tanks</a> with agitators and air, carbon handling, a route for loaded carbon through an owned or toll <a href="/equipment/gold-elution-electrowinning-plant">elution plant</a>, cyanide storage and handling, a lined tailings facility and continuous power. It also brings new approvals and operator training. Keep the gravity circuit ahead of the leach so that free gold is still recovered early, and plan the layout so the plant can keep producing while the new section is built. Our <a href="/insights/small-cip-plant-guide">small CIP and CIL plant guide</a> and the <a href="/equipment/cil-cip-plant">CIL and CIP plant page</a> explain the circuit in more detail.</p>
<h2 id="mercury">Consider a mercury-free route as a complete circuit</h2>
<p>The <a href="https://www.epa.gov/international-cooperation/artisanal-and-small-scale-gold-mining-without-mercury">US EPA overview of mercury-free methods</a> describes concentration and other recovery options. A concentrator purchase should be paired with a tested cleanup and final-product route. Old residues with mercury need separate assessment before reprocessing.</p>
<p>For any cyanide option, use specialist design, training and project-specific controls. The <a href="https://cyanidecode.org/about-the-cyanide-code/the-cyanide-code/">Cyanide Code</a> provides a management framework; this comparison is not a chemical operating recipe.</p>
${renderArticleFaqs("gravity-vs-cyanide-gold-recovery", "en")}
<h2 id="conclusion">Choose by incremental recoverable value</h2>
<p>Test gravity and downstream recovery on representative material, reconcile the gold balance and compare the full cost of each viable option. The route that suits your project is the one supported by both process evidence and an operable budget. Start by preparing sample locations, feed quantities and the question the test programme must answer.</p>
<h2 id="basis">Sources and example basis</h2>
<p>References were reviewed on 5 October 2026; the upgrade section was added on 7 October 2026. The combined-recovery example uses assumed values and is not a performance claim for Bart Mining equipment.</p>`
export default content
