import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>A junior explorer needs each programme to answer a geological question while preserving enough cash to act on the result. Outsourcing can provide field capacity, but it does not remove the company’s responsibility for data quality, spending decisions or public disclosure. The programme should leave evidence that another technical team can assess.</p>
<p>This guide explains how to scope external support, organise the data and set review points between reconnaissance and resource work. The practical outcome is a programme with clear deliverables and a decision gate, rather than a contractor instructed simply to “find more ore.”</p>
<h2 id="decision">Begin with the next decision</h2>
<p>Identify whether you need to rank targets, test continuity, establish metallurgy or improve confidence for a resource estimate. Each purpose implies a different sample, drilling and review programme. A campaign aimed at discovery should not be presented as though it automatically delivers the information needed for mine design.</p>
<p>Write the technical hypothesis and the evidence that would support or weaken it. For an illustrative vein target, the question might be whether mapped mineralisation continues beneath cover. The resulting programme should test geometry and continuity, rather than only collecting additional high-grade surface samples.</p>
<h2 id="contractors">Give contractors deliverables you can check</h2>
<p>Separate geology, drilling, laboratories and environmental or community work into defined scopes, with someone responsible for coordinating them. Agree data formats, sample custody, daily reporting, change control and who can approve additional expenditure. A cheap drilling rate is difficult to evaluate if the sampling and survey work are excluded.</p>
<p>Ask for staff experience relevant to the deposit and work involved. Where a public-reporting signatory is required, identify the person and applicable qualification separately. A consultancy’s general experience does not establish that a particular person can sign every type of report.</p>
<h2 id="database">Keep a database that survives a handover</h2>
<p>Maintain original collar, downhole-survey, geology, sample and assay records, with unique identifiers and a documented coordinate system. Retain laboratory certificates and corrections rather than replacing the original values without a trail. Backups need a tested restore procedure and clear access ownership.</p>
<p>Prepare QA/QC rules before results arrive and document how failures are investigated. Software does not validate the geological meaning of an interval or repair an incorrectly located hole. Agree who reviews the data and when results may be used in interpretation.</p>
<h2 id="disclosure">Arrange the reporting responsibility early</h2>
<p>The <a href="https://www.jorc.org/docs/JORC_code_2012.pdf">JORC Code</a> requires relevant competence and accountable documentation for public reporting under that framework. Projects reporting in another jurisdiction should confirm that jurisdiction’s rules, including any Qualified Person requirements. Do not treat JORC and NI 43-101 as interchangeable badges.</p>
<p><a href="https://www.asx.com.au/about/regulation/rules-guidance-notes-and-waivers/asx-listing-rules-guidance-notes-and-waivers">ASX listing rules and guidance</a> are a separate reference for ASX issuers. Involve the appropriate reporting adviser before a campaign whose results will be announced publicly, so material context and limitations are collected as the work proceeds.</p>
<h2 id="review-gates">Use review gates to protect the budget</h2>
<p>For the hypothetical covered-vein target, complete the map and initial samples, review their reliability, then decide whether the geometry justifies drilling. After the first drilling stage, update the model before committing the next stage. Define what would trigger further work, redesign or stopping.</p>
<p>Budget for sample preparation, surveys, supervision, interpretation and reporting alongside field metres. Keep contingency for uncertainty and identify delays that could affect the company’s cash runway. An aggressive campaign that produces unusable data spends money without moving the decision forward.</p>
${renderArticleFaqs("junior-mining-company", "en")}
<h2 id="conclusion">Buy evidence for a defined decision</h2>
<p>Organise outsourced work around a clear technical question, controlled data and reviewable deliverables. Confirm public-reporting responsibilities and retain enough budget to respond to what the programme discovers. Before tendering, prepare a short brief stating the target hypothesis, required evidence and next decision gate.</p>
<h2 id="basis">Sources and example basis</h2>
<p>The reporting resources were reviewed on 5 October 2026. The vein-target sequence is illustrative and does not describe a Bart Mining discovery or claim reporting credentials for any member of staff.</p>`
export default content
