import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Battery minerals have brought a new kind of project to East Africa. In Tanzania, the Kabanga nickel project plans to mine nickel sulphide ore in Kagera and refine it at Kahama, and exploration companies are testing lithium-bearing pegmatites across the region. For a junior company or licence holder with a lithium or nickel prospect, the processing route shapes what the deposit is worth long before any plant is built, because it decides the product that can be sold and the tests needed to prove it.</p>
<p>This guide gives an overview of how hard-rock lithium and nickel sulphide ores are processed, what products they make and what an early-stage project should test and budget for. A worked example shows how ore grade and recovery set the mass of lithium concentrate. It is an overview for planning, not a process design.</p>
<h2 id="lithium-spodumene">Hard-rock lithium: concentrating spodumene</h2>
<p>Most hard-rock lithium comes from spodumene, a lithium-bearing mineral in pegmatite. Mines usually sell a spodumene concentrate, with an approximate target grade of 6% lithium oxide (Li₂O), to refiners that convert it into lithium chemicals. Two concentration methods are used, alone or together. Dense media separation (DMS) separates crushed ore in a heavy liquid medium and works when spodumene is released at a coarse size; it rejects much of the waste before any fine grinding. Flotation is used when the spodumene is only released at finer sizes, typically with fatty acid collectors after scrubbing and desliming, because fine slimes interfere with flotation.</p>
<p>Iron contamination matters to buyers, so circuits often include <a href="/equipment/magnetic-separator">magnetic separation</a> to remove iron-bearing minerals and steel wear from the concentrate. Mica and feldspar may also be floated off separately. The test programme decides which combination the ore needs.</p>
<h2 id="nickel-sulphide">Nickel sulphide: concentrate and refining</h2>
<p>Nickel sulphide ore is usually crushed, ground and concentrated by <a href="/equipment/flotation-cell">flotation</a> into a nickel concentrate, which also carries copper and cobalt. The concentrate is then smelted or treated by hydrometallurgy to produce refined metal or intermediate products. Kabanga illustrates the route: ore from the mine in Ngara district is to be concentrated and the concentrate refined at a hydrometallurgical refinery at Kahama to produce nickel, copper and cobalt. The project is planned at 3.4 million tonnes of ore a year with capital costs of about USD 942 million.</p>
<p>For a junior, the key point is that nickel is valued through its concentrate and refining terms. Mineralogy that shows how the nickel occurs, and how much reports to a flotation concentrate, is as important as the drill-hole grade.</p>
<h2 id="worked-example">How grade and recovery set concentrate mass</h2>
<p>The concentrate a lithium operation produces follows from the ore grade, the recovery and the concentrate grade. As a worked assumption, ore grading 1.3% Li₂O, with 70% of the lithium recovered into a 6% Li₂O concentrate, gives a concentrate mass of 1.3 × 0.70 ÷ 6 = about 15% of the ore. Every 1,000 tonnes of ore would then make about 152 tonnes of concentrate.</p>
<p>That ratio drives the economics: it sets how much ore must be mined and processed for each tonne sold and how much transport the product needs. Replace the assumed grade and recovery with your own assays and test results; recovery in particular varies widely with how the spodumene occurs.</p>
<h2 id="exploration-checklist">What an early-stage project should do</h2>
<ol>
<li>Drill enough to define the mineralised zones, keeping core or <a href="/equipment/rc-drilling-rig">RC samples</a> for both assay and metallurgy. Our <a href="/insights/assay-laboratory-tanzania">assay laboratory guide</a> covers sample handling and quality checks.</li>
<li>Run mineralogy to identify the lithium or nickel minerals, their grain size and what they are attached to.</li>
<li>Commission staged test work: heavy-liquid and DMS tests and flotation for lithium; flotation and concentrate analysis for nickel. See our <a href="/insights/plant-test-work-guide">test-work guide</a>.</li>
<li>Ask potential buyers for concentrate specifications, including penalty elements such as iron in spodumene concentrate.</li>
<li>Plan power, water and tailings early; both routes need continuous power and produce large tailings volumes.</li>
</ol>
${renderArticleFaqs("lithium-nickel-processing-guide", "en")}
<h2 id="conclusion">Prove the product before the plant</h2>
<p>A lithium or nickel deposit is valued through the concentrate it can produce and the terms a buyer will offer. For spodumene that means testing whether DMS, flotation or both can reach about 6% Li₂O with low iron; for nickel sulphide it means proving a flotation concentrate and a refining route. Build the drilling, mineralogy and test programme around those products, and size equipment only once the results are in.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Spodumene concentration methods and the 6% Li₂O target follow <a href="https://www.911metallurgist.com/blog/froth-flotation-spodumene-processing-lithium-extraction">911 Metallurgist’s overview of spodumene flotation</a> and published project disclosures. Kabanga figures are from <a href="https://www.tanzaniainvest.com/mining/kabanga-nickel-project-implementation">TanzaniaInvest (June 2026)</a>. Sources were reviewed on 7 October 2026. The concentrate example uses an assumed grade and recovery to show the calculation and is not a result for any deposit.</p>`
export default content
