import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Heavy minerals such as ilmenite, rutile, zircon, monazite and magnetite are found in beach and river sands and in the concentrates that gold miners produce every day. Separating them uses two physical properties: density and magnetism. Gravity equipment sorts particles by how heavy they are, and magnetic separators sort them by how strongly a magnet attracts them. Most heavy-mineral operations need both, in the right order, and the choice of equipment depends on which minerals are present.</p>
<p>This guide explains how gravity and magnetic separation differ, how they work together in a mineral sands flowsheet and how a gold operation can use a magnet to clean its black-sand concentrate. A worked example shows how removing magnetite reduces the concentrate a gold miner has to smelt.</p>
<h2 id="gravity">Gravity separation sorts by density</h2>
<p>Gravity equipment separates particles that differ in density. Spiral concentrators, <a href="/equipment/shaking-table-gold">shaking tables</a>, jigs and <a href="/equipment/centrifugal-gold-concentrator">centrifugal concentrators</a> all let heavy particles settle while lighter quartz and clay are washed away. In mineral sands, wet gravity spirals usually come first, turning a large tonnage of sand into a much smaller heavy mineral concentrate that contains all the heavy minerals together.</p>
<p>Gravity cannot separate heavy minerals from each other when their densities are similar. Ilmenite, rutile and zircon are all heavy, so once they are concentrated together, another property is needed to split them.</p>
<h2 id="magnetic">Magnetic separation sorts by magnetic response</h2>
<p>A <a href="/equipment/magnetic-separator">magnetic separator</a> exploits differences in magnetic susceptibility. Strongly magnetic minerals such as magnetite are removed with low-intensity drum separators. Weakly magnetic minerals such as ilmenite, garnet and monazite need high-intensity separators, which develop roughly 7,000–20,000 gauss. Non-magnetic minerals such as rutile and zircon pass through. In mineral sands plants, magnetic separation is often combined with electrostatic separation, which splits minerals by how well they conduct electricity, to produce separate ilmenite, rutile and zircon products.</p>
<h2 id="mineral-sands">How they work together in mineral sands</h2>
<p>A typical mineral sands route runs in two parts. A wet plant at the deposit uses gravity spirals to make a heavy mineral concentrate. A mineral separation plant then dries that concentrate and splits it with magnetic and electrostatic separators, sometimes with further gravity cleaning. The order matters: gravity removes the bulk of the light sand cheaply, and the magnetic and electrostatic steps then separate minerals that gravity cannot.</p>
<p>Tanzania has projects of this kind. In March 2024 a mineral sands mining licence was granted for a project in Handeni District, Tanga Region, reported to contain 268 million tonnes of heavy mineral sands, including 74 million tonnes of proven reserves (<a href="https://www.tanzaniainvest.com/mining/licenses-mineral-sands-mining-handeni-metal-refining-kahama">TanzaniaInvest</a>).</p>
<h2 id="gold-black-sand">Cleaning gold concentrate with a magnet</h2>
<p>Gold miners meet the same minerals in their sluice and concentrator products as black sand. Magnetite in that concentrate adds weight, slows table cleaning and increases the flux needed to smelt it. Because gold is not magnetic, a magnet removes magnetite and leaves the gold behind. On a small scale a hand magnet or small drum is enough; larger operations use a low-intensity drum separator on the concentrate before the shaking table.</p>
<p>As a worked assumption, suppose a day’s gravity concentrate weighs 50 kg and 60% of it is magnetite. Removing the magnetite leaves 50 × (1 − 0.60) = 20 kg to clean on the table and smelt. Check the magnetic fraction regularly with a pan or assay, because gold can be trapped in wet clumps that the magnet lifts.</p>
<h2 id="next-steps">Tests to commission</h2>
<ol>
<li>Mineralogy of a representative sample or concentrate, showing which heavy minerals are present and in what proportions.</li>
<li>A heavy-liquid or gravity test to measure how much heavy mineral concentrate the material yields.</li>
<li>Magnetic susceptibility testing at several field strengths, and electrostatic tests where rutile and zircon matter.</li>
<li>For gold concentrates, a simple magnetic split with assays of both fractions to confirm no gold is lost.</li>
</ol>
${renderArticleFaqs("magnetic-vs-gravity-separation", "en")}
<h2 id="conclusion">Use density first, then magnetism</h2>
<p>Gravity and magnetic separation answer different questions. Gravity concentrates the heavy minerals and removes the light waste; magnetic separation, often with electrostatic separation, splits the heavy minerals from each other. For mineral sands that means a staged flowsheet designed from mineralogy and tests; for a gold operation it can be as simple as a magnet on the concentrate. Start with mineralogy and a magnetic susceptibility test on your material.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Magnetic separator field ranges follow <a href="https://www.911metallurgist.com/blog/fundamentals-high-intensity-magnetic-separation-industrial-minerals/">911 Metallurgist on high-intensity separation</a> and <a href="https://www.911metallurgist.com/blog/wet-magnetic-separation/">wet magnetic separation</a>. The Handeni project figures are from <a href="https://www.tanzaniainvest.com/mining/licenses-mineral-sands-mining-handeni-metal-refining-kahama">TanzaniaInvest (March 2024)</a>. Sources were reviewed on 7 October 2026. The black-sand example uses an assumed magnetite share to show the calculation.</p>`
export default content
