const content = `<p>Moving away from mercury requires a recovery route that operators can run and measure. For suitable gold feed, gravity concentration can be part of that route, but buying a bowl or table does not by itself establish the final recovery or product quality. Preparation, cleanup, operator practice and a safe final-product route all matter.</p>
<p>This guide helps a small mine plan and assess a mercury-free trial. It focuses on the evidence needed to select equipment and compare performance, rather than promising that every ore will reach a fixed recovery when mercury is removed.</p>
<h2 id="starting-point">Understand the current process and residues</h2>
<p>Record feed source, tonnage, preparation and how gold reaches the current product. Sample the feed and residues through a designed programme. If the site has used mercury, assess contaminated equipment, stockpiles and tailings separately; a new concentrator does not remove the existing contamination.</p>
<p>The <a href="https://www.epa.gov/international-cooperation/artisanal-and-small-scale-gold-mining-without-mercury">US EPA overview</a> describes mercury-free concentration and recovery methods and their dependence on feed characteristics. Use it to understand options, then test the specific material with a competent laboratory or process specialist.</p>
<h2 id="preparation">Prepare the gold for the selected separator</h2>
<p>Alluvial material may need washing and classification. Hard-rock material may need crushing and grinding to expose gold. Different particles then behave differently in a sluice, centrifugal concentrator or shaking table. Selection should consider the size distribution and mineral associations rather than the feed tonnage alone.</p>
<p><a href="https://www.sgs.com/en/-/media/sgscorp/documents/corporate/brochures/sgs-min-wa012-gravity-separation-en-11.cdn.en.pdf">SGS’s gravity guidance</a> explains the importance of particle-size preparation. Ask for tests that reflect your proposed circuit and report both concentrate and tailings; a photograph of visible gold in a pan is not a mass balance.</p>
<h2 id="product-route">Plan how the concentrate becomes a product</h2>
<p>A gravity concentrate contains other dense minerals as well as gold. It may need further cleaning, specialist treatment or a suitable refinery arrangement. Test whether direct smelting is appropriate for the actual concentrate and identify required facilities and controls. Do not describe all concentrates as immediately ready to smelt.</p>
<p>Keep concentrate handling secure and recorded. Agree custody, sampling, assay and settlement terms with any external processor. Gold present in concentrate is inventory until the complete route has recovered and settled it.</p>
<h2 id="trial-example">Measure a trial with a gold balance</h2>
<p>For an illustrative trial, assume 10 dry t of feed at 2 g/t contains 20 g of gold. If the final recovered product contains 12 g, recovery is 12 / 20 = 60%. The remaining 8 g must be considered in tailings, intermediate inventories and measurement uncertainty. These assumed results are not a prediction for any machine.</p>
<p>Compare alternatives on representative feed using documented masses, assays and operating conditions. If a trial changes both grind size and separator, recognise that the result does not isolate the separator’s effect. Include water, energy, wear parts and labour in the comparison.</p>
<h2 id="implementation">Make the change manageable</h2>
<ol><li>Establish a documented baseline and assess any legacy mercury contamination.</li><li>Trial preparation, separation and concentrate treatment on representative material.</li><li>Review the gold balance and operating cost with the process specialist.</li><li>Specify the complete circuit, utilities, residue handling and approvals.</li><li>Train operators and repeat the measurement during commissioning and routine operation.</li></ol>
<p>If tests suggest additional treatment of gravity tailings, evaluate it as a separate investment. <a href="/insights/gravity-vs-cyanide-gold-recovery">Gravity and leaching</a> can complement each other, but hazardous chemical treatment requires its own design and operating capability.</p>
<h2 id="conclusion">Replace mercury with a tested recovery system</h2>
<p>Select a complete route from prepared feed to final product and verify it with a reconciled trial. Budget for cleanup, training and legacy contamination as well as the separator. Begin by mapping the current process and arranging representative samples so the change has a measurable technical and operating basis.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Technical references were reviewed on 5 October 2026. Trial figures are hypothetical. The guide does not claim current national mercury-use statistics or offer an exposure-treatment or chemical-handling procedure.</p>`
export default content
