const content = `<p>A mineral survey in Kenya should begin with a target and a decision, rather than a request to scan a large area for any valuable mineral. Gold, heavy mineral sands and industrial minerals require different evidence. Selecting the wrong survey can produce data that looks detailed while leaving the commercial question unanswered.</p>
<p>This guide explains how to scope that work, use regional information and request deliverables that can guide sampling or drilling. It also separates historical operating examples from current project opportunities.</p>
<h2 id="context">Read regional context with its date</h2>
<p><a href="https://www.usgs.gov/centers/national-minerals-information-center/kenya">USGS’s Kenya industry page</a> records gold, industrial minerals and titanium-mineral production. It also reports that mining at Kwale ended in December 2024 after ore-reserve depletion. The previous operation is therefore an industry reference, not a current operating example or proof of an available neighbouring deposit.</p>
<p>Compile maps, historical reports, rights and access information for the actual property. Regional mineral occurrence identifies a question to investigate; it does not establish grade or a product market.</p>
<h2 id="target-types">Choose measurements for the mineral system</h2>
<p>A gold target may need structural mapping, systematic geochemistry and drilling to test continuity. A heavy-mineral-sands target needs sediment sampling and mineral composition, together with geometry and recovery evidence. An industrial-mineral target needs chemistry and physical properties matched to a buyer’s specification.</p>
<p>Geophysics can support those models when a relevant contrast exists. <a href="https://www.usgs.gov/special-topics/earth-mri/geophysical-mapping">USGS’s method overview</a> explains the role of physical measurements. No instrument should be marketed as directly establishing every mineral or its grade beneath the licence.</p>
<h2 id="survey-design">Specify coverage and field checks</h2>
<p>Provide the boundary, coordinate system, target model, existing data and access constraints. Have the geologist or geophysicist propose coverage that can answer the question. Agree observations, sampling, QA/QC and the follow-up needed to distinguish an anomaly from another cause.</p>
<p>For an illustrative sampling plan, five traverses with ten planned stations each give 50 stations before controls and replacements. The number is a tender quantity, not evidence that the spacing is adequate. Coverage must follow the target geometry and variability.</p>
<h2 id="product-example">Distinguish mineral content from saleable output</h2>
<p>Suppose an assumed 1,000 t sand sample contains 5% heavy minerals, or 50 t. That is not automatically 50 t of saleable titanium concentrate: the heavy fraction may contain several minerals and recovery and specification still need testing. Report the component mineralogy and process results before valuing a product.</p>
<p>The same principle applies to industrial material. An occurrence may be technically real but unsuitable for a particular customer’s purity, particle size or strength requirement. Start the product discussion before treating all mapped material as revenue.</p>
<h2 id="handover">Request evidence and a ranked next programme</h2>
<p>Require original located observations, sample records, laboratory results, raw survey data where relevant and interpretations with limitations. The report should rank targets and explain which direct test is justified next. Keep editable spatial files alongside the PDF.</p>
<p>Have local advisers confirm the current mineral right, permitted survey activities, environmental requirements and sample movement arrangements. The technical contractor’s mobilisation plan is not itself evidence of those permissions.</p>
<h2 id="conclusion">Survey for the target and product decision</h2>
<p>Select methods from the mineral system, retain the underlying evidence and use results to scope a direct next test. Keep historical context separate from present opportunity and mineral content separate from a saleable product. Begin with a target brief, existing-data inventory and the intended customer or development question.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>USGS resources were reviewed on 5 October 2026. Sample counts and heavy-mineral quantities are illustrative. No current licence availability or project grade is asserted.</p>`
export default content
