import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>When a shaft goes deeper or production increases, the hoisting system usually becomes the limit on how much ore reaches surface. Choosing a winch by its headline rating alone often leads to a machine that is too small for the real load, too slow for the daily tonnage or unsafe on a headframe that was never designed for it. Sizing the system properly means working out the heaviest load on the rope, the number of trips needed each day and the structure that carries the rope over the shaft.</p>
<p>This guide takes you through those calculations for a small-scale gold shaft, with a worked example for a 100-metre shaft. It explains how load, rope, speed, sheave and headframe fit together, and what information a supplier and a structural engineer need before they can quote or design. It does not replace the certification that a permanent hoisting installation requires.</p>
<h2 id="suspended-load">Start with the heaviest load on the rope</h2>
<p>A winch’s rated line pull is quoted on the first layer of rope on the drum. The load it must handle is everything hanging below the drum at the heaviest moment of the trip: the bucket, kibble or skip, the ore it carries, any attachments and the rope itself from the drum to the bottom of the shaft. Rope weight is easy to forget on a shallow shaft but significant on a deep one, so take the mass per metre from the rope supplier and multiply it by the full hoisting length.</p>
<p>The rope must then be strong enough with a margin. Goods hoisting is commonly designed to a safety factor of at least 5:1 against the rope’s minimum breaking load, and hoisting people requires a much higher factor, typically 8:1 or more under the applicable regulation. Our <a href="/equipment/wire-rope-slings-lifting-tackle">wire rope page</a> explains rope construction and the ISO 4309 discard criteria that decide when a rope must be replaced.</p>
<h2 id="trips-per-day">Work out the trips needed for your tonnage</h2>
<p>Hoisting capacity depends on how much each trip carries and how long each trip takes. A full cycle includes winding up, tipping at the bank, lowering the empty conveyance and loading at the bottom. Line speed sets the winding time, so a deeper shaft or a slower winch reduces the trips available in a shift.</p>
<p>As a worked assumption, consider a 100-metre shaft with a winch that winds at 10 metres per minute. Winding up takes 10 minutes and lowering another 10, and loading and tipping add an assumed 4 minutes, so one cycle takes 24 minutes. Over 20 hoisting hours that gives 50 trips. If each trip carries 600 kg of ore, the shaft can deliver about 30 tonnes a day. If the plant needs 40 tonnes, the options are a larger conveyance, a faster winch, longer hoisting hours or a second compartment; each option changes the load or the equipment, so recalculate the suspended load after any change.</p>
<h2 id="choosing-winch">Match the winch to the load and depth</h2>
<p>With the heaviest suspended load and the required speed known, choose a winch whose rating leaves a margin when the drum is nearly full, because pull falls as rope builds up in layers. The drum must also hold the full rope length with the turns required at the bottom. As a general guide from our catalogue, a <a href="/equipment/1-ton-winch">1 tonne winch</a> suits shafts up to about 60 metres, a <a href="/equipment/2-ton-winch">2 tonne winch</a> about 60–120 metres and a <a href="/equipment/5-ton-mine-winch">5 tonne winch</a> permanent production hoisting on shafts of about 120–300 metres. A production winch should have two independent brakes, overwind protection and depth indication.</p>
<h2 id="headframe">Design the headframe and sheave around the rope</h2>
<p>The <a href="/equipment/mine-hoist-headframe">headframe</a> carries the sheave wheel over the shaft and transfers the rope loads to its foundations. Small-scale steel headframes are typically 8–18 metres high. The height must leave room for the conveyance to tip at the bank and for an overwind clearance above it, so that a conveyance that travels past its stopping point is caught before it reaches the sheave.</p>
<p>The sheave must be large enough for the rope. A sheave diameter of at least 60 times the rope diameter limits the bending fatigue that would otherwise shorten rope life. For a 12 mm rope that means a sheave of at least 720 mm. The rope’s angle from the drum to the sheave, its alignment and the loads on the structure all need checking by a structural engineer, who designs the headframe and its foundations for the actual rope loads, including the emergency braking load.</p>
<h2 id="certification">Plan inspection and certification</h2>
<p>A permanent hoisting installation is subject to occupational safety regulation and periodic examination by a competent person, with records retained. Requirements differ for goods-only hoisting and for hoisting people. Confirm the current obligations for your licence with the <a href="https://www.tumemadini.go.tz/">Mining Commission</a> and <a href="https://www.osha.go.tz/">OSHA Tanzania</a> before commissioning, and build the daily rope and brake checks into the operating routine from the first shift.</p>
<h2 id="next-steps">Information to prepare for a quotation</h2>
<ol>
<li>Shaft depth now and the depth planned over the next few years.</li>
<li>Conveyance type and empty weight, and the ore load per trip.</li>
<li>Tonnes per day required and hoisting hours per day.</li>
<li>Whether the system will ever carry people.</li>
<li>Power supply available at the shaft, and any existing headframe drawings.</li>
</ol>
${renderArticleFaqs("mine-winch-headframe-sizing", "en")}
<h2 id="conclusion">Size the system from load, trips and structure</h2>
<p>A hoisting system is sized correctly when the winch handles the heaviest suspended load with a margin on a full drum, completes enough trips for the plant’s daily tonnage and runs over a sheave and headframe designed for its rope and braking loads. Work through the load and trip calculation first, then ask the supplier and a structural engineer to confirm the winch, rope, sheave and headframe together. Start by measuring your conveyance, its load and your shaft depth.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Winch capacities, rope safety factors, headframe heights and the sheave-to-rope ratio match our equipment pages for the <a href="/equipment/1-ton-winch">1</a>, <a href="/equipment/2-ton-winch">2</a> and <a href="/equipment/5-ton-mine-winch">5 tonne winches</a>, the <a href="/equipment/mine-hoist-headframe">headframe</a> and <a href="/equipment/wire-rope-slings-lifting-tackle">wire rope</a>, reviewed on 7 October 2026. Rope discard follows ISO 4309. The 100-metre example uses assumed speeds, times and loads to show the calculation and is not a design for any shaft.</p>`
export default content
