import { CHUNYA_EXAMPLES, HARD_ROCK_EXAMPLES, MONTHLY_OPERATING_EXAMPLES, totalCost, usd } from '@/data/plant-cost-examples'

const [wash, starter, full] = CHUNYA_EXAMPLES
const [gravity, cil] = HARD_ROCK_EXAMPLES
const projectTotal = (p: typeof gravity | typeof cil) => p.equipment + p.delivery + p.civilsUtilities + p.engineeringStartup + p.contingency + p.workingCapital
const operatingRows = MONTHLY_OPERATING_EXAMPLES.map((p, i) => `<tr><th scope="row">${['Alluvial washing and sluices', 'Hard-rock gravity', 'Hard-rock with CIL'][i]}</th><td>${p.throughput.toLocaleString('en-US')} ${p.unit}/month</td><td>${usd(totalCost(p.costs))}</td><td>${usd(totalCost(p.costs) * 2)}</td><td>USD ${(totalCost(p.costs) / p.throughput).toFixed(2)}/${p.unit}</td></tr>`).join('')

const content = `
<p>If you are planning a gold plant in Tanzania, the first useful number is the money needed to reach production. That includes the right equipment for your deposit, delivery to site, construction, water and power, commissioning, and enough cash to operate while production settles. The price of a crusher or a washing screen covers only part of that investment.</p>
<p>This guide compares an alluvial wash plant, a hard-rock plant with crushers and a ball mill, and a hard-rock plant with leaching. We start with client-facing figures from Bart Mining’s Chunya proposals, then use separate worked assumptions to show how hard-rock budgets and monthly operating costs can be built. By the end, you should know which plant to investigate, what your budget must cover and what information is needed for a quotation.</p>

<h2 id="choose-the-plant">Choose the process before comparing prices</h2>
<p>Alluvial gold occurs in loose gravel or sand. Where the gold is already liberated, washing and screening prepare it for gravity recovery through sluices, jigs or centrifugal concentrators. Clay can change this arrangement: a simple washing screen may not break it down sufficiently, so a rotary scrubber and a more developed recovery circuit may be needed. A conventional alluvial circuit does not need a ball mill just because the project produces gold. <a href="https://www.jxscmachine.com/gold-mining-equipment-for-sale/">JXSC’s processing examples</a> show how washing and hard-rock circuits differ.</p>
<p>Hard-rock ore needs crushing and grinding to release the gold. A typical circuit feeds a jaw crusher, a ball mill and a classification stage before gravity recovery. Test work establishes how much gold this circuit can recover and how fine the ore must be ground. If a worthwhile share remains and leach tests support it, CIL or CIP may be added. Gold locked within difficult minerals can require further treatment; buying leach tanks alone does not solve that problem.</p>
<figure><ol class="process-flow" aria-label="Typical alluvial process"><li>Gravel feed</li><li>Washing / scrubbing</li><li>Screening</li><li>Gravity recovery</li><li>Concentrate cleanup</li></ol><figcaption>Alluvial process concept. Water returns through a settling and recycling system; the final arrangement depends on clay and gold size.</figcaption></figure>
<figure><ol class="process-flow" aria-label="Typical hard-rock process"><li>Ore feed</li><li>Crushing</li><li>Ball milling and classification</li><li>Gravity recovery</li><li>Optional tested leach circuit</li></ol><figcaption>Hard-rock process concept. Crushing and grinding introduce equipment, power and wear costs that a loose-gravel wash plant may avoid.</figcaption></figure>

<h2 id="chunya-costs">What the Chunya proposals show about alluvial plant costs</h2>
<p>Our 5 October 2026 Phase 1 proposal describes a 150 m³/h washing-and-sluice plant. It includes a double-deck washing screen, six sluice boxes, gold mats, a water pump, hoses, a control cabinet and the generator in the priced configuration. Its equipment package is ${usd(wash.equipment)}. With the proposal’s estimated execution services, the total becomes approximately <strong>${usd(wash.total)}</strong>, before separately payable import VAT, other statutory charges and the owner’s operating capital.</p>
<p>The earlier 3 October proposal compares scrubber plants with centrifugal concentrators and concentrate cleanup. These are different recovery circuits with larger site-work and delivery allowances. Their prices help explain the effect of scope; they are not interchangeable quotations for the same plant.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Cost table; scroll horizontally to see all columns"><p class="article-table-caption">Client-facing Chunya proposal examples, rounded USD; execution remains estimated.</p><table aria-label="Client-facing Chunya proposal examples, rounded USD; execution remains estimated."><thead><tr><th scope="col">Plant configuration</th><th scope="col">Nominal feed capacity</th><th scope="col">Equipment</th><th scope="col">Execution services</th><th scope="col">Equipment + execution</th></tr></thead><tbody>
<tr><th scope="row">Washing screen + six sluices</th><td>150 m³/h</td><td>${usd(wash.equipment)}</td><td>${usd(wash.execution)}</td><td>${usd(wash.total)}</td></tr>
<tr><th scope="row">Scrubber + gravity recovery, starter</th><td>75 m³/h</td><td>${usd(starter.equipment)}</td><td>${usd(starter.execution)}</td><td>${usd(starter.total)}</td></tr>
<tr><th scope="row">Scrubber + gravity recovery, larger</th><td>150 m³/h</td><td>${usd(full.equipment)}</td><td>${usd(full.execution)}</td><td>${usd(full.total)}</td></tr>
</tbody></table></div>
<p>The proposals treat import VAT and statutory charges as client responsibilities and assume an import-duty position that must be confirmed for the actual goods and importer. They also require site access, a water source, approvals and a representative bulk sample. Feed excavation and haulage, land or licence acquisition, and routine production costs need their own budgets. These figures describe proposed scope, rather than a completed plant’s measured cost or a universal price list.</p>
<p>Capacity also needs careful comparison. Alluvial plant feed is expressed here in cubic metres per hour; hard-rock plants below use tonnes per day. Converting between them requires measured bulk density, operating hours and availability. Fine-gold recovery and clay handling can justify a different circuit even at the same nominal feed rate.</p>
<figure><img src="/equipment/rotary-scrubber.jpeg" alt="Rotary scrubber shown in the Bart Mining equipment catalogue" width="1200" height="800" loading="lazy" /><figcaption>Equipment reference from our catalogue: a rotary scrubber washes clay-bearing gravel before separation. This is not a photograph of an installed Chunya plant.</figcaption></figure>

<h2 id="hard-rock-budgets">How a crusher-and-ball-mill plant changes the budget</h2>
<p>A hard-rock gravity plant adds a crushing circuit, a ball mill, classification, recovery equipment and the associated pumps and controls. The mill must achieve the required grind on your ore at the planned throughput. A lower machine price is useful only if the equipment can perform that duty with acceptable wear and power consumption.</p>
<p>We do not have a current hard-rock quotation behind this page. The following two examples therefore use <strong>illustrative budgeting assumptions</strong>, not Bart Mining offers or verified market ranges. They show the amount that can sit outside the equipment price and give you a structure to replace with quotations.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Cost table; scroll horizontally to see all columns"><p class="article-table-caption">Worked hard-rock startup budgets, USD. Every amount in this table is assumed.</p><table aria-label="Worked hard-rock startup budgets, USD. Every amount in this table is assumed."><thead><tr><th scope="col">Budget item</th><th scope="col">30 t/day gravity plant</th><th scope="col">50 t/day gravity + CIL plant</th></tr></thead><tbody>
<tr><th scope="row">Equipment allowance</th><td>${usd(gravity.equipment)}</td><td>${usd(cil.equipment)}</td></tr>
<tr><th scope="row">Freight, clearing and inland delivery allowance</th><td>${usd(gravity.delivery)}</td><td>${usd(cil.delivery)}</td></tr>
<tr><th scope="row">Civil works, power, water and tailings infrastructure</th><td>${usd(gravity.civilsUtilities)}</td><td>${usd(cil.civilsUtilities)}</td></tr>
<tr><th scope="row">Testing, engineering, installation and startup</th><td>${usd(gravity.engineeringStartup)}</td><td>${usd(cil.engineeringStartup)}</td></tr>
<tr><th scope="row">Contingency: 10% of the preceding items</th><td>${usd(gravity.contingency)}</td><td>${usd(cil.contingency)}</td></tr>
<tr><th scope="row">Two months of illustrative processing costs</th><td>${usd(gravity.workingCapital)}</td><td>${usd(cil.workingCapital)}</td></tr>
<tr><th scope="row">Illustrative startup funding</th><td><strong>${usd(projectTotal(gravity))}</strong></td><td><strong>${usd(projectTotal(cil))}</strong></td></tr>
</tbody></table></div>
<p>These totals exclude import taxes, land and mineral rights, mine development, the purchase of an excavation or haulage fleet, financing charges and a complete owner’s overhead budget. Tailings and water allowances must be replaced by site engineering; an unusually demanding site can exceed the entire allowance. A CIP arrangement may have different tank and carbon-handling requirements from CIL, so the CIL example cannot price every leaching option.</p>
<figure><img src="/equipment/ball-mill-gold-ore.jpg" alt="Ball mill shown in the Bart Mining gold ore equipment catalogue" width="1200" height="800" loading="lazy" /><figcaption>Equipment reference: a ball mill grinds crushed ore. Its duty must be checked against ore hardness, the target grind and operating hours.</figcaption></figure>

<h2 id="operating-costs">What it costs to keep each plant running</h2>
<p>Operating costs should be modelled separately from construction. An alluvial operation needs money for feeding the plant, diesel or electricity, pumps, operators, cleanup and wear parts. A hard-rock plant adds grinding media and liners. CIL or CIP also adds reagents, carbon management, process control and environmental monitoring. Recovery tests and local supplier quotations are needed to turn these categories into a project forecast.</p>
<p>The table below is a worked comparison. All monthly expenses are assumptions, including the diesel and power prices. It covers the stated processing scope and is not a forecast of Chunya’s actual operating costs.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Cost table; scroll horizontally to see all columns"><p class="article-table-caption">Illustrative monthly processing costs and cash reserve, USD.</p><table aria-label="Illustrative monthly processing costs and cash reserve, USD."><thead><tr><th scope="col">Plant example</th><th scope="col">Assumed monthly feed</th><th scope="col">Monthly cost</th><th scope="col">Two-month reserve</th><th scope="col">Cost per feed unit</th></tr></thead><tbody>${operatingRows}</tbody></table></div>
<p><strong>Alluvial assumptions:</strong> the 150 m³/h washing plant operates for 20 scheduled hours a day, 26 days a month, with 75% productive availability, giving 58,500 m³ of feed. We allow an average 120 kW electrical draw over 520 hours, fuel use of 0.27 litres/kWh and diesel at USD 1.20/litre. That is about USD 20,218 for plant fuel. Feeding and loading add USD 15,000, labour USD 5,000, wear and servicing USD 3,000, and water management, sampling and overhead USD 3,500. The feeding allowance excludes purchase of a mining fleet; the average electrical draw is assumed, not the generator’s 200 kW rating.</p>
<p><strong>Hard-rock gravity assumptions:</strong> 30 t/day for 26 productive days gives 780 tonnes. At an assumed 35 kWh/t and USD 0.30/kWh, power costs USD 8,190. Labour is USD 4,500, media and wear consumables USD 3,900, water and sampling USD 1,560, and maintenance USD 2,340. The total is USD 20,490, or about USD 26.27/t.</p>
<p><strong>CIL assumptions:</strong> 50 t/day for 26 productive days gives 1,300 tonnes. Power at 40 kWh/t and USD 0.30/kWh costs USD 15,600; reagents and carbon add USD 10,400, media and liners USD 6,500, labour USD 8,000, water and laboratory work USD 2,600, and maintenance USD 3,900. The total is USD 47,000, or about USD 36.15/t. This assumes successful steady production; a slow commissioning period needs additional cash.</p>
<p>Mining, ore transport, royalties, refining, financing and taxes must be added where relevant. An alluvial USD/m³ cost cannot be compared directly with a hard-rock USD/t cost. For a revenue model, multiply actual feed by measured grade and tested recovery, then apply the sale price and deductions. Repeat the calculation at lower grade, lower recovery and fewer productive hours before committing capital.</p>

<h2 id="delivered-cost">Check exactly what a delivery quotation covers</h2>
<p>Ask for the named delivery term and a written scope. EXW, FOB and CIF assign different transport responsibilities. Under CIF the seller pays freight and insurance to the named destination port, while transport risk transfers when the goods are placed on board at origin. CIF alone does not include customs clearance, inland delivery or plant installation. <a href="https://academy.iccwbo.org/incoterms/article/place-of-delivery-risk-transfer-global-trade-contracts/">ICC Academy explains the distinction between destination costs and risk transfer</a>.</p>
<p>Have your clearing agent assess the goods using their specifications, invoices, origin and HS codes. Use the <a href="https://www.eac.int/tariffsearch">EAC tariff search</a> and confirm the applicable position with TRA. A mining licence should never be treated as proof that every machine or spare is exempt. Customs estimates belong on their own line, with the tax basis and responsibility stated.</p>
<p>The Chunya washing-and-sluice example budgets approximately ${usd(wash.execution)} beyond equipment. That allowance covers logistics, installation, civil works, engineering, testing, commissioning and contingency. It illustrates why adding one flat percentage to a machine price can miss much of the funding required to start production.</p>

<h2 id="before-ordering">Turn the estimate into a project budget</h2>
<p>Start with a representative feed sample and a site assessment. Establish grade, gold size and recoverability, clay content for gravel, and hardness and grinding requirements for rock. Confirm the water source, pumping distance and elevation, site access, power supply and a feasible tailings arrangement before requesting comparable equipment proposals. Our <a href="/insights/plant-test-work-guide">test-work guide</a> explains how these results shape the plant.</p>
<p>Then request an itemised proposal that separates equipment, delivery, taxes, construction, commissioning and owner responsibilities. Ask how capacity and recovery will be demonstrated on your material, which spares are included, and what changes if the feed differs from the sample. Compare suppliers against the same duty and scope.</p>
<p>Build the schedule alongside the budget. The current Chunya washing proposal models 16 weeks to production; the earlier scrubber options model 24 and 26.5 weeks. These are proposal schedules with dependencies, rather than guaranteed delivery times. Site preparation can run alongside manufacture and shipping, but water, access and approvals must be ready for commissioning.</p>

<h2 id="questions">Questions when budgeting a plant</h2>
<h3>Can I start with washing and sluices, then add recovery equipment?</h3>
<p>That is the approach proposed for the Chunya Phase 1 project. It can make sense where the feed contains recoverable free gold and the initial circuit fits the material. Tests should show what the sluices miss, and the layout should allow a later addition such as centrifugal concentration or concentrate cleanup. Expansion is a separate budget, not a guarantee that the simplest circuit will suit every deposit.</p>
<h3>Does the plant total include an excavator and mine development?</h3>
<p>The Chunya figures on this page cover the stated processing equipment and execution scope. They do not price a complete mining business. Budget excavation, haulage, site ownership or access, mineral rights and operating capital separately.</p>
<h3>Should I convert the USD figures into Tanzanian shillings now?</h3>
<p>For your financing plan, use the exchange rate and bank charges that apply to your expected payment dates. This page keeps the figures in the proposal currency so an assumed exchange rate is not mistaken for a current one.</p>

<h2 id="conclusion">Budget for the route from feed to first production</h2>
<p>For loose alluvial gravel, investigate washing and gravity recovery first. For hard rock, establish the crushing and grinding duty before pricing the plant, then add leaching only where test work and the economics support it. These decisions explain much more about cost than the equipment name alone.</p>
<p>The Chunya proposals provide a practical starting reference: about ${usd(wash.total)} for the washing-and-sluice equipment and estimated execution scope, rising to different budgets for scrubber-based recovery. Your investment decision still needs taxes, owner costs and an operating reserve. Bring your site location, sample results, target feed rate, water and power information to the next discussion so those remaining items can be priced.</p>

<h2 id="basis">Sources and basis of the figures</h2>
<p>The alluvial capital figures are rounded client-facing totals from Bart Mining’s Chunya planning proposals dated 3 and 5 October 2026, recalculated using the Plant Planner’s proposal model. They are preliminary proposed prices and execution allowances, not incurred costs. Supplier costs and internal commercial figures are excluded from this article. The hard-rock startup budgets and every operating-cost example are explicit teaching assumptions, not values taken from those proposals. The manufacturer, ICC and EAC links above support the process and trade explanations; they do not validate the budget assumptions.</p>
`
export default content
