import { renderArticleFaqs } from '@/lib/article-faqs'

import { CHUNYA_EXAMPLES, HARD_ROCK_PLANNING_REFERENCE, MONTHLY_OPERATING_EXAMPLES, totalCost, usd } from '@/data/plant-cost-examples'

const [wash, starter, full] = CHUNYA_EXAMPLES
const hardRock = HARD_ROCK_PLANNING_REFERENCE
const operatingRows = MONTHLY_OPERATING_EXAMPLES.map((p, i) => `<tr><th scope="row">${['Alluvial washing and sluices', 'Hard-rock gravity', 'Hard-rock with CIL'][i]}</th><td>${p.throughput.toLocaleString('en-US')} ${p.unit}/month</td><td>${usd(totalCost(p.costs))}</td><td>${usd(totalCost(p.costs) * 2)}</td><td>USD ${(totalCost(p.costs) / p.throughput).toFixed(2)}/${p.unit}</td></tr>`).join('')

const content = `
<p>If you are planning a gold plant in Tanzania, the first useful number is the money needed to reach production. That includes the right equipment for your deposit, delivery to site, construction, water and power, commissioning, and enough cash to operate while production settles. The price of a crusher or a washing screen covers only part of that investment.</p>
<p>This guide compares an alluvial wash plant, a hard-rock plant with crushers and a ball mill, and a hard-rock plant with leaching. We start with client-facing figures from Bart Mining’s Chunya proposals, then use a preliminary hard-rock equipment and transport reference and separate worked assumptions for monthly operating costs. By the end, you should know which plant to investigate, what your budget must cover and what information is needed for a quotation.</p>

<h2 id="choose-the-plant">Choose the process before comparing prices</h2>
<p>Alluvial gold occurs in loose gravel or sand. Where the gold is already liberated, washing and screening prepare it for gravity recovery through sluices, jigs or centrifugal concentrators. Clay can change this arrangement: a simple washing screen may not break it down sufficiently, so a rotary scrubber and a more developed recovery circuit may be needed. A conventional alluvial circuit does not need a ball mill just because the project produces gold. <a href="https://www.jxscmachine.com/gold-mining-equipment-for-sale/">JXSC’s processing examples</a> show how washing and hard-rock circuits differ.</p>
<p>Hard-rock ore needs crushing and grinding to release the gold. A typical circuit feeds a jaw crusher, a ball mill and a classification stage before gravity recovery. Test work establishes how much gold this circuit can recover and how fine the ore must be ground. If a worthwhile share remains and leach tests support it, CIL or CIP may be added. Gold locked within difficult minerals can require further treatment; buying leach tanks alone does not solve that problem.</p>
<figure><ol class="process-flow" aria-label="Typical alluvial process"><li>Gravel feed</li><li>Washing / scrubbing</li><li>Screening</li><li>Gravity recovery</li><li>Concentrate cleanup</li></ol><figcaption>Alluvial process concept. Water returns through a settling and recycling system; the final arrangement depends on clay and gold size.</figcaption></figure>
<figure><ol class="process-flow" aria-label="Typical hard-rock process"><li>Ore feed</li><li>Crushing</li><li>Ball milling and classification</li><li>Gravity recovery</li><li>Optional tested leach circuit</li></ol><figcaption>Hard-rock process concept. Crushing and grinding introduce equipment, power and wear costs that a loose-gravel wash plant may avoid.</figcaption></figure>

<h2 id="chunya-costs">What the Chunya proposals show about alluvial plant costs</h2>
<p>Our 5 October 2026 Phase 1 proposal describes a 150 m³/h washing-and-sluice plant. It includes a double-deck washing screen, six sluice boxes, gold mats, a water pump, hoses, a control cabinet and the generator in the priced configuration. Its equipment package is ${usd(wash.equipment)}. With the proposal’s estimated execution services, the total becomes approximately <strong>${usd(wash.total)}</strong>, before separately payable import VAT, other statutory charges and the owner’s operating capital.</p>
<p>The earlier 3 October proposal compares scrubber plants with centrifugal concentrators and concentrate cleanup. These are different recovery circuits with larger site-work and delivery allowances. Their prices help explain the effect of scope; they are not interchangeable quotations for the same plant.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Cost table; scroll horizontally to see all columns"><p class="article-table-caption">Client-facing Chunya proposal examples, rounded USD; execution remains estimated.</p><table aria-label="Client-facing Chunya proposal examples, rounded USD; execution remains estimated."><thead><tr><th scope="col">Plant configuration</th><th scope="col">Nominal feed capacity</th><th scope="col">Equipment</th><th scope="col">Execution services</th><th scope="col">Equipment + execution</th></tr></thead><tbody>
<tr><th scope="row">Washing screen + six sluices</th><td>150 m³/h</td><td>${usd(wash.equipment)}</td><td>${usd(wash.execution)}</td><td>${usd(wash.total)}</td></tr>
<tr><th scope="row">Scrubber + gravity recovery, starter</th><td>75 m³/h</td><td>${usd(starter.equipment)}</td><td>${usd(starter.execution)}</td><td>${usd(starter.total)}</td></tr>
<tr><th scope="row">Scrubber + gravity recovery, larger</th><td>150 m³/h</td><td>${usd(full.equipment)}</td><td>${usd(full.execution)}</td><td>${usd(full.total)}</td></tr>
</tbody></table></div>
<p>The proposals treat import VAT and statutory charges as client responsibilities and assume an import-duty position that must be confirmed for the actual goods and importer. They also require site access, a water source, approvals and a representative bulk sample. Feed excavation and haulage, land or licence acquisition, and routine production costs need their own budgets. These figures describe proposed scope, rather than a completed plant’s measured cost or a universal price list.</p>
<p>Capacity also needs careful comparison. Alluvial plant feed is expressed here in cubic metres per hour; the hard-rock operating examples below use tonnes per day. Converting between them requires measured bulk density, operating hours and availability. Fine-gold recovery and clay handling can justify a different circuit even at the same nominal feed rate.</p>
<figure><img src="/equipment/rotary-scrubber.jpeg" alt="Rotary scrubber shown in the Bart Mining equipment catalogue" width="1200" height="800" loading="lazy" /><figcaption>Equipment reference from our catalogue: a rotary scrubber washes clay-bearing gravel before separation. This is not a photograph of an installed Chunya plant.</figcaption></figure>

<h2 id="hard-rock-budgets">How a crusher-and-ball-mill plant changes the budget</h2>
<p>A hard-rock gravity plant adds a crushing circuit, a ball mill, classification, recovery equipment and the associated pumps and controls. The mill must achieve the required grind on your ore at the planned throughput. A lower machine price is useful only if the equipment can perform that duty with acceptable wear and power consumption.</p>
<p>Our preliminary planning reference, discussed on 5 October 2026, is about <strong>${usd(hardRock.equipment)} for a small plant’s equipment package</strong>. Allow ${usd(hardRock.domesticTransport)} for transport within Tanzania, or ${usd(hardRock.internationalTransport)} for an international route as a first planning allowance. These are approximate business estimates awaiting a scoped quotation and transport quote; they are not published market prices or guaranteed delivery ceilings.</p>
<p>Confirm the equipment list and capacity before using that reference. A crusher, mill and gravity-recovery package must not be compared with a leach plant unless tanks, agitation, carbon handling and the route to recovering gold from loaded carbon are explicitly included. Also confirm whether the generator, pumps, controls, initial grinding media and spares are supplied. The reference does not establish a price for a particular 30 t/day or 50 t/day circuit.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Cost table; scroll horizontally to see all columns"><p class="article-table-caption">Preliminary equipment and transport reference, USD. Both columns use the same indicative equipment package; site startup costs are additional.</p><table aria-label="Preliminary equipment and transport reference, USD"><thead><tr><th scope="col">Budget item</th><th scope="col">Transport within Tanzania</th><th scope="col">International transport</th></tr></thead><tbody>
<tr><th scope="row">Indicative equipment package</th><td>${usd(hardRock.equipment)}</td><td>${usd(hardRock.equipment)}</td></tr>
<tr><th scope="row">Transport planning allowance</th><td>${usd(hardRock.domesticTransport)}</td><td>${usd(hardRock.internationalTransport)}</td></tr>
<tr><th scope="row">Equipment + transport subtotal only</th><td><strong>${usd(hardRock.equipment + hardRock.domesticTransport)}</strong></td><td><strong>${usd(hardRock.equipment + hardRock.internationalTransport)}</strong></td></tr>
</tbody></table></div>
<p>The two transport columns are alternatives, not costs to add together. Define the collection point, destination, shipment weight, dimensions and number of loads before requesting a transport quote. Check loading, unloading, insurance, port and clearance charges separately; import taxes and statutory charges are outside these transport allowances unless a written quote includes them.</p>
<p>To turn the subtotal into a startup budget, price foundations, electrical installation, water supply and tailings management from the site layout. Then obtain a scoped allowance for test work, engineering, installation, training and commissioning. Add contingency to the completed budget and reserve operating cash for the planned ramp-up. Unpriced work remains an open budget item rather than an invented fixed amount, so this page does not give a complete hard-rock startup total yet.</p>
<p>A manufacturer’s <a href="https://www.jxscmachine.com/cases/5tph-alluvial-gold-and-1tph-rock-gold-processing-plant-in-niger/">1 t/hour hard-rock example in Niger</a> illustrates a jaw crusher, ball mill, shaking table and supporting equipment. It is a useful scope reference, but it does not publish a package price or verify the ${usd(hardRock.equipment)} estimate.</p>
<figure><img src="/equipment/ball-mill-gold-ore.jpg" alt="Ball mill shown in the Bart Mining gold ore equipment catalogue" width="1200" height="800" loading="lazy" /><figcaption>Equipment reference: a ball mill grinds crushed ore. Its duty must be checked against ore hardness, the target grind and operating hours.</figcaption></figure>

<h2 id="operating-costs">What it costs to keep each plant running</h2>
<p>Operating costs should be modelled separately from construction. An alluvial operation needs money for feeding the plant, diesel or electricity, pumps, operators, cleanup and wear parts. A hard-rock plant adds grinding media and liners. CIL or CIP also adds reagents, carbon management, process control and environmental monitoring. Recovery tests and local supplier quotations are needed to turn these categories into a project forecast.</p>
<p>The table below is a worked comparison. All monthly expenses are assumptions, including the diesel and power prices. It covers the stated processing scope and is not a forecast of Chunya’s actual operating costs. The 30 t/day and 50 t/day scenarios are separate arithmetic examples; they do not establish the capacity or running cost of the preliminary USD 90,000 equipment package.</p>
<div class="tbl" tabindex="0" role="region" aria-label="Cost table; scroll horizontally to see all columns"><p class="article-table-caption">Illustrative monthly processing costs and cash reserve, USD.</p><table aria-label="Illustrative monthly processing costs and cash reserve, USD."><thead><tr><th scope="col">Plant example</th><th scope="col">Assumed monthly feed</th><th scope="col">Monthly cost</th><th scope="col">Two-month reserve</th><th scope="col">Cost per feed unit</th></tr></thead><tbody>${operatingRows}</tbody></table></div>
<p><strong>Alluvial assumptions:</strong> the 150 m³/h washing plant operates for 20 scheduled hours a day, 26 days a month, with 75% productive availability, giving 58,500 m³ of feed. We allow an average 120 kW electrical draw over 520 hours, fuel use of 0.27 litres/kWh and diesel at USD 1.20/litre. That is about USD 20,218 for plant fuel. Feeding and loading add USD 15,000, labour USD 5,000, wear and servicing USD 3,000, and water management, sampling and overhead USD 3,500. The feeding allowance excludes purchase of a mining fleet; the average electrical draw is assumed, not the generator’s 200 kW rating.</p>
<p><strong>Hard-rock gravity assumptions:</strong> 30 t/day for 26 productive days gives 780 tonnes. At an assumed 35 kWh/t and USD 0.30/kWh, power costs USD 8,190. Labour is USD 4,500, media and wear consumables USD 3,900, water and sampling USD 1,560, and maintenance USD 2,340. The total is USD 20,490, or about USD 26.27/t.</p>
<p><strong>CIL assumptions:</strong> 50 t/day for 26 productive days gives 1,300 tonnes. Power at 40 kWh/t and USD 0.30/kWh costs USD 15,600; reagents and carbon add USD 10,400, media and liners USD 6,500, labour USD 8,000, water and laboratory work USD 2,600, and maintenance USD 3,900. The total is USD 47,000, or about USD 36.15/t. This assumes successful steady production; a slow commissioning period needs additional cash.</p>
<p>Mining, ore transport, royalties, refining, financing and taxes must be added where relevant. An alluvial USD/m³ cost cannot be compared directly with a hard-rock USD/t cost. For a revenue model, multiply actual feed by measured grade and tested recovery, then apply the sale price and deductions. Repeat the calculation at lower grade, lower recovery and fewer productive hours before committing capital.</p>

<h2 id="delivered-cost">Check exactly what a delivery quotation covers</h2>
<p>Ask for the named delivery term and a written scope. EXW, FOB and CIF assign different transport responsibilities. Under CIF the seller pays freight and insurance to the named destination port, while transport risk transfers when the goods are placed on board at origin. CIF alone does not include customs clearance, inland delivery or plant installation. <a href="https://academy.iccwbo.org/incoterms/article/place-of-delivery-risk-transfer-global-trade-contracts/">ICC Academy explains the distinction between destination costs and risk transfer</a>.</p>
<p>Have your clearing agent assess the goods using their specifications, invoices, origin and HS codes. Use the <a href="https://www.eac.int/tariffsearch">EAC tariff search</a> and confirm the applicable position with TRA. A mining licence should never be treated as proof that every machine or spare is exempt. Customs estimates belong on their own line, with the tax basis and responsibility stated.</p>
<p>The Chunya washing-and-sluice example budgets approximately ${usd(wash.execution)} beyond equipment. That allowance covers logistics, installation, civil works, engineering, testing, commissioning and contingency. It illustrates why adding one flat percentage to a machine price can miss much of the funding required to start production.</p>

<h2 id="before-ordering">Turn the estimate into a project budget</h2>
<p>Start with a representative feed sample and a site assessment. Establish grade, gold size and recoverability, clay content for gravel, and hardness and grinding requirements for rock. Confirm the water source, pumping distance and elevation, site access, power supply and a feasible tailings arrangement before requesting comparable equipment proposals. Our <a href="/insights/plant-test-work-guide">test-work guide</a> explains how these results shape the plant.</p>
<p>Then request an itemised proposal that separates equipment, delivery, taxes, construction, commissioning and owner responsibilities. Ask how capacity and recovery will be demonstrated on your material, which spares are included, and what changes if the feed differs from the sample. Compare suppliers against the same duty and scope.</p>
<p>Build the schedule alongside the budget. The current Chunya washing proposal models 16 weeks to production; the earlier scrubber options model 24 and 26.5 weeks. These are proposal schedules with dependencies, rather than guaranteed delivery times. Site preparation can run alongside manufacture and shipping, but water, access and approvals must be ready for commissioning.</p>

${renderArticleFaqs("mining-equipment-cost-tanzania", "en", "Questions when budgeting a plant")}
<h2 id="conclusion">Budget for the route from feed to first production</h2>
<p>For loose alluvial gravel, investigate washing and gravity recovery first. For hard rock, establish the crushing and grinding duty before pricing the plant, then add leaching only where test work and the economics support it. These decisions explain much more about cost than the equipment name alone.</p>
<p>The Chunya proposals provide a practical starting reference: about ${usd(wash.total)} for the washing-and-sluice equipment and estimated execution scope, rising to different budgets for scrubber-based recovery. Your investment decision still needs taxes, owner costs and an operating reserve. Bring your site location, sample results, target feed rate, water and power information to the next discussion so those remaining items can be priced.</p>

<h2 id="basis">Sources and basis of the figures</h2>
<p>The alluvial capital figures are rounded client-facing totals from Bart Mining’s Chunya planning proposals dated 3 and 5 October 2026, recalculated using the Plant Planner’s proposal model. They are preliminary proposed prices and execution allowances, not incurred costs. Supplier costs and internal commercial figures are excluded from this article. The hard-rock equipment and transport reference is Bart Mining’s preliminary estimate discussed on 5 October 2026, with package scope and route still to be confirmed. It is not taken from the alluvial proposals. Every operating-cost example uses explicit teaching assumptions. The manufacturer, ICC and EAC links above support the process and trade explanations; they do not validate the budget assumptions.</p>
`
export default content
