import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>A small mine can hold a valid licence and still have gaps in the approvals, operating plans or records needed for its actual activities. Adding a processing plant, entering a technical-support arrangement or opening a new working can change what must be checked. A useful compliance review therefore starts with the mine you operate today, rather than a generic folder of forms.</p>
<p>This 2026 checklist helps a Tanzanian operator prepare an organised review with the Resident Mines Officer and other relevant authorities. It does not claim that every item applies identically to every PML, processing licence or larger mine. The outcome should be a list of confirmed obligations, supporting evidence and actions with named owners.</p>
<h2 id="licence">Begin with the right, area and activity</h2>
<p>Match the licence holder, mineral, coordinates and validity period to the work on site. Check rent receipts, conditions, renewal dates and any approved agreements. A company registration, land arrangement or equipment purchase is not evidence that a mineral right covers the intended operation.</p>
<p>The <a href="https://www.tumemadini.go.tz/pages/licenseservice/">Mining Commission’s licensing guidance</a> distinguishes mining, processing, smelting and refining licences. Use those distinctions to ask whether your proposed activity needs an additional right or approval; do not assume an existing mining licence settles every downstream activity.</p>
<h2 id="plans">Turn the plans into an operating file</h2>
<p>Ask the officer which mining, mine-opening, environmental, community, local-content and technical-support documents apply to your licence and project. Record the required version, approving authority and submission date. Where a plan is required, keep the approved document together with evidence that the site follows it.</p>
<p>A water-management plan, for example, should identify drains, pumps, storage and discharge arrangements that staff can locate. Inspection sheets and monitoring records then show whether those measures work. A document describing a different pit or an earlier plant layout will be difficult to use when an inspector visits.</p>
<h2 id="environment">Review environmental and chemical responsibilities</h2>
<p>Establish the environmental assessment and approval route before committing to construction or a change in process. <a href="https://eia.nemc.or.tz/dev/web/home.eu">NEMC’s project-management system</a> separates project developers from registered environmental experts and supports assessment and audit submissions. Have the appointed expert confirm the route, conditions and reporting schedule for your scope.</p>
<p>If the mine stores or uses process chemicals, include procurement, transport, containment, training and emergency arrangements in the review. The chemical circuit and its waste handling need to appear in the design and approvals; they cannot be treated as an accessory added after commissioning.</p>
<h2 id="site-check">Walk the site against the file</h2>
<p>Review ground conditions, access, machinery guarding, lifting arrangements, electrical distribution, ventilation, water and tailings with the people responsible for them. Ask who can stop work and what triggers that decision. Equipment invoices prove a purchase, while inspection, maintenance and training records demonstrate its management.</p>
<p>Use a simple action register with columns for the issue, required correction, responsible person, due date and evidence of closure. For an illustrative pump defect, the closure evidence might include repair records and a witnessed test, rather than a note saying “pump checked.” Safety-critical findings should be assessed promptly by the responsible competent person.</p>
<h2 id="review-sequence">Prepare for a productive official review</h2>
<ol><li>Make an inventory of licences, permits, agreements, plans and payment records.</li><li>Mark missing or expired documents and any mismatch with the current site.</li><li>Confirm the applicable obligations and submission routes with the relevant authority.</li><li>Assign corrective work, its budget and a completion date.</li><li>Keep the resulting evidence and schedule the next review around renewal dates and operational changes.</li></ol>
<p>This sequence also helps a lender or technical adviser understand the project. Share controlled copies and keep originals and access credentials secure.</p>
${renderArticleFaqs("mining-commission-compliance-2026", "en")}
<h2 id="conclusion">Make compliance usable on site</h2>
<p>A sound compliance file connects each permission and plan to the activity it governs and the person implementing it. Begin with the licence and current layout, confirm the project-specific requirements, and close gaps with evidence. That gives you a practical basis for operating and changing the mine, rather than a checklist completed only for an inspection.</p>
<h2 id="basis">Sources and scope</h2>
<p>The official licensing and NEMC resources linked above were reviewed for this guide on 5 October 2026. The action-register example is an editorial planning method, not an official prescribed form. Current fees, deadlines and individual licence conditions must come from the relevant authority.</p>`
export default content
