import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>A remote mine needs a power system that can start its equipment, support the production schedule and keep essential services available during interruptions. Adding motor ratings gives only part of that picture. Actual demand, starting conditions, fuel logistics and maintenance determine whether the system is operable and affordable.</p>
<p>This guide helps an owner prepare a load assessment and compare diesel, grid and hybrid options with an electrical designer. It includes a fuel-cost example, while keeping equipment selection and protection settings within project-specific engineering.</p>
<h2 id="load-list">Begin with the load list and schedule</h2>
<p>List each motor and other load with its nameplate, duty, operating hours, starting method and simultaneous operation. Separate connected load, sustained demand and transient starting demand. Identify essential loads such as dewatering or process systems that need a defined response to power loss.</p>
<p><a href="https://www.cat.com/en_US/by-industry/electric-power/electric-power-resources/genset-sizing.html">Caterpillar’s sizing guidance</a> includes running and surge demands, while its <a href="https://www.cat.com/en_IN/exclusive/industry/electric-power/electric-power-webinars/right-sizing-gensets-for-motor-loads.html">motor-load reference</a> explains why motor characteristics matter. Have the designer assess starting sequence, voltage and frequency response rather than applying a single current multiplier to every motor.</p>
<p>For a first figure before you speak to a designer, our <a href="/generator-rental#generator-size-calculator">generator sizing calculator</a> turns a load list into a generator size, allowing for motor starting and an 80% load limit.</p>
<h2 id="supply-options">Compare supply around the actual duty</h2>
<p>A grid option needs a confirmed connection cost, available capacity, tariff and reliability assessment for the site. Diesel generation needs the appropriate manufacturer rating for the operating duty, a fuel-consumption curve, service plan and supply logistics. Neither option should be selected from a generic claim that it is always cheaper.</p>
<p>A solar-and-storage or solar-diesel option needs an hourly load profile and a design for periods when solar output is low. Assess usable storage, dispatch, reserve supply and maintenance. Solar energy during the day does not by itself establish that a mill can run throughout the night.</p>
<h2 id="fuel-example">Build a monthly fuel model</h2>
<p>Assume an average delivered electrical demand of 120 kW for 20 hours/day over 26 days. Monthly energy is 120 × 20 × 26 = 62,400 kWh. At an assumed 0.27 litres/kWh, diesel consumption is 16,848 litres. At an assumed USD 1.20/litre, fuel costs USD 20,217.60 for the month.</p>
<p>These are planning assumptions, not a generator guarantee or current Tanzanian diesel price. The example excludes lubricant, maintenance, distribution losses, backup operation, transport and storage costs. Replace the consumption factor with the selected equipment’s performance at the modelled load and confirm the delivered fuel price.</p>
<h2 id="sensitivity">Test utilisation and changing load</h2>
<p>In the same assumed case, adding 20 kW of average demand adds 10,400 kWh/month. Holding the assumed consumption factor and price constant, that adds USD 3,369.60 in fuel. Real generator efficiency varies with load, so the designer should recalculate the actual dispatch case rather than assume the factor stays unchanged.</p>
<p>Include ramp-up, maintenance and standby operation in the schedule. A plant’s installed kilowatts, average draw and monthly energy are different numbers. Keeping them distinct makes equipment offers and operating forecasts easier to compare.</p>
<h2 id="grid-connection">Assess a grid connection on the same basis</h2>
<p>Where a power line runs near the site, ask <a href="https://www.tanesco.co.tz/">TANESCO</a> for a connection assessment before assuming grid power is cheaper or out of reach. The answer you need covers the capacity available on the nearest line, the cost and timetable of any line extension and transformer, the tariff category that would apply and the connection terms. Tariffs are approved by the regulator, <a href="https://www.ewura.go.tz/">EWURA</a>, so confirm the current schedule for your category rather than relying on a figure from another site.</p>
<p>Compare the two options per kilowatt-hour on the same monthly energy. In the assumed fuel model above, fuel alone costs 0.27 litres × USD 1.20 = about USD 0.32 per kWh before maintenance and generator capital. For the grid, add the energy and any demand or service charges from the tariff to the connection cost spread over a sensible period. As assumed arithmetic, a USD 60,000 connection spread over 36 months is about USD 1,667 a month, or roughly USD 0.03 per kWh at 62,400 kWh a month. Replace both sides with your quotation and tariff. Ask neighbouring operations about outage history too, because even a cheaper grid supply needs standby generation for dewatering and other essential loads.</p>
<h2 id="hybrid">Size a solar-diesel hybrid from the hourly profile</h2>
<p>A solar array can reduce daytime fuel use, but a plant that runs into the night still needs storage or a generator after sunset. The useful first estimate is the share of daily energy that falls in solar hours. In the assumed case, the plant uses 120 kW for 20 hours, or 2,400 kWh a day. If solar could carry the full load for an assumed 6 daytime hours, that is 720 kWh, or about 30% of daily energy, before allowing for cloudy days, storage losses and the generator’s minimum load.</p>
<p>The designer then checks practical limits: whether the inverter can handle motor starting, the minimum load at which the generator can run efficiently alongside solar, the storage needed to cover short clouds or evening loads, and the maintenance and security of the array. A hybrid makes most sense where the plant runs mainly in daylight, fuel delivery is expensive or unreliable, and the operation expects to stay at the site for long enough to recover the array’s cost.</p>
<h2 id="site-system">Include distribution and operating readiness</h2>
<p>Budget cables, switchgear, protection, earthing, control integration and commissioning alongside the source equipment. Fuel storage and handling, exhaust, access and fire controls belong in the site assessment. Installation needs qualified design and inspection, not improvised changes during startup.</p>
<p>Agree the outage response and restart sequence with the operations team. Confirm who maintains the power equipment and which spares are critical. Our <a href="/insights/gold-plant-setup-cost">plant startup guide</a> includes utilities and owner works in the capital scope.</p>
${renderArticleFaqs("off-grid-mine-power", "en")}
<h2 id="conclusion">Design for starting, production and interruptions</h2>
<p>Prepare a load list and hourly schedule, assess starting conditions and cost the complete supply system. Compare realistic operating cases rather than one nameplate or fuel factor. Your next step is a coordinated electrical brief that lets suppliers model the same duty and explain their selection.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Manufacturer references were reviewed on 5 October 2026; the grid and hybrid sections were added on 7 October 2026 and use assumed connection costs and solar hours. Example fuel and price inputs are assumed and match the illustrative alluvial operating model in the public plant-cost guide. No electrical protection or installation settings are prescribed.</p>`
export default content
