import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Test work helps turn a gold occurrence into a processing decision. An assay establishes gold content in a sample, while metallurgical tests investigate how that gold can be recovered and what the process consumes. A high assay alone cannot size a mill, select leaching or establish an operating budget.</p>
<p>This guide explains how to commission a useful programme before buying a plant. You should leave able to describe the feed, ask for tests that answer the design questions and request results that can support a supplier’s specification.</p>
<h2 id="representative-sample">Start with a sample plan</h2>
<p>Identify the material the plant will treat over time: ore types, weathering zones, grade ranges and any tailings sources. Keep sample location, depth, mass and preparation records. A deliberately selected high-grade piece may demonstrate mineralisation but cannot represent the planned feed schedule.</p>
<p>Ask the laboratory how much material each test requires before collection. Some tests need intact pieces or particular size fractions; others need a composite prepared from defined domains. Retain separate variability samples where blending would conceal important differences.</p>
<h2 id="test-questions">Match each test to a decision</h2>
<p>Assays and mineralogy establish content and associations. Gravity testing investigates physical recovery. Leach tests assess extraction with time and consumption under specified conditions. Comminution tests support crushing and grinding selection. The <a href="https://www.sgs.com/-/media/sgscorp/documents/corporate/brochures/sgs-canada-inc-minerals-comminution.cdn.en-CA.pdf">SGS comminution reference</a> describes grindability work, while its <a href="https://www.sgs.com/-/media/sgscorp/documents/corporate/brochures/sgs-nr-gold-processing-en.cdn.en-KZ.pdf">gold-processing overview</a> explains the wider process-development context.</p>
<p>If vat or heap treatment is considered, ask for work addressing liquid flow through prepared material. If a carbon circuit is proposed, include the relevant adsorption and downstream duties. The cheapest isolated test may not answer the question that controls the equipment investment.</p>
<h2 id="compare-tests">Read comparisons under the same conditions</h2>
<p>Ask for feed preparation, grind or crush size, duration, solution conditions, consumption and residue assays alongside recovery. Compare tests from the same material and understand any changed input. A result achieved at a finer grind is not directly comparable with a coarser-grind result on power cost alone.</p>
<p>For a hypothetical 100 g gold feed, one test recovering 80 g and another recovering 90 g differ by 10 g. To value that improvement, you need the additional grinding, treatment and downstream costs and whether the second test represents the proposed production conditions. The example is arithmetic, not a predicted recovery.</p>
<h2 id="results">Request a report that engineering can use</h2>
<ul><li>Sample identity, origin, preparation and representativeness limitations.</li><li>Methods, conditions and complete result tables, including unsuccessful tests.</li><li>Mass and gold balances, duplicates and relevant quality checks.</li><li>Recovery and consumption against time and size where measured.</li><li>Variability between feed domains and unresolved process questions.</li><li>Recommendations for further work and the limits of scaling the results.</li></ul>
<p>A summary saying “suitable for CIL” is not enough for a designer to establish a reliable duty. Keep the underlying report and raw records available for technical review.</p>
<h2 id="programme-budget">Scope cost and schedule rather than assume a package price</h2>
<p>Get a written laboratory proposal stating sample requirements, tests, consumables, reporting, turnaround, transport and retained-sample arrangements. This guide publishes no universal testing price or duration because programme size and test sequence differ materially.</p>
<p>Stage the work around decisions. An initial response may justify more detailed variability or pilot work, or reveal that a proposed route should be reconsidered. Reserve budget for interpretation and additional tests instead of treating the first quote as the complete development programme.</p>
${renderArticleFaqs("plant-test-work-guide", "en")}
<h2 id="conclusion">Use tests to write the plant brief</h2>
<p>Collect representative material, commission tests tied to the design choices and obtain results that explain both performance and limitations. Then turn those results into feed, duty, utility and operating assumptions for the plant. Begin with a sample inventory and the specific question that must be resolved before equipment selection.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Laboratory references were reviewed on 5 October 2026. The recovery comparison is hypothetical. A laboratory result is not an installed-plant guarantee without an agreed engineering and acceptance basis.</p>`
export default content
