const content = `<p>A platinum-group metal project in Zimbabwe needs evidence about the mineralised horizon, its continuity and its metal composition. A single combined grade can hide differences that matter to processing and sales. The exploration programme should collect both geological information and representative material for process assessment.</p>
<p>This guide explains how to frame a Great Dyke target and move from mapping to a reviewable drill and metallurgical dataset. Its practical aim is to connect the reported grade to the product and development questions that follow.</p>
<h2 id="great-dyke">Use the mineralised horizon as a geological model</h2>
<p><a href="https://implats-ir.co.za/reports/implats-iar-2014/implats-minerals-report-2014/the-great-dyke.php">Implats’ geological description of the Great Dyke</a> identifies the Main Sulphide Zone as a host for PGM and associated base-metal mineralisation. This is a geological reference from a dated report; it is not a current resource estimate for a new property.</p>
<p>Compile the local stratigraphy, maps and historical holes and test where the horizon occurs, how it dips and what interrupts it. Do not transfer the thickness, grade or operating assumptions of a nearby mine into your target without evidence.</p>
<h2 id="drilling">Design core work to test continuity</h2>
<p>Use hole orientations and sampling intervals that can establish the mineralised package and its structural relationships. Keep collar and downhole surveys, recovery, logging, photographs and assay intervals linked. Investigate faulting, weathering and domains that may affect mining or process behaviour.</p>
<p>Separate observed downhole lengths from interpreted true thickness. For a narrow horizon, dilution and mining selectivity can materially change the feed grade even when the geological interpretation is sound.</p>
<h2 id="assays">Specify the metals behind the grade</h2>
<p>State exactly which elements are included in a combined grade such as 3E, 4E or 6E, and report the component assays where needed. Naming conventions must be explained in the project report rather than assumed. Use appropriate laboratory methods and reference materials for the expected metal suite.</p>
<p>For an illustrative assay of 2.0 g/t platinum, 1.0 g/t palladium and 0.2 g/t gold, their explicitly defined sum is 3.2 g/t. That total does not mean the three metals share the same price, recovery or payability. The values are teaching assumptions, not a Great Dyke grade prediction.</p>
<h2 id="metallurgy">Assess recovery and payable products</h2>
<p>Test mineralogy and the proposed concentration route on representative domains. Establish which metals enter the product and which remain in residues. Discuss concentrate quality, impurities, smelting or refining terms and qualification with suitable counterparties.</p>
<p><a href="https://www.usgs.gov/centers/national-minerals-information-center/zimbabwe">USGS’s Zimbabwe industry page</a> provides dated PGM-sector context. Use it to understand the industry, while obtaining current commercial and product terms for the actual project. A quoted platinum price cannot be applied to all combined metal ounces.</p>
<h2 id="development-brief">Include mine and infrastructure constraints</h2>
<p>Evaluate horizon geometry, ground conditions, access, ventilation and water alongside power and processing requirements. Confirm the applicable mineral rights, environmental route and product movement rules through local specialists. Avoid placing one universal legal or ownership rule in an early technical brief.</p>
<p>Request a phased report that ranks uncertainties and explains the next work: continuity drilling, geotechnical assessment, metallurgical variability or product discussions. The priorities should follow what can change the development case.</p>
<h2 id="conclusion">Connect the horizon to a payable metal basket</h2>
<p>Establish local geometry and component grades, test the recovery route and understand the product terms before evaluating a PGM project. Your next step is a coordinated core, assay and metallurgical brief that keeps geological continuity and metal value as separate, reviewable questions.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Geological and industry references were reviewed on 5 October 2026. The historical geological source is dated where cited. Assays are hypothetical; no current resource, mine ownership or production target is claimed.</p>`
export default content
