const content = `<p>The price offered for a gram of gold is only one part of a sale. Weight, fineness, valuation, statutory deductions and payment timing determine what reaches your account. For a Tanzanian miner, a good sale also leaves a record of the gold’s legal origin and how the buyer calculated the settlement.</p>
<p>This guide explains how to prepare a sale, compare a licensed buyer with the Bank of Tanzania programme, and understand the 20% allocation without treating every domestic purchase as the same transaction. Use it to request a written settlement calculation before you deliver gold.</p>
<h2 id="buyer">Confirm who is buying and under which authority</h2>
<p>The <a href="https://www.tumemadini.go.tz/pages/mineral-royalties-and-inspection-fees-rates/">Mining Commission’s trading guidance</a> identifies mineral-right holders and licensed dealers and brokers as authorised trading participants. Verify the buyer’s current licence, permitted activity and purchasing location with the Commission. An introduction from another miner or an attractive price is not sufficient verification.</p>
<p>For a market transaction, ask the local office which documents you need for your seller category and how valuation and receipts will be handled. Keep the production or acquisition records supporting the lot. Swahili readers can use our <a href="/mrabaha-na-kodi-za-dhahabu">guide to deductions</a> and information about <a href="/soko-la-madini/chunya">the Chunya mineral market</a>.</p>
<h2 id="valuation">Understand the unit being priced</h2>
<p>Gross weight includes material that may not be pure gold. Ask whether the quotation is per gross gram or per fine-gold gram, which assay establishes fineness, and how a disagreement will be resolved. Observe weighing where permitted and obtain the assay reference used for settlement.</p>
<p>For an illustrative lot weighing 100 g at an agreed 90% fineness, the fine-gold content is 100 × 0.90 = 90 g. If the assumed price is TSh 300,000 per fine-gold gram, the starting value is TSh 27,000,000. These are teaching assumptions, not today’s price or a substitute for official valuation. Deduct charges from the appropriate confirmed base, rather than silently applying them to a different weight or value.</p>
<h2 id="bot">What the Bank of Tanzania programme says</h2>
<p>BoT’s <a href="https://www.bot.go.tz/Adverts/PressRelease/en/2024100206312713.pdf">1 October 2024 notice</a> described a 4% royalty, no inspection fee, zero-rated VAT and payment within 24 hours after confirmation of the approved refinery’s fire-assay report. It also said BoT would cover refining costs. Those are dated programme terms; confirm the terms, approved route and documentation for your transaction before relying on them.</p>
<p>The distinction matters for cash flow. A payment period linked to assay confirmation does not start automatically when you hand over the lot. Ask who transports and insures it, when the assay will be available and who communicates acceptance and settlement.</p>
<h2 id="allocation">Treat the 20% allocation as a specific obligation</h2>
<p>The Bank’s <a href="https://www.bot.go.tz/Publications/Other/The%2050th%20Anniversary%20of%20Bank%20of%20Tanzania/sw/2026061710500724.pdf">2026 anniversary publication</a> describes the allocation as 20% of gold exports for purchase by BoT, applying to mineral-right holders and licensed dealers under section 59 of the Mining Act. This is more precise than saying every miner simply sells 20% to any domestic buyer.</p>
<p>If you export or sell through someone who exports, obtain instructions from the Commission and BoT on allocation, documentation and any release procedure. Do not assume a sale at a mineral market automatically proves compliance with a separate export obligation.</p>
<h2 id="settlement">Compare the amount and timing you will receive</h2>
<p>Request an itemised settlement showing valuation, royalty, inspection charges where applicable, other statutory deductions, buyer charges and net proceeds. The Commission’s published schedule gives a general 6% gold royalty and identifies exceptions; it must be read alongside the applicable law and programme terms. A discounted refinery rate should be confirmed for the actual buyer, rather than inferred from the word “refinery.”</p>
<p>Using the assumed TSh 27,000,000 value solely to practise arithmetic, a 6% deduction is TSh 1,620,000 and a separate 1% deduction is TSh 270,000. The remaining TSh 25,110,000 is before any other applicable charge. This example does not establish that those two charges are the complete or correct deductions for your sale.</p>
<h2 id="records">Keep a sale file that reconciles</h2>
<p>Retain the lot identifier, weight record, assay, valuation, buyer details, statutory receipts and bank-payment reference. Reconcile the receipt with the amount actually paid. A consistent record supports production accounting and helps explain sales when applying for <a href="/insights/small-miner-financing">finance</a>.</p>
<h2 id="conclusion">Agree the settlement before the sale</h2>
<p>Choose a verified route, understand how weight and purity become a payable value, and confirm deductions and payment triggers in writing. The useful comparison is the net amount you can document and the time needed to receive it. Prepare one lot’s records and request that calculation before committing the gold.</p>
<h2 id="basis">Sources and example basis</h2>
<p>Official Commission and BoT publications were reviewed on 5 October 2026. Historical programme terms are dated where cited; examples use assumed prices and fineness. This guide does not publish a current gold price or a complete tax assessment.</p>`
export default content
