const content = `<p>A loan helps a small mine when the funded work has a clear purpose and the business can cover repayments through an uneven production cycle. A licence and a promising sample are a starting point, but they do not establish how much feed the mine can supply or when the plant will generate cash.</p>
<p>Before approaching a Tanzanian lender, build a project file that connects geology, equipment scope, approvals and sales to a monthly cash forecast. This guide shows what to prepare, how a loan differs from hire or leasing, and how to test whether the proposed repayment is manageable.</p>
<h2 id="funding-purpose">Define what the money will accomplish</h2>
<p>Separate exploration, construction and operating finance. Sampling or drilling reduces uncertainty about the deposit; a plant purchase funds a selected process; working capital pays for fuel, labour and consumables before sales arrive. Combining all three into “money for equipment” hides important risks.</p>
<p>For an existing operation, describe the bottleneck and the evidence behind the proposed improvement. If a new mill is expected to increase recovery, show the grinding and recovery tests and the feed it will receive. Equipment itself does not guarantee the extra revenue needed to repay a loan.</p>
<h2 id="project-file">Prepare a file a lender can assess</h2>
<ul><li>Licence, company or owner identification, rent receipts and evidence of land access.</li><li>Relevant approvals and any outstanding compliance actions.</li><li>Geological and metallurgical evidence, with sample locations and test limitations.</li><li>Itemised equipment, delivery, installation and site-work quotations.</li><li>Sales receipts and business bank records, where the mine already operates.</li><li>A monthly cash forecast including startup, ramp-up, deductions and debt service.</li><li>The proposed security and any existing borrowing commitments.</li></ul>
<p>These are preparation items, not a promise that every lender requires or accepts the same file. Ask for the institution’s own application checklist and identify missing evidence before paying for a full application.</p>
<h2 id="available-options">Compare the contract as well as the interest rate</h2>
<p>A term loan generally leaves you responsible for purchasing and maintaining the asset while meeting scheduled repayments. A lease may tie the equipment to a financing contract with specific ownership and default provisions. Hire supplies access for a period and can suit a short trial, although mobilisation and standby costs still matter.</p>
<p><a href="https://www.crdbbank.co.tz/en/for-business">CRDB’s business-finance page</a> lists SME loans, asset finance and working-capital facilities. It is a place to ask about eligibility, not evidence that a mining project will be approved. Obtain current written offers from suitable lenders and compare deposit, fees, security, grace period, repayment currency and total amount payable. This guide does not publish a mining loan rate or claim a subsidy is available.</p>
<h2 id="cash-example">Test the repayment against a weaker month</h2>
<p>Assume, for a planning exercise, that a mine receives TSh 30 million a month after selling deductions and spends TSh 21 million on operating outgoings. That leaves TSh 9 million before debt service, taxes not already included and owner withdrawals. A proposed TSh 5 million repayment would leave TSh 4 million, but that alone does not demonstrate affordability.</p>
<p>If receipts fall by 20% to TSh 24 million while operating outgoings remain TSh 21 million, only TSh 3 million is available before the repayment. The same contract then creates a TSh 2 million monthly shortfall even before the omitted obligations. These are assumed figures; replace them with your sales and expense records and test commissioning delays as well as lower production.</p>
<h2 id="startup">Keep construction contingency and working cash separate</h2>
<p>Contingency covers uncertainty in the project scope or cost estimate. Operating cash covers the period when the equipment is installed but receipts are delayed or production is below plan. Neither should disappear into the supplier’s deposit. Our <a href="/insights/gold-plant-setup-cost">startup-budget guide</a> shows these as separate lines.</p>
<p>Where revenue and debt are in different currencies, model exchange-rate changes explicitly. A cheaper quoted interest rate can still leave the business with a repayment it cannot predict in its selling currency.</p>
<h2 id="conclusion">Finance a tested use of funds</h2>
<p>Take lenders a defined scope, evidence of feed and recovery, and a cash forecast that survives a weaker month. Compare written offers on their complete obligations and keep enough operating cash for ramp-up. If the downside case cannot pay the instalment, revise the project size, funding structure or timetable before signing.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>The lender product page was reviewed on 5 October 2026. The cash-flow example is editorial arithmetic, not a borrower’s records or a credit recommendation. Lending eligibility, security and terms must be confirmed directly with the institution.</p>`
export default content
