const content = `<p>An enquiry for underground “air supply” can mean ventilation for the working environment or compressed air for pneumatic tools. These systems serve different purposes and need separate designs. Buying a compressor does not establish suitable ventilation, and a fan does not supply the pressure a drill requires.</p>
<p>This guide explains the distinction and the information to take to a qualified designer. The aim is a clear equipment brief and verification plan; it does not provide a universal airflow allowance, gas limit or instruction to re-enter a working.</p>
<h2 id="two-systems">Separate the two duties</h2>
<p>Ventilation moves air through the mine to manage the underground environment and contaminants. It depends on the working layout, equipment, activities, pathways and operating controls. Compressed air supplies tools through a pressurised distribution system, with demand defined by the tools and their simultaneous use.</p>
<p>The <a href="https://stacks.cdc.gov/view/cdc/161141">NIOSH mine-ventilation fundamentals</a> describe airflow and its distribution. They are a technical reference, not Tanzanian approval criteria. Site requirements and operating limits must be established by the responsible specialists under the applicable rules.</p>
<h2 id="ventilation-brief">Give the ventilation designer the mine layout</h2>
<p>Provide workings, depths, lengths, cross-sections, connections, occupied areas, diesel equipment and planned activities, including blasting where relevant. Identify existing air routes, fans, ducts and measurement records. Changes in workings or equipment can change the ventilation duty and should trigger reassessment.</p>
<p>Fan selection needs the operating point of airflow and pressure against the system resistance, rather than motor power alone. Duct condition, restrictions and leakage affect what reaches the intended location. Measure the relevant locations through an approved survey plan instead of assuming airflow at the fan proves conditions elsewhere.</p>
<h2 id="distribution">Treat air routing as part of the design</h2>
<p>Stoppings, ducts and connections direct air rather than merely accompany the fan. <a href="https://www.cdc.gov/niosh/docs/mining/works/coversheet808.html">NIOSH’s stopping guidance</a> illustrates the role of controlling flow paths. An additional fan can change the network, so any modification needs assessment rather than a purchase based on a local complaint alone.</p>
<p>For a purely illustrative reading comparison, an instrument records 5 m³/s at one location and 4 m³/s downstream under comparable conditions. The difference is 1 m³/s, or 20% of the first reading. That calculation identifies a question for investigation; it establishes neither the cause nor whether either reading is adequate or safe.</p>
<h2 id="compressed-air">Specify tool demand at the required pressure</h2>
<p>Record each tool’s manufacturer demand, pressure, simultaneous duty and air-quality requirements. Include pipe or hose lengths, elevations, fittings and the supply equipment’s rating basis. Pressure loss and leakage need assessment alongside volume, and compressor figures expressed under different reference conditions cannot simply be compared.</p>
<p><a href="https://www.epiroc.com/content/dam/epiroc/rock-drilling-tools/documents/9866%200277%2001%20Secoroc%20COP%20M6%20%E2%80%93%20operator%27s%20instructions%20and%20spare%20parts%20list.pdf">Epiroc’s model-specific drilling instructions</a> demonstrate that air capacity and pressure belong to the equipment specification. Use the actual tool manual; the cited model is not a recommendation for your mine.</p>
<h2 id="readiness">Plan inspection, monitoring and interruptions</h2>
<p>Have qualified personnel assess electrical supply, fan and compressor installation, pressure systems, guarding, isolation and maintenance. Agree what happens if ventilation or power fails and who can authorise work or re-entry. A gas detector or compressed-air line does not replace a functioning ventilation system.</p>
<p>Include surveys, calibration where relevant, training and critical spares in the operating budget. Keep records linked to the current layout so an expanding working does not continue under an obsolete equipment brief.</p>
<h2 id="conclusion">Specify each air system for its purpose</h2>
<p>Separate environmental ventilation from tool air, provide the layout and equipment data, and have the complete distribution duties assessed. The next step is a site survey and design brief with documented measurement and failure-response responsibilities. Choose fans and compressors only after that basis is established.</p>
<h2 id="basis">Sources and scope</h2>
<p>Technical references were reviewed on 5 October 2026. The flow comparison is illustrative and cannot establish safe working conditions. Operating limits and emergency procedures require site-specific professional assessment.</p>`
export default content
