const content = `<p>Old tailings, often called marudio, can retain gold, but a reprocessing project needs more than a promising assay. You must establish how much material is available, how it was previously treated and whether solution can reach the remaining gold. Those questions determine whether vat leaching is a credible option.</p>
<p>This guide explains the assessment before building a vat site. Its purpose is to help you specify sampling and tests, calculate a batch’s potential output and budget the route to saleable gold. It does not provide a cyanide dosing or operating procedure.</p>
<h2 id="material">Define the material and the right to treat it</h2>
<p>Confirm ownership and any agreement to move or process the tailings. Map volumes, depths, different sources and evidence of prior treatment. A sample from the richest visible surface patch does not represent the whole stockpile, and an earlier buyer’s assay should not replace your own documented programme.</p>
<p>Include contaminants in the assessment, particularly where mercury amalgamation was used. The <a href="https://www.epa.gov/international-cooperation/artisanal-and-small-scale-gold-mining-without-mercury">EPA’s mercury-free processing guidance</a> identifies the concern with cyanide treatment of mercury-bearing tailings. Have specialists assess handling and treatment before procuring chemicals.</p>
<h2 id="vat-response">Test permeability as well as extraction</h2>
<p>Vat leaching brings solution into contact with material held in a vessel, with collection and downstream recovery. Particle size, fines, clay and drainage influence that contact. A bottle-roll extraction test on agitated material does not demonstrate that solution will pass through a full vat at the same recovery or rate.</p>
<p>Ask the metallurgical laboratory for tests that represent the proposed loading, preparation and flow conditions. Compare extraction over time, permeability and residue behaviour. If regrinding or agitated treatment is being considered, test it as a separate option and cost the additional equipment.</p>
<h2 id="batch-example">Calculate the value basis of a batch</h2>
<p>Assume a 100 dry t batch grading 1.0 g/t. It contains 100 g of gold. At a hypothetical 60% overall recovery to the final product, the batch produces 60 g. These values are teaching assumptions; neither an assay nor a dissolution result proves the final-product recovery.</p>
<p>For economics, use payable value after the relevant sale deductions and subtract material purchase, transport, preparation, reagents, pumping, labour, analysis, carbon handling and residue costs. Include the elapsed loading, leaching, draining and unloading cycle. A batch can appear profitable per tonne while tying up cash for longer than the operator can afford.</p>
<h2 id="site-scope">Define the full facility</h2>
<p>The design needs vessels, containment, drainage and solution storage; pumping and recovery equipment; safe chemical storage and handling; sampling; and a managed residue route. An elution arrangement is needed where gold is collected on carbon. Obtain terms for a <a href="/insights/gold-elution-plant-price">toll facility or owned plant</a> before assuming loaded carbon is cash.</p>
<p>Prepare a water balance that includes rainfall and abnormal conditions. Liner selection, pond capacity, leak response and structural design require engineering. A drawing of a lined vat alone does not establish that the site can contain its complete solution inventory.</p>
<h2 id="readiness">Confirm approval and operating responsibilities</h2>
<p>Have the relevant authorities confirm licensing, environmental and chemical requirements for the actual activity. Use the <a href="https://cyanidecode.org/about-the-cyanide-code/the-cyanide-code/">Cyanide Code</a> as a management reference where appropriate, together with specialist procedures, training and emergency planning.</p>
<p>Assign responsibility for sampling, inventory, maintenance and operating decisions. Keep batch records linking incoming material to residue, solution, carbon and final settlement. This is how you distinguish lower feed grade from a process loss or delayed gold inventory.</p>
<h2 id="conclusion">Prove the batch before building the site</h2>
<p>Establish representative grade, material rights, contaminants and vat-specific process response, then cost the whole batch cycle and final-product route. If permeability or handling prevents reliable operation, compare another process before committing to construction. Your next step is a mapped tailings inventory and a test brief that answers those uncertainties.</p>
<h2 id="basis">Sources and scope</h2>
<p>References were reviewed on 5 October 2026. The batch calculation is hypothetical. Site design, chemical settings and approvals require project-specific professional assessment.</p>`
export default content
