import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>A gold plant uses far more water than most owners expect, and in many Tanzanian districts water is the limit on how long a plant can run in the dry season. Recycling process water lets a plant keep operating with a smaller fresh supply, reduces what leaves the site and protects nearby water users. Doing it well means knowing how much water each part of the plant uses, settling or thickening the solids so the water can return, and keeping process water separate from clean water and rain runoff.</p>
<p>This guide explains how to build a simple water balance, choose between settling ponds and a thickener, and plan for the rains. A worked example for an alluvial wash plant shows how recycling changes the fresh-water requirement. It does not cover chemical treatment of cyanide-bearing water, which needs a specialist design.</p>
<h2 id="water-balance">Start with a water balance</h2>
<p>A water balance lists where water enters the plant, where it is used and where it leaves. The main uses are washing and screening, grinding, gravity recovery and, in hard-rock plants, leaching. Water leaves in tailings, in damp concentrate and stockpiles, through evaporation from ponds and through any discharge. The difference between what the plant uses and what it can recover is the make-up water the supply must provide.</p>
<p>Washing equipment sets the scale on alluvial sites. A <a href="/equipment/trommel-screen">trommel</a> commonly uses 1–3 cubic metres of water per cubic metre of feed, and a <a href="/equipment/rotary-scrubber">rotary scrubber</a> in heavy clay 2–5 cubic metres. Measure your actual flows with a flow meter or a timed bucket where possible; estimates based on equipment ratings are a starting point, not a balance.</p>
<h2 id="settling">Settle the solids so the water can return</h2>
<p>Water can only be reused once most of the solids have settled out. On small plants this is usually done in a series of settling ponds: the first pond catches coarse sand, and later ponds give finer particles time to settle before clear water is pumped back. Clay-rich feed settles slowly, so ponds for clay ore need more area or more time, and a flocculant may be worth testing with a supplier.</p>
<p>A thickener does the same job in a tank. Slurry enters the centre, solids settle to the bottom and are pumped out as a dense underflow, and clear water overflows the rim for reuse. It needs less land than ponds and returns water faster, but costs more and needs power and operator attention. Hard-rock plants with grinding and leaching often use a thickener; alluvial wash plants usually start with ponds. Where water is very scarce, a <a href="/equipment/filter-press">filter press</a> can recover still more water from tailings.</p>
<h2 id="worked-example">A worked example for a wash plant</h2>
<p>Assume an alluvial wash plant treats 50 cubic metres of feed an hour and uses 2 cubic metres of water per cubic metre of feed, so it circulates 100 cubic metres of water an hour. Without recycling, a 10-hour day would need 1,000 cubic metres of fresh water. If settling ponds return an assumed 80% of that water, the plant needs only about 20 cubic metres of make-up an hour, or 200 cubic metres a day, to replace what is lost in tailings, evaporation and seepage.</p>
<p>The ponds must be large enough for the water to settle before it returns. If the clear water needs an assumed 4 hours to settle at 100 cubic metres an hour, the ponds need at least 400 cubic metres of working volume, plus space for the solids that build up and freeboard for rain. Replace these assumptions with your measured flows and a settling test on your own material.</p>
<h2 id="rain-and-separation">Plan for the rains and keep waters separate</h2>
<p>Ponds that work in the dry season can overflow in the rains. Divert clean runoff around the plant and ponds with drains, keep freeboard in every pond and plan where excess water would go in a heavy storm. Our <a href="/insights/recovering-gold-rainy-season">rainy-season guide</a> covers drainage and covered stockpiles.</p>
<p>Keep process water separate from drinking water and from streams. In plants that use cyanide, process water must stay within the designed circuit and its treated tailings facility, and any release needs the treatment and approval set out in the environmental permit. Have a specialist design that part of the system.</p>
<h2 id="next-steps">Information to prepare</h2>
<ol>
<li>Measured or estimated water use for each stage of the plant and the daily operating hours.</li>
<li>Your fresh-water source, how much it can supply in the dry season and any other users who depend on it.</li>
<li>Available land for ponds, the soil type and the site’s drainage paths.</li>
<li>A sample of tailings for a settling test, especially if the feed is clay-rich.</li>
</ol>
${renderArticleFaqs("water-recycling-gold-plant", "en")}
<h2 id="conclusion">Design the plant around the water it can recover</h2>
<p>A plant’s fresh-water need depends on how much process water it recycles. Build a water balance, settle or thicken the solids so water can return, size ponds for both settling and the rains, and keep process water separate from clean water. Start by measuring the water each stage uses and testing how quickly your tailings settle, then size the ponds or thickener from those figures.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Water-use ranges for trommels and scrubbers match our equipment pages, reviewed on 7 October 2026. The <a href="https://www.epa.gov/international-cooperation/artisanal-and-small-scale-gold-mining-without-mercury">US EPA overview of small-scale gold mining practices</a> gives wider context on processing and residues. The wash-plant example uses an assumed recycling rate and settling time to show the calculation and is not a design for any site.</p>`
export default content
