import { renderArticleFaqs } from '@/lib/article-faqs'

const content = `<p>Most small hard-rock gold operations in Tanzania grind their ore in a wet pan mill, and many of them later ask whether a ball mill would recover more gold. The answer depends on three things: how fine the ore must be ground to release its gold, how many tonnes you need to treat each day and what power and workshop support your site has. A wet pan mill is cheaper, simpler and easier to repair. A ball mill grinds finer and more consistently at higher tonnage, but it costs more to buy, power and run.</p>
<p>This guide explains how each mill works, which conditions favour each one and how to compare them for your own ore. A worked example shows the calculation for a 20-tonne-per-day operation. You should finish knowing which test results and site information settle the choice.</p>
<h2 id="how-they-work">How the two mills grind ore</h2>
<p>A <a href="/equipment/wet-pan-mill">wet pan mill</a>, sometimes called a Chilean mill, grinds crushed ore under heavy steel rollers that run around a circular pan with water. The 1,100 mm and 1,200 mm double-roller machines are the most common sizes on Tanzanian small-scale sites. They typically treat 0.5–3 tonnes per hour and produce material in the range of about 0.1–0.6 mm, discharged as a slurry that can go straight to a <a href="/equipment/shaking-table-gold">shaking table</a> or concentrator.</p>
<p>A <a href="/equipment/ball-mill-gold-ore">ball mill</a> is a rotating steel shell partly filled with steel balls. As the shell turns, the tumbling balls break the ore by impact and grinding. In gold plants, ball mills are usually set to produce 80% of the product finer than about 75–150 microns, which is finer than a pan mill normally achieves. They run continuously, often in a closed circuit with a classifier or hydrocyclone that returns oversize material for further grinding.</p>
<h2 id="what-decides">What decides the choice</h2>
<p><strong>Liberation size comes first.</strong> Gold can only be recovered once grinding has released it from the surrounding rock. If most of your gold is freed at a coarse size, a pan mill can do the job. If tests show the gold is locked in fine particles and only released below about 0.1 mm, a pan mill at the fine end of its range will leave gold in the tailings that a ball mill could release. A grind and recovery test on a representative sample answers this question; our <a href="/insights/plant-test-work-guide">test-work guide</a> explains how to commission it.</p>
<p><strong>Tonnage is the second factor.</strong> Each pan mill treats a limited amount of ore, so a growing operation adds more mills, more operators and more maintenance points. Above about 10–15 tonnes per day, one ball mill circuit usually becomes easier to run than a row of pan mills, because power and labour start to favour a single grinding line.</p>
<p><strong>Power, support and budget complete the picture.</strong> A pan mill runs on a modest diesel or electric motor and can be repaired in Mwanza or Geita workshops. A ball mill needs a larger motor, a soft starter or variable-speed drive if it runs from a generator, a crane or lifting plan for liners, and a budget for grinding media, which commonly consumes 0.3–1.2 kg of steel per tonne of ore.</p>
<h2 id="worked-example">A worked example at 20 tonnes per day</h2>
<p>Assume an operation needs to treat 20 tonnes of crushed ore per day and runs its mills for 20 hours a day. The grinding duty is therefore 1 tonne per hour.</p>
<ul>
<li>If test work shows the gold is released at about 0.3 mm and a pan mill treats an assumed 0.5 tonnes per hour on this ore, two pan mills would meet the duty, with a third worth considering as a standby while one is being relined.</li>
<li>If the same tests show that recovery only reaches an acceptable level when the ore is ground to about 0.1 mm, the pan mills would be working at the limit of their range. A small ball mill sized from a grindability test would be the more reliable choice.</li>
</ul>
<p>To compare the options, put both on the same basis: the equipment and installation cost, the power each draws over a month, labour, wear parts and media, and the extra gold the finer grind recovers according to the tests. A ball mill that recovers more gold can repay its higher cost; one installed for ore that a pan mill already liberates adds cost without adding gold. The figures in this example are assumptions for the arithmetic, not measured capacities for any machine.</p>
<h2 id="staged-approach">Starting with a pan mill and moving to a ball mill later</h2>
<p>Many operations start with pan mills while they prove the ore body and build cash flow, then add a ball mill once tonnage and test results justify it. This can work well, provided the site layout leaves room for the larger mill, its classifier and its power supply. Keep records of grind size and gold recovered from the pan mills from the start, because those records help size the ball mill later.</p>
<p>Whichever mill you use, pair it with gravity recovery rather than mercury. Adding mercury to a pan mill loses both mercury and gold to the tailings and endangers the operators. A centrifugal concentrator followed by a shaking table recovers free gold without it; see our <a href="/insights/mercury-free-gold-recovery">mercury-free recovery guide</a>.</p>
<h2 id="next-steps">Information to prepare</h2>
<ol>
<li>Collect a representative sample of the ore you will treat over the coming months, not a selected high-grade piece.</li>
<li>Ask a laboratory for a grind and recovery test at several grind sizes, and a grindability test if a ball mill is likely.</li>
<li>Record your target tonnes per day, operating hours and the crushed feed size from your crusher.</li>
<li>Note your power source and its capacity, and whether a workshop nearby can support each mill.</li>
</ol>
${renderArticleFaqs("wet-pan-mill-vs-ball-mill", "en")}
<h2 id="conclusion">Choose the mill your ore and tonnage require</h2>
<p>A wet pan mill suits small tonnage, coarse liberation and sites that need simple, locally repairable equipment. A ball mill suits finer liberation, higher tonnage and operations that can support its power, media and maintenance. Test results settle the grind question, and your daily tonnage settles the capacity question. Start with a representative sample and a grind and recovery test before committing to either mill.</p>
<h2 id="basis">Sources and assumptions</h2>
<p>Capacities, grind ranges and media consumption match our equipment pages for the <a href="/equipment/wet-pan-mill">wet pan mill</a> and <a href="/equipment/ball-mill-gold-ore">ball mill</a>, reviewed on 7 October 2026. The <a href="https://www.sgs.com/-/media/sgscorp/documents/corporate/brochures/sgs-canada-inc-minerals-comminution.cdn.en-CA.pdf">SGS comminution reference</a> describes the grindability tests behind ball mill sizing. The 20-tonne example uses assumed capacities to show the calculation and is not a performance claim for any machine.</p>`
export default content
